### ISSUE TITLE
继承BaseMapper后，自定义方法，自定义xml语句，语句包含where（id,tenant_id） in((1111122,222333)),在MySQL和Mybatis中执行均正常，在mybatis-plus中就异常

### ISSUE THREAD

**Issue by shmily2038** [baomidou/mybatis-plus#1023]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
定义一个FbOmsTemplateConfigMapper扩展BaseMapper，然后自定义一个方法stopStatusByIds
![图片](https://user-images.githubusercontent.com/16485682/56192420-e5339280-6060-11e9-8cfc-7570e4561f21.png)
，在对应的FbOmsTemplateConfigMapper.xml里，增加SQL片段
![图片](https://user-images.githubusercontent.com/16485682/56192325-ad2c4f80-6060-11e9-82c1-44fc2a8f8c42.png)

### 重现步骤
调用下这个Mapper，传入list，list中一个对象，就报错

### 报错信息
![图片](https://user-images.githubusercontent.com/16485682/56192502-18762180-6061-11e9-9ced-c7122bc8b30f.png)
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 7, column 20.

Was expecting one of:

    "&"
    "&&"
    ")"
    "::"
    "<<"
    ">>"
    "AND"
    "COLLATE"
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:6724)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:6687)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:6658)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:5675)
	at net.sf.jsqlparser.parser.CCJSqlParser.Update(CCJSqlParser.java:943)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:127)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:458)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:121)
	... 160 common frames omitted

**Comment by miemieYaho** [comment]
把该mthod用租户注解过滤

**Comment by shmily2038** [comment]
> 
> 
> 把该mthod用租户注解过滤
不知道你说的是怎么处理

**Comment by miemieYaho** [comment]
CCJSqlParser报错,无法解析你的sql,看看你是不用了多租户功能或者其他的插件,去除掉

**Comment by shmily2038** [comment]
有用多租户，分页，逻辑，版本号，我明天将多租户的去掉试试。

**Comment by shmily2038** [comment]
要将多租户的插件给去掉，不然依赖的jsqlparser就会报错。目前去掉后，使用正常
