### ISSUE TITLE
添加攻击sql阻断解析器,导致查询语句报错

### ISSUE THREAD

**Issue by BushJack** [baomidou/mybatis-plus#1108]
### 该问题是怎么引起的？**
为了避免全表删除,按照官方文档的写法,添加了一个攻击sql阻断解析器,的确是有效的.但是当我我查询的时候,使用了postgres 的函数 substring()时,括号处报错. 把这段代码注释掉,又可以正常执行.
 @Bean
    public PaginationInterceptor paginationInterceptor() {
        PaginationInterceptor paginationInterceptor = new PaginationInterceptor();
        List<ISqlParser> sqlParserList = new ArrayList<>();
        // 攻击 SQL 阻断解析器、加入解析链
        sqlParserList.add(new BlockAttackSqlParser());
        paginationInterceptor.setSqlParserList(sqlParserList);
        return paginationInterceptor;
    }

### 重现步骤
select case when a.insurance_id = 1001 then '工伤'
        when a.insurance_id = 1002 then '养老'
        when a.insurance_id = 1003 then '失业'
        when a.insurance_id = 1004 then '生育'
        when a.insurance_id = 1005 then '医疗'
        when a.insurance_id = 1006 then '长期照护'
        when a.insurance_id = 1007 then '补充医疗'
        when a.insurance_id = 1008 then '大病'
        when a.insurance_id = 2001 then '公积金'
        else '' end
        as socialType,substring(b.ought_paid_month from 5 for 6) as month
        from insu_person_payment_detail a
        left join ins_personal_payment b on a.insurance_personal_payment_id = b.person_payment_id

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select case when a.insurance_id = 1001 then '工伤'
        when a.insurance_id = 1002 then '养老'
        when a.insurance_id = 1003 then '失业'
        when a.insurance_id = 1004 then '生育'
        when a.insurance_id = 1005 then '医疗'
        when a.insurance_id = 1006 then '长期照护'
        when a.insurance_id = 1007 then '补充医疗'
        when a.insurance_id = 1008 then '大病'
        when a.insurance_id = 2001 then '公积金'
        else '' end
        as socialType,substring(b.ought_paid_month from 5 for 6) as months
        from insu_person_payment_detail a
        left join ins_personal_payment b on a.insurance_personal_payment_id = b.person_payment_id
        where b.certificate_no = ? and b.ought_paid_month like concat(?,'%')
  at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
  at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
  at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
  ... 114 more
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select case when a.insurance_id = 1001 then '工伤'
        when a.insurance_id = 1002 then '养老'
        when a.insurance_id = 1003 then '失业'
        when a.insurance_id = 1004 then '生育'
        when a.insurance_id = 1005 then '医疗'
        when a.insurance_id = 1006 then '长期照护'
        when a.insurance_id = 1007 then '补充医疗'
        when a.insurance_id = 1008 then '大病'
        when a.insurance_id = 2001 then '公积金'
        else '' end
        as socialType,substring(b.ought_paid_month from 5 for 6) as months
        from insu_person_payment_detail a
        left join ins_personal_payment b on a.insurance_personal_payment_id = b.person_payment_id
        where b.certificate_no = ? and b.ought_paid_month like concat(?,'%')
  at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:41)
  at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:78)
  at com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler.sqlParser(AbstractSqlParserHandler.java:63)
  at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:129)
  at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
  at com.sun.proxy.$Proxy238.prepare(Unknown Source)
  at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
  at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
  at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
  at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
  at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
  at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
  ... 120 more
Caused by: net.sf.jsqlparser.JSQLParserException
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:154)
  at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:64)
  ... 130 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 11, column 32.

Was expecting one of:

    "&"
    ","
    "::"
    ";"
    "<<"
    ">>"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COMMIT"
    "CONNECT"
    "DO"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FIRST"
    "FOLLOWING"
    "FOR"
    "FROM"
    "GROUP"
    "HAVING"
    "INDEX"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "INTO"
    "ISNULL"
    "KEY"
    "LAST"
    "MATERIALIZED"
    "MINUS"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TRUNCATE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "XML"
    "ZONE"
    "^"
    "|"
    <EOF>
    <K_DATETIMELITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

  at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18597)
  at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:18447)
  at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:516)
  at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)
  ... 131 more

**Comment by miemieYaho** [comment]
jsqlparser 的问题,不支持你的函数

**Comment by BushJack** [comment]
> jsqlparser 的问题,不支持你的函数

那我需要怎么做?再添加其他的jsqlparse吗

**Comment by BushJack** [comment]
> jsqlparse
我引用了一个依赖,好像就解决了
 <dependency>
	<groupId>com.github.jsqlparser</groupId>
	<artifactId>jsqlparser</artifactId>
	<version>1.4</version>
</dependency>
