### ISSUE TITLE
3.1.1版本，QueryWrapper中eq使用LocalDateTime.now()参数,jdbcType=null

### ISSUE THREAD

**Issue by MaseratiGTX** [baomidou/mybatis-plus#1112]
### 当前使用版本(必须填写清楚，否则不予处理)

mp:3.1.1，hikaricp：3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用3.1.0版本，以下代码没问题，升级到3.1.1执行这段代码会报错，LogisticquoteEntity中有LocalDateTime类型的成员属性，结果集封装会报错

 Wrapper<LogisticquoteEntity> query = new QueryWrapper<LogisticquoteEntity>() .lt("enddate", LocalDateTime.now())
 return baseMapper.selectPage(logisticquoteEntityPage, query);

### 重现步骤
LogisticquoteEntity中含有LocalDateTime类型的成员属性，像QueryWrapper这种构造条件对象中设置了LocalDateTime类型的参数

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy75.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:115)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy165.selectPage(Unknown Source)
	at com.jinying.modules.app.service.impl.LogisticquoteServiceImpl.selectLogisticquoteQdPage(LogisticquoteServiceImpl.java:75)
	at com.jinying.modules.app.service.impl.LogisticquoteServiceImpl$$FastClassBySpringCGLIB$$b0deb577.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.jinying.modules.app.service.impl.LogisticquoteServiceImpl$$EnhancerBySpringCGLIB$$45249602.selectLogisticquoteQdPage(<generated>)
	at com.jinying.modules.app.service.impl.LogisticquoteServiceImpl$$FastClassBySpringCGLIB$$b0deb577.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.jinying.modules.app.service.impl.LogisticquoteServiceImpl$$EnhancerBySpringCGLIB$$999d2b7a.selectLogisticquoteQdPage(<generated>)
	at com.jinying.modules.app.controller.LogisticquoteController.selectLogisticquoteQd(LogisticquoteController.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.jinying.common.xss.XssFilter.doFilter(XssFilter.java:24)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT  id,ORIGIN,DESTINATION,GOODS,QUANTITY,FEE,OTHERFEE,SPEREQUEST,ZHXREQUEST,INNUM,OUTNUM,CRTUSERID,CRTUSERNAME,CRTCOMPID,CRTCOMP,CRTDATE,ISDEL,REMARK,STATUSTRACK,STATUSCONFIRM,STATUS,POSPOINT,TOP,TOPDATE,GOODSDATE,ENDDATE,LOGISTICNO,XPOINT,YPOINT,GOODSID,ISDELIVERFEE,ISONEINVOICE,QDCOMPANY,QDCOMPANYID,QDUSER,QDUSERID,TRUEFEE,HOTLINE,ISPICK,CUSTFEE,UNIT,UNITTRUEFEE,UNITCUSTFEE,CONTACT,MOBILE,ISPAY,TYCOMPANYID,TYCOMPANY,TYLAWPERSON,TYDUTY,TYADDRESS,TYPOSTCODE,TYMOBILE,TYFAX,CYCOMPANYID,CYCOMPANY,CYLAWPERSON,CYDUTY,CYADDRESS,CYPOSTCODE,CYMOBILE,CYFAX,CYTRANSNO,CYBUSINESSNO,THCOMP,THADDRESS,SHCOMP,SHADDRESS,COUPONID,THEMONEY,FULLMONEY,COUPONSTARTDATE,COUPONENDDATE,MIDCOMP,MIDLAWPERSON,MIDADDRESS,MIDMOBILE,MIDFAX,JYWSIGN,YTSIGN,WLSIGN,OTHERFEEREMARK,LOADTIME,DOWNTIME,CUSTDATE,WLDATE,CONTRACTNO,ZONEID,APPRAISESTATUS,QDDATE,QDIP,LATITUDE,LONTITUDE,PAYAFTERMONEY,PAYRATEMONEY,PAYINTEREST,CUSTSEAL,ISONLINE,ISTAX,ISAPP,ISINSURANCE,SPLITID,SPLITUSER,SPLITUSERID,SPLITDATE,CONFIRMUSERID,CONFIRMUSERNAME,CUSTOMISPAY,TRUEPICK,LIFTFEE,PICKUNIT,ISCHECK,CHECKUSERID,VERID,TRANSPORTTYPE,ORIGINPORT,DESTINATIONPORT,FILEUPLOAD,UPLOADUSERID,UPLOADDATE,FILECHECKUSERID,FILECHECKDATE,FILECHECKSTATUS,STOREHOUSEID,DELIVERYTIME,DRIVINGLICENSE,VEHICLELICENSE,ISCOMMENT,ISLOGISTICPARTNER,LOGISTICPARTNERID,DIVIDENDS,ISDIVIDENDS,SHIPPINGTYPE,ISAPPQD  FROM LOGISTICQUOTE 
 WHERE  ISDEL=0

AND status > ? OR ( status = ? AND enddate < ? AND goodsdate < ? ) ORDER BY crtdate DESC ) TOTAL 

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT  id,ORIGIN,DESTINATION,GOODS,QUANTITY,FEE,OTHERFEE,SPEREQUEST,ZHXREQUEST,INNUM,OUTNUM,CRTUSERID,CRTUSERNAME,CRTCOMPID,CRTCOMP,CRTDATE,ISDEL,REMARK,STATUSTRACK,STATUSCONFIRM,STATUS,POSPOINT,TOP,TOPDATE,GOODSDATE,ENDDATE,LOGISTICNO,XPOINT,YPOINT,GOODSID,ISDELIVERFEE,ISONEINVOICE,QDCOMPANY,QDCOMPANYID,QDUSER,QDUSERID,TRUEFEE,HOTLINE,ISPICK,CUSTFEE,UNIT,UNITTRUEFEE,UNITCUSTFEE,CONTACT,MOBILE,ISPAY,TYCOMPANYID,TYCOMPANY,TYLAWPERSON,TYDUTY,TYADDRESS,TYPOSTCODE,TYMOBILE,TYFAX,CYCOMPANYID,CYCOMPANY,CYLAWPERSON,CYDUTY,CYADDRESS,CYPOSTCODE,CYMOBILE,CYFAX,CYTRANSNO,CYBUSINESSNO,THCOMP,THADDRESS,SHCOMP,SHADDRESS,COUPONID,THEMONEY,FULLMONEY,COUPONSTARTDATE,COUPONENDDATE,MIDCOMP,MIDLAWPERSON,MIDADDRESS,MIDMOBILE,MIDFAX,JYWSIGN,YTSIGN,WLSIGN,OTHERFEEREMARK,LOADTIME,DOWNTIME,CUSTDATE,WLDATE,CONTRACTNO,ZONEID,APPRAISESTATUS,QDDATE,QDIP,LATITUDE,LONTITUDE,PAYAFTERMONEY,PAYRATEMONEY,PAYINTEREST,CUSTSEAL,ISONLINE,ISTAX,ISAPP,ISINSURANCE,SPLITID,SPLITUSER,SPLITUSERID,SPLITDATE,CONFIRMUSERID,CONFIRMUSERNAME,CUSTOMISPAY,TRUEPICK,LIFTFEE,PICKUNIT,ISCHECK,CHECKUSERID,VERID,TRANSPORTTYPE,ORIGINPORT,DESTINATIONPORT,FILEUPLOAD,UPLOADUSERID,UPLOADDATE,FILECHECKUSERID,FILECHECKDATE,FILECHECKSTATUS,STOREHOUSEID,DELIVERYTIME,DRIVINGLICENSE,VEHICLELICENSE,ISCOMMENT,ISLOGISTICPARTNER,LOGISTICPARTNERID,DIVIDENDS,ISDIVIDENDS,SHIPPINGTYPE,ISAPPQD  FROM LOGISTICQUOTE 
 WHERE  ISDEL=0

AND status > ? OR ( status = ? AND enddate < ? AND goodsdate < ? ) ORDER BY crtdate DESC ) TOTAL 

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 92 common frames omitted
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT  id,ORIGIN,DESTINATION,GOODS,QUANTITY,FEE,OTHERFEE,SPEREQUEST,ZHXREQUEST,INNUM,OUTNUM,CRTUSERID,CRTUSERNAME,CRTCOMPID,CRTCOMP,CRTDATE,ISDEL,REMARK,STATUSTRACK,STATUSCONFIRM,STATUS,POSPOINT,TOP,TOPDATE,GOODSDATE,ENDDATE,LOGISTICNO,XPOINT,YPOINT,GOODSID,ISDELIVERFEE,ISONEINVOICE,QDCOMPANY,QDCOMPANYID,QDUSER,QDUSERID,TRUEFEE,HOTLINE,ISPICK,CUSTFEE,UNIT,UNITTRUEFEE,UNITCUSTFEE,CONTACT,MOBILE,ISPAY,TYCOMPANYID,TYCOMPANY,TYLAWPERSON,TYDUTY,TYADDRESS,TYPOSTCODE,TYMOBILE,TYFAX,CYCOMPANYID,CYCOMPANY,CYLAWPERSON,CYDUTY,CYADDRESS,CYPOSTCODE,CYMOBILE,CYFAX,CYTRANSNO,CYBUSINESSNO,THCOMP,THADDRESS,SHCOMP,SHADDRESS,COUPONID,THEMONEY,FULLMONEY,COUPONSTARTDATE,COUPONENDDATE,MIDCOMP,MIDLAWPERSON,MIDADDRESS,MIDMOBILE,MIDFAX,JYWSIGN,YTSIGN,WLSIGN,OTHERFEEREMARK,LOADTIME,DOWNTIME,CUSTDATE,WLDATE,CONTRACTNO,ZONEID,APPRAISESTATUS,QDDATE,QDIP,LATITUDE,LONTITUDE,PAYAFTERMONEY,PAYRATEMONEY,PAYINTEREST,CUSTSEAL,ISONLINE,ISTAX,ISAPP,ISINSURANCE,SPLITID,SPLITUSER,SPLITUSERID,SPLITDATE,CONFIRMUSERID,CONFIRMUSERNAME,CUSTOMISPAY,TRUEPICK,LIFTFEE,PICKUNIT,ISCHECK,CHECKUSERID,VERID,TRANSPORTTYPE,ORIGINPORT,DESTINATIONPORT,FILEUPLOAD,UPLOADUSERID,UPLOADDATE,FILECHECKUSERID,FILECHECKDATE,FILECHECKSTATUS,STOREHOUSEID,DELIVERYTIME,DRIVINGLICENSE,VEHICLELICENSE,ISCOMMENT,ISLOGISTICPARTNER,LOGISTICPARTNERID,DIVIDENDS,ISDIVIDENDS,SHIPPINGTYPE,ISAPPQD  FROM LOGISTICQUOTE 
 WHERE  ISDEL=0

AND status > ? OR ( status = ? AND enddate < ? AND goodsdate < ? ) ORDER BY crtdate DESC ) TOTAL 

	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:223)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:177)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy243.prepare(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:94)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy242.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 98 common frames omitted
Caused by: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL3', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #3 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #3 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: 无效的列类型
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.setParameters(MybatisDefaultParameterHandler.java:229)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:206)
	... 113 common frames omitted
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #3 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #3 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: 无效的列类型
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:71)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.setParameters(MybatisDefaultParameterHandler.java:227)
	... 114 common frames omitted
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #3 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: 无效的列类型
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:71)
	at org.apache.ibatis.type.UnknownTypeHandler.setNonNullParameter(UnknownTypeHandler.java:45)
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:69)
	... 115 common frames omitted
Caused by: java.sql.SQLException: 无效的列类型
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:8921)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:8396)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:9176)
	at oracle.jdbc.driver.OraclePreparedStatement.setObject(OraclePreparedStatement.java:9153)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:234)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:67)
	at com.sun.proxy.$Proxy244.setObject(Unknown Source)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.setNonNullParameter(LocalDateTimeTypeHandler.java:33)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.setNonNullParameter(LocalDateTimeTypeHandler.java:28)
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:69)
	... 117 common frames omitted

**Comment by miemieYaho** [comment]
不要使用 druid 连接池,druid的问题

**Comment by MaseratiGTX** [comment]
> 不要使用 druid 连接池,druid的问题

按照你说的，用了hikaricp还是出这个错

**Comment by miemieYaho** [comment]
那就给出你的复现 demo

**Comment by MaseratiGTX** [comment]
> 那就给出你的复现 demo

是jdbc驱动问题，ojdbc6换成ojdbc8就没问题了
