### ISSUE TITLE
单元测试成功，正常使用报错

### ISSUE THREAD

**Issue by pencilso** [baomidou/mybatis-plus#1137]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

//先贴Service 代码

```
    @Override
    public UserRoleModel getByLevel(Integer level) {
        UserRoleModel one = lambdaQuery().eq(UserRoleModel::getLevel, level).one();
        return one;
    }

```

//这个是Controller里的代码
```
UserRoleModel roleModel = userRoleService.getByLevel(3);
return roleModel ;
```
//这个是单元测试的代码  其实和Controller里一样的
```
        UserRoleModel roleModel = userRoleService.getByLevel(3);
        System.out.println("roleModel："+roleModel);
```

//问题在于  单元测试里面 是可以查询到数据的  但是在Controller里调用  直接就异常了
//以下是错误信息 虽然说提示信息是  没有level这个字段  但是数据库里是有的

```
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Your property named "level" cannot find the corresponding database column name!
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.lambda$getColumn$1(AbstractLambdaWrapper.java:86) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_211]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.getColumn(AbstractLambdaWrapper.java:85) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:65) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:61) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:39) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.lambda$addCondition$ac69df92$1(AbstractWrapper.java:324) ~[mybatis-plus-core-3.1.1.jar:3.1.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_211]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_211]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_211]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_211]
	at com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList.childrenSqlSegment(NormalSegmentList.java:89) ~[mybatis-plus-core-3.1.1.jar:3.1.1]

```

**Comment by miemieYaho** [comment]
移除 dev-tools
