### ISSUE TITLE
配置多租户解析后，有些SQL解析直接报错

### ISSUE THREAD

**Issue by zhongzhouping** [baomidou/mybatis-plus#1145]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

由于数据一个字段使用了全文索引 而查询时需要使用
 ` MATCH(username) AGAINST ('zhangsan')`
这样的语句

### 重现步骤
在数据库某张表建立全文索引，比如
```
DROP TABLE IF EXISTS `t_user`;
CREATE TABLE `t_user`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(32) DEFAULT NULL COMMENT '用户名',
  `tenant_id` varchar(32) DEFAULT NULL COMMENT '多租户标识',
  PRIMARY KEY (`id`) USING BTREE,
  FULLTEXT INDEX idx_username(`username`) with parser ngram
) ENGINE = InnoDB AUTO_INCREMENT=1  CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '用户表' ROW_FORMAT = Dynamic;
```
然后查询时使用这样的SQL语句来查询
`select * from t_user where MATCH(username) AGAINST ('张三')`

### 报错信息

```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL:select * from t_user where MATCH(username) AGAINST ('张三')
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy143.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany(PageMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy163.listByCommentInfoQuery(Unknown Source)

Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select * from t_user where MATCH(username) AGAINST ('张三')
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:41)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:78)
	at com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler.sqlParser(AbstractSqlParserHandler.java:63)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:129)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy223.prepare(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.util.ExecutorUtil.executeAutoCount(ExecutorUtil.java:138)
	at com.github.pagehelper.PageInterceptor.count(PageInterceptor.java:148)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:97)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy222.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 107 common frames omitted
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:154)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:64)
	... 122 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "AGAINST" <S_IDENTIFIER>
    at line 36, column 44.

Was expecting one of:

    ")"
    "."
    "AND"
    "CONNECT"
    "EXCEPT"
    "FOR"
    "GROUP"
    "HAVING"
    "INTERSECT"
    "KEEP"
    "MINUS"
    "ORDER"
    "START"
    "UNION"
    "}"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.FromItem(CCJSqlParser.java:4283)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2944)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3107)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2824)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2817)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:133)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:250)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152)
	... 123 common frames omitted
```

**Comment by miemieYaho** [comment]
jsqlparser 不支持,过滤掉该方法然后自己 set 租户条件

**Comment by zhongzhouping** [comment]
如何过滤该方法，我按照官网所示，在mapper方法里面加入@SqlParser(filter=true) 注解和加入以下配置项，但是不起效
mybatis-plus:
  global-config:
    sql-parser-cache: true

**Comment by yuxiaobin** [comment]
问题重点是： jsqlparser不支持非标准语法：where MATCH(username) AGAINST ('张三')

你换 username like '%张三%' 尽量使用标准语法来达到数据过滤

**Comment by zhongzhouping** [comment]
如果可以使用like肯定使用like的，但是like 效率太低了，所以才考虑使用全文索引的，我试过了，很多个版本，现在是3.1.1的@sqlparser(filter=true)注解是有用的
