### ISSUE TITLE
NoClassDefFoundError: org/mybatis/logging/LoggerFactory

### ISSUE THREAD

**Issue by javait90** [baomidou/mybatis-plus#1150]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1 

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

创建 SqlSessionFactory 的时候报错

### 重现步骤
 MybatisSqlSessionFactoryBean sqlSessionFactoryBean = new MybatisSqlSessionFactoryBean();
直接报错

### 报错信息

Caused by: java.lang.NoClassDefFoundError: org/mybatis/logging/LoggerFactory
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.<clinit>(MybatisSqlSessionFactoryBean.java:98)
	at com.cy.ares.dao.conf.MybatisConfiguration.sqlSessionFactoryBean(MybatisConfiguration.java:151)

**Comment by javait90** [comment]
3.1.0 有人也问过这个问题，但是我3.1.1 还是报错

**Comment by miemieYaho** [comment]
mybatis 版本冲突

**Comment by Jasonandy** [comment]
还是有问题解决不了
