### ISSUE TITLE
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ":" ":"

### ISSUE THREAD

**Issue by wangkebin1990** [baomidou/mybatis-plus#1164]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1
### 该问题是怎么引起的？**
在查询语句中带有冒号:,如：
CASE WHEN @rowtotal = pcxx.pczs THEN @rownum
WHEN @rowtotal := pcxx.pczs THEN @rownum :=@rownum + 1
WHEN @rowtotal = 0 THEN @rownum :=@rownum + 1
通过mysql可视化工具执行没问题。
### 报错信息
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:123)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60)
	... 158 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: ":" ":"
    at line 8, column 35.
Was expecting one of:

**Comment by miemieYaho** [comment]
jsqlparser 不支持解析你这种数据库方言, 注解不走租户自己设置租户条件

**Comment by wangkebin1990** [comment]
请问怎么处置呢？

**Comment by wangkebin1990** [comment]
> jsqlparser 不支持解析你这种数据库方言, 注解不走租户自己设置租户条件

请问怎么处置呢？谢谢

**Comment by wangkebin1990** [comment]
> jsqlparser 不支持解析你这种数据库方言, 注解不走租户自己设置租户条件

可以了 谢谢~

**Comment by Ivan-IT-Java** [comment]
请问是如何解决的？

**Comment by dolt131943** [comment]
同样问题，升级3.5.1后没有出现。
