### ISSUE TITLE
3.1.1版本 启动时候报错

### ISSUE THREAD

**Issue by hyzhan43** [baomidou/mybatis-plus#1197]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus   3.1.1
spring-boot   2.0.4.RELEASE

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用  声明  一个 UserMapper  extends  BaseMapper   启动的时候报错，
退回版本  3.1.0  就不会了

### 重现步骤

使用  声明  一个 UserMapper  extends  BaseMapper   启动的时候报错，
退回版本  3.1.0  就不会了

### 报错信息

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'monitorMapper' defined in file [D:\Java\WorkSpace\service-device-project\service-device\target\classes\com\kapark\cloud\mapper\MonitorMapper.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:740)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at com.kapark.cloud.ServiceDeviceApplication.main(ServiceDeviceApplication.java:20)
Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.getLanguageDriver(MybatisMapperAnnotationBuilder.java:369)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parseStatement(MybatisMapperAnnotationBuilder.java:280)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:112)
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:82)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:104)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
	... 16 common frames omitted

**Comment by miemieYaho** [comment]
问题无法复现,参照 samples

**Comment by yuxiaobin** [comment]
Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;

请参考这个FAQ排查

https://mybatis.plus/guide/faq.html#%E5%90%AF%E5%8A%A8%E6%97%B6%E5%BC%82%E5%B8%B8

**Comment by yinlijing** [comment]
我也遇到了同样的问题，感谢你的提问，退回3.1.0就好了

**Comment by NeilHao886** [comment]
同楼上，换回3.1.0就好了。问题没有解决，为什么close掉

**Comment by qmdx** [comment]
@NeilHao886 最好给出问题原因 OR 重现 demo 我们没时间去各种尝试和猜测

**Comment by LiWeiWei233** [comment]
从3.1.0升级到3.2.0的时候我也遇了到这个问题，尝试后发现是和我引用activiti-spring-boot-starter-basic6.0.0自带的mybatis包冲突了，排除activiti的mybatis就好了

**Comment by WingGao** [comment]
> Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;
> 
> 请参考这个FAQ排查
> 
> https://mybatis.plus/guide/faq.html#%E5%90%AF%E5%8A%A8%E6%97%B6%E5%BC%82%E5%B8%B8

链接里说 3.4.2 目前只有3.3.2 也是报错

**Comment by zender-projects** [comment]
这个错误到底是因为什么啊？

**Comment by zender-projects** [comment]
我升级到3.2.0，启动直接报这个异常

**Comment by zender-projects** [comment]
![image](https://user-images.githubusercontent.com/16514360/87239203-fa06fd80-c43e-11ea-8313-53ea34237d8d.png)
难道是版本内不兼容？？

**Comment by topwqp** [comment]
> 
我的也是集成    activiti-spring-boot-starter 时报错的，按照楼主说的： 排除掉mybatis对应的包，解决
  <dependency>
      <groupId>org.activiti</groupId>
      <artifactId>activiti-spring-boot-starter</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.mybatis</groupId>
          <artifactId>mybatis</artifactId>
        </exclusion>
      </exclusions>
      <version>7.1.0.M6</version>
    </dependency>

**Comment by topwqp** [comment]
> 从3.1.0升级到3.2.0的时候我也遇了到这个问题，尝试后发现是和我引用activiti-spring-boot-starter-basic6.0.0自带的mybatis包冲突了，排除activiti的mybatis就好了

我的也是集成activiti-spring-boot-starter 时报错的，按照这种方式已解决
``
```xml
  <dependency>
      <groupId>org.activiti</groupId>
      <artifactId>activiti-spring-boot-starter</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.mybatis</groupId>
          <artifactId>mybatis</artifactId>
        </exclusion>
      </exclusions>
      <version>7.1.0.M6</version>
    </dependency>
```
