### ISSUE TITLE
Error evaluating expression 'ew.nonEmptyOfEntity and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: nonEmptyOfEntity [java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space]

### ISSUE THREAD

**Issue by boy-good** [baomidou/mybatis-plus#1221]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0版本

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

不清楚什么问题引起的，定时器运行一段时间后就会出现内存溢出。

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.nonEmptyOfEntity and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: nonEmptyOfEntity [java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy74.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:168)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:82)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy82.selectList(Unknown Source)
	at com.bitoffer.wallet.common.service.impl.WalletAddressServiceImpl.selectList(WalletAddressServiceImpl.java:52)
	at com.bitoffer.wallet.eth.server.service.impl.EthWallet.getEthSatisfyAddress(EthWallet.java:368)
	at com.bitoffer.wallet.eth.server.service.impl.EthWallet.transferToCold(EthWallet.java:400)
	at com.bitoffer.wallet.eth.server.service.impl.EthWallet$$FastClassBySpringCGLIB$$eb91d010.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.bitoffer.wallet.eth.server.service.impl.EthWallet$$EnhancerBySpringCGLIB$$13b53f2.transferToCold(<generated>)
	at com.bitoffer.wallet.common.service.WalletScheduledService.transferToCold(WalletScheduledService.java:30)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by boy-good** [comment]
因为selectList的语句：

LambdaQueryWrapper<WalletAddressPo> wrapper = new QueryWrapper<WalletAddressPo>().lambda()
                .eq(WalletAddressPo::getCurrencyId, currencyId);
        return walletAddressMapper.selectList(wrapper);

**Comment by miemieYaho** [comment]
加大内存

**Comment by boy-good** [comment]
> 加大内存

我几个项目，同样的使用。分配同样的内存，但是其他项目都不会出现这个问题，不清楚为什么只有这个会，一般运行七八个小时后就崩了

**Comment by boy-good** [comment]
> 加大内存

![image](https://user-images.githubusercontent.com/39320533/58848060-b5dff000-86b7-11e9-88de-3758041069ab.png)
频繁读取数据库会导致这个问题吗
