### ISSUE TITLE
使用 Wrapper 自定义SQL出现错误

### ISSUE THREAD

**Issue by vae13** [baomidou/mybatis-plus#1242]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用 Wrapper 自定义SQL出现错误
（XML形式 Mapper.xml）
`
/**
 * @Description: 订单
 * @author：vae
 * @date：   2019-06-09
 * @version： V1.0
 */
public interface SalesOrderMapper extends BaseMapper<SalesOrder> {
    List<SalesOrder> queryJoinGoods(Wrapper ew);

}

<mapper namespace="com.zhizaikeji.modules.sales.mapper.SalesOrderMapper">
    <select id="queryJoinGoods" resultType="com.zhizaikeji.modules.sales.entity.SalesOrder">
        SELECT * from sales_order LEFT JOIN goods ON sales_order.GOODS_ID=goods.ID ${ew.customSqlSegment}
    </select>
</mapper>
`

### 报错信息

Caused by: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'ew' in 'class com.baomidou.mybatisplus.core.conditions.query.QueryWrapper'
	at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:419)
	at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:164)

**Comment by miemieYaho** [comment]
看文档

**Comment by vae13** [comment]
> 看文档

谢谢，已经解决了
