### ISSUE TITLE
经过测试mybatis-plus用3.1.0的版本的可以用druid的所有版本（包括最新的1.1.17的版本），但是mybatis-plus用3.1.1和druid的测试了从1.1.13-1.1.17都报错

### ISSUE THREAD

**Issue by ylh23y** [baomidou/mybatis-plus#1245]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.1，orcale12c,ruid的测试了从1.1.13-1.1.17

### 重现步骤

经过测试mybatis-plus用3.1.0的版本的可以用druid的所有版本（包括最新的1.1.17的版本），但是mybatis-plus用3.1.1却不能用druid的测试了从1.1.13-1.1.17都报错

### 报错信息
org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'CREATE_TIME' from result set. Cause: java.sql.SQLFeatureNotSupportedException
; null; nested exception is java.sql.SQLFeatureNotSupportedException
at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:96)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
at com.sun.proxy.$Proxy180.selectList(Unknown Source)
at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
at com.sun.proxy.$Proxy181.selectList(Unknown Source)
at com.flyfee.admin.service.impl.SysRouteConfServiceImpl.routes(SysRouteConfServiceImpl.java:57)
at com.flyfee.admin.service.impl.SysRouteConfServiceImpl$$FastClassBySpringCGLIB$$b3fd3aed.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
at com.flyfee.admin.service.impl.SysRouteConfServiceImpl$$EnhancerBySpringCGLIB$$80128694.routes()
at com.flyfee.admin.config.DynamicRouteInitRunner.initRoute(DynamicRouteInitRunner.java:46)
at com.flyfee.admin.config.DynamicRouteInitRunner$$FastClassBySpringCGLIB$$41409389.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
at java.util.concurrent.FutureTask.run(FutureTask.java)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLFeatureNotSupportedException: null
at com.alibaba.druid.pool.DruidPooledResultSet.getObject(DruidPooledResultSet.java:1771)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.logging.jdbc.ResultSetLogger.invoke(ResultSetLogger.java:69)
at com.sun.proxy.$Proxy282.getObject(Unknown Source)
at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:38)
at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:28)
at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:521)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:402)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
at com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor.intercept(PerformanceInterceptor.java:172)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy278.query(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at com.sun.proxy.$Proxy278.query(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at com.sun.proxy.$Proxy278.query(Unknown Source)
at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
... 22 common frames omitted

**Comment by ylh23y** [comment]
请问到底是druid有问题

**Comment by miemieYaho** [comment]
druid的问题

**Comment by ylh23y** [comment]
是druid的问题呢？

**Comment by ylh23y** [comment]
需要怎么改才能匹配？

**Comment by miemieYaho** [comment]
据说最新版修好了,升级,不行就换 hicaricp

**Comment by ylh23y** [comment]
我升级到最新的1.1.17还是有问题

**Comment by lzonly** [comment]
同样的错误。localdatetime这类字段，3.1.0正常，3.1.1报错

**Comment by qmdx** [comment]
这个问题是 mp 3.1.1 升级了 Mybatis 底层又升级了 jdbc 修改了 date 处理方式 druid 不支持

**Comment by xiongzehua** [comment]
mk

**Comment by abxw** [comment]
@TableField("CREATE_DATE")
 private Date createDate;
生成的实体类中  
把localdatetime修改Date成这样的 问题解决了  但不知道有没有其他问题

**Comment by 5468sun** [comment]
> 据说最新版修好了,升级,不行就换 hicaricp

换成 hikari 3.3.1 依然报同样的错。MP版本是 3.1.2

**Comment by qmdx** [comment]
> > 据说最新版修好了,升级,不行就换 hicaricp
> 
> 换成 hikari 3.3.1 依然报同样的错。MP版本是 3.1.2

那么 jdbc 驱动也换成最新的

**Comment by 5468sun** [comment]
> > > 据说最新版修好了,升级,不行就换 hicaricp
> > 
> > 
> > 换成 hikari 3.3.1 依然报同样的错。MP版本是 3.1.2
> 
> 那么 jdbc 驱动也换成最新的

管用。多谢啦。

**Comment by jingping1020** [comment]
mp 版本3.1.2 druid 版本1.1.18，还是有问题，我觉得把LocalDateTime类型修改回java.util.Date 更方便，代码生成器配置指定时间类型策略就行了：
 GlobalConfig gc = new GlobalConfig();
  gc.setDateType(DateType.ONLY_DATE);

**Comment by liukang113** [comment]
Caused by: com.jdjr.cds.driver.exception.CdsException: update语句不允许修改切分键的值:

Q:
1.数据表使用了分表策略，id和切分键都没有变，更新了其他数据，但是使用mapper.update()报错

**Comment by 97wgl** [comment]
还是不行啊，mp 3.1.0, mysql, druid 1.1.17

**Comment by qiaoqiao888** [comment]
可以增加两个jar包解决这个问题 mp-3.1.2,druid-1.1.6 亲测可以使用
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-typehandlers-jsr310</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

**Comment by bihell** [comment]
> 可以增加两个jar包解决这个问题 mp-3.1.2,druid-1.1.6 亲测可以使用
> 
> org.mybatis
> mybatis-typehandlers-jsr310
> 1.0.2
> 
> 
> com.fasterxml.jackson.datatype
> jackson-datatype-jsr310
最新的可以么

**Comment by 1346735074** [comment]
这个bug好像还没有修复

**Comment by kasiait521** [comment]
已经修复，升级druid1.1.21

**Comment by yinxingmingpx** [comment]
> 已经修复，升级druid1.1.21

3.3.1.9-SNAPSHOT版本druid1.1.21最新版本，还是报这个错呢,jdbc版本有要求吗

**Comment by eceye** [comment]
druid已经升级到了1.2.6  依然报这个错误，是咋回事？
