### ISSUE TITLE
 xml中自定义SQL分页查询，使用Map传参报错 

### ISSUE THREAD

**Issue by abciop** [baomidou/mybatis-plus#1251]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.1 

### 该问题是怎么引起的？ 
今天从2.x 升级到3.1.1 后，报错

### 重现步骤
1. xml

```
<!-- 列表分页查询 -->
    <select id="selectImagesList"  parameterType="java.util.Map" resultMap="BaseResultMap">
		select
		     t.id,
  		     t.name,
  		     t.url,
  		     t.path,
  		     t.type,
  		     t.ctime,
  		     t.isdel  
		from
			t_images as t
        <where>
			<if test="id != null">
				t.id = #{id}
			</if>
			<if test="name != null">
				AND t.name like CONCAT('%',#{name},'%')
			</if>
        </where>
    </select>
```

2. mapper

```
/**
     * 列表分页查询
     * @param page
     * @return
     */
    List<Images> selectImagesList(Page<Images> page, Map paramMap);
```

### 报错信息

3. 报错信息

```
2019-06-10 09:34:33,327 ERROR ExceptionFilter:96 -  [DUBBO] Got unchecked and undeclared exception which called by 192.168.56.1. service: com.xlauch.mall.api.facade.deve.IImagesSvc, method: selectImagesList, exception: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'id' not found. Available parameters are [, arg0, param1, param2], dubbo version: 2.7.0, current host: 192.168.56.1
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'id' not found. Available parameters are [, arg0, param1, param2]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy62.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy63.selectImagesList(Unknown Source)
	at com.xlauch.mall.svc.service.deve.impl.ImagesServiceImpl.selectImagesList(ImagesServiceImpl.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
	at com.sun.proxy.$Proxy66.selectImagesList(Unknown Source)
	at com.xlauch.mall.svc.facade.deve.ImagesSvc.selectImagesList(ImagesSvc.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
	at com.sun.proxy.$Proxy85.selectImagesList(Unknown Source)
```

**Comment by miemieYaho** [comment]
@param

**Comment by abciop** [comment]
@miemieYaho ，设置param，就得param.XXX了，为何不能跟2.X一样
