### ISSUE TITLE
mybatisplus代码生成器怎么将自定义模板放在src\test\java目录下

### ISSUE THREAD

**Issue by happydevelopers** [baomidou/mybatis-plus#1270]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
目前代码生成器只能讲自定义模板放在src\main\resources\templates目录下，这样子打war包会将自定义模板打进去。所以想放在src\test\java目录下，或者任意路径下。

### 重现步骤
设置controller模板再D盘根目录下，会报错找不到该文件。
templateConfig.setController("D:/controller.java");

### 报错信息
freemarker.template.TemplateNotFoundException: Template not found for name "D:/controller.java.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine, basePackagePath="/").
	at freemarker.template.Configuration.getTemplate(Configuration.java:2797)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2599)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.writer(FreemarkerTemplateEngine.java:50)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:131)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:102)

**Comment by qmdx** [comment]
https://mybatis.plus/guide/generator.html
参考 templatePath

**Comment by drinking** [comment]
> https://mybatis.plus/guide/generator.html 参考 templatePath

Same question, but link is broken
