### ISSUE TITLE
mybatis版本从2.1.9升级3.1.X，启动缺少LoggerFactory

### ISSUE THREAD

**Issue by stwen** [baomidou/mybatis-plus#1287]
### 当前使用版本(必须填写清楚，否则不予处理)

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.1</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
springboot项目，从2.1.9升级到3.1.1

### 重现步骤
启动springboot就报错

### 报错信息
报错缺少class
Caused by: java.lang.ClassNotFoundException: org.mybatis.logging.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 72 common frames omitted

**Comment by miemieYaho** [comment]
去看samples
