### ISSUE TITLE
mysql中有with rollup同时使用了mybatisplus的多租户解析器出现异常

### ISSUE THREAD

**Issue by skydrivers** [baomidou/mybatis-plus#1315]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.1.2

### 重现步骤
1 sql中有with rollup
select name, sum(a), sum(b) from (
	select 'tom' as name, 30 as a, 50 as b from dual union 
	select 'jerry' as name, 60 as a, 80 as b from dual
)t group by name with ROLLUP

2 使用mybatisplus的多租户sql解析器
https://mp.baomidou.com/guide/tenant.html

### 报错信息
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select name, sum(a), sum(b) from (
			select 'tom' as name, 30 as a, 50 as b from dual union 
			select 'jerry' as name, 60 as a, 80 as b from dual
		)t group by name with ROLLUP
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39) ~[mybatis-plus-core-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:74) ~[mybatis-plus-core-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler.sqlParser(AbstractSqlParserHandler.java:76) ~[mybatis-plus-extension-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:146) ~[mybatis-plus-extension-3.1.2.jar:3.1.2]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.1.jar:3.5.1]
	at com.sun.proxy.$Proxy164.prepare(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:94) ~[mybatis-plus-core-3.1.2.jar:3.1.2]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66) ~[mybatis-plus-core-3.1.2.jar:3.1.2]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.1.jar:3.5.1]
	... 118 common frames omitted
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:154) ~[jsqlparser-1.2.jar:na]
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60) ~[mybatis-plus-core-3.1.2.jar:3.1.2]
	... 129 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "with" "WITH"
    at line 4, column 20.

Was expecting one of:

    "&"
    ","
    "."
    "::"
    ";"
    "<<"
    ">>"
    "EXCEPT"
    "FOR"
    "HAVING"
    "INTERSECT"
    "MINUS"
    "ORDER"
    "UNION"
    "^"
    "|"
    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047) ~[jsqlparser-1.2.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900) ~[jsqlparser-1.2.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:293) ~[jsqlparser-1.2.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152) ~[jsqlparser-1.2.jar:na]
	... 130 common frames omitted

**Comment by qmdx** [comment]
jsqlparser 不支持该 sql 的解析 ， issue 移步至 https://github.com/JSQLParser/JSqlParser  或者注解过滤 xml 中传入租户条件
