### ISSUE TITLE
使用and嵌套报错

### ISSUE THREAD

**Issue by ozyl** [baomidou/mybatis-plus#1320]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0
kotlin

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用and嵌套报错

### 重现步骤
        val queryWrapper=KtQueryWrapper(AppShopGoodsCategory::class.java).and {
          it.eq(AppShopGoodsCategory::shopId,shopId).or().isNull(AppShopGoodsCategory::shopId)
        }

### 报错信息
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.baomidou.mybatisplus.extension.kotlin.KtQueryWrapper.<init>, parameter entity
	at com.baomidou.mybatisplus.extension.kotlin.KtQueryWrapper.<init>(KtQueryWrapper.kt)
	at com.baomidou.mybatisplus.extension.kotlin.KtQueryWrapper.instance(KtQueryWrapper.kt:111)
	at com.baomidou.mybatisplus.extension.kotlin.KtQueryWrapper.instance(KtQueryWrapper.kt:33)
	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.addNestedCondition(AbstractWrapper.java:323)
	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.and(AbstractWrapper.java:193)
	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.and(AbstractWrapper.java:42)
	at com.baomidou.mybatisplus.core.conditions.interfaces.Nested.and(Nested.java:34)

**Comment by miemieYaho** [comment]
kotlin 没人维护,欢迎你找到到底是哪的问题 pr
