### ISSUE TITLE
mybatis-plus 中collection 级联查询异常

### ISSUE THREAD

**Issue by zongyuanL** [baomidou/mybatis-plus#1353]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 重现步骤

EsMemberMapper的xml文件：
<mapper namespace="com.XXX.dbutil.um.mapper.EsMemberMapper">

    <resultMap id="baseResultMap" type="com.XXX.dbutil.um.entity.EsMember">
        <id property="id" column="id" jdbcType="INTEGER" />
        <result property="memberName" column="member_name" jdbcType="VARCHAR" />
        <result property="password" column="password" jdbcType="VARCHAR" />
        <result property="mobile" column="mobile" jdbcType="VARCHAR" />
        <result property="email" column="email" jdbcType="VARCHAR" />
        <result property="sex" column="sex" jdbcType="TINYINT" />
        <result property="birthday" column="birthday" jdbcType="TIMESTAMP" />
        <result property="createTime" column="createTime" jdbcType="TIMESTAMP" />
        <collection property="roles" fetchType="eager" column="id" select="com.XXX.dbutil.um.mapper.EsRoleMapper.findByMemberId"></collection>
    </resultMap>
</mapper>

EsRole的xml文件

    <resultMap id="baseResultMap" type="com.XXX.dbutil.um.entity.EsRole">
        <id property="id" column="id" jdbcType="INTEGER" />
        <result property="roleName" column="role_name" jdbcType="VARCHAR" />
        <result property="valid" column="valid" jdbcType="TINYINT" />
        <result property="createTime" column="createTime" jdbcType="TIMESTAMP" />
        <result property="updateTime" column="updateTime" jdbcType="TIMESTAMP" />
        <collection property="permissions" fetchType="eager" column="id" select="com.XXX.dbutil.um.mapper.EsPermissionMapper.findByRoleId"></collection>
    </resultMap>

    <select id="findByMemberId" resultMap="baseResultMap" parameterType="Integer">
      select r.* from es_member_role mr,es_role r where mr.role_id = r.id and mr.member_id = #{memberId,jdbcType=INTEGER}
    </select>

### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'roles' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'roles' in 'field list'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234) ~[spring-jdbc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73) ~[mybatis-spring-2.0.0.jar:2.0.0]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-2.0.0.jar:2.0.0]
	at com.sun.proxy.$Proxy148.selectList(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-2.0.0.jar:2.0.0]

**Comment by miemieYaho** [comment]
自行排查
