### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by liunewshine** [baomidou/mybatis-plus#1415]
### 当前使用版本
3.1.2

### 该问题是怎么引起的

`使用性能分析拦截器 PerformanceInterceptor`

### 重现步骤
使用jdk 11.0.2，执行查询sql

### 报错信息
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.invoker.GetFieldInvoker (file:/C:/Users/liunewshine/.m2/repository/org/mybatis/mybatis/3.5.1/mybatis-3.5.1.jar) to field java.lang.reflect.Proxy.h
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.invoker.GetFieldInvoker
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

以上是警告信息，当设置vm参数--illegal-access=debug后的报错信息：

```
2019-07-26 14:00:13.131 INFO  [http-nio-7001-exec-1] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-07-26 14:00:13.132 INFO  [http-nio-7001-exec-1] org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
2019-07-26 14:00:13.142 INFO  [http-nio-7001-exec-1] org.springframework.web.servlet.DispatcherServlet - Completed initialization in 10 ms
2019-07-26 14:00:13.236 DEBUG [http-nio-7001-exec-1] com.step.emp.basic.mapper.UserMapper.selectDtoById - ==>  Preparing: select u.*, r.id as role_id, r.name as role_name from basic_user u left join basic_user_role ur on u.id = ur.userId left join basic_role r on r.id = ur.roleId where u.id = ? 
WARNING: Illegal reflective access by org.apache.ibatis.reflection.invoker.GetFieldInvoker (file:/C:/Users/liunewshine/.m2/repository/org/mybatis/mybatis/3.5.1/mybatis-3.5.1.jar) to field java.lang.reflect.Proxy.h
	at org.apache.ibatis.reflection.invoker.GetFieldInvoker.invoke(GetFieldInvoker.java:38)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:164)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at org.apache.ibatis.reflection.MetaObject.metaObjectForProperty(MetaObject.java:145)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:115)
	at com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor.intercept(PerformanceInterceptor.java:101)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy138.query(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy94.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy110.selectDtoById(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy111.selectDtoById(Unknown Source)
	at com.step.emp.basic.service.UserService.selectDtoById(UserService.java:76)
	at com.step.emp.basic.service.UserService$$FastClassBySpringCGLIB$$3f071716.invoke(<generated>)
2019-07-26 14:00:13.277 DEBUG [http-nio-7001-exec-1] com.step.emp.basic.mapper.UserMapper.selectDtoById - ==> Parameters: 4(Integer)
2019-07-26 14:00:13.315 DEBUG [http-nio-7001-exec-1] com.step.emp.basic.mapper.UserMapper.selectDtoById - <==      Total: 2
 Time：40 ms - ID：com.step.emp.basic.mapper.UserMapper.selectDtoById
Execute SQL：SQLServerPreparedStatement:3
```

**Comment by miemieYaho** [comment]
PerformanceInterceptor 该插件不再维护
