### ISSUE TITLE
租户拦截器导致复杂sql报错

### ISSUE THREAD

**Issue by chenlingyx** [baomidou/mybatis-plus#1449]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
开启租户解析器，执行复杂sql报错，如果没有租户解析器，可以正常运行

### 重现步骤
开启租户解析器，执行sql：
select count(0) from (SELECT * FROM
        ( SELECT
            tb.id AS id,
            tb.code AS code,
            tb.app_code AS app_code,
            tb.main_resource_type AS main_resource_type,
            tb.main_field AS main_field,
            tb.latest AS latest,
            tb.name AS name,
            tb.remark AS remark,
            tb.type AS type,
            tb.status AS status,
            tb.behavior_action_api AS behavior_action_api,
            tb.invoke_type AS invoke_type,
            tb.edition AS edition,
            tb.behavior_param AS behavior_param,
            tb.tenant_id AS tenant_id,
            tb.is_deleted AS deleted,
            tb.version AS version,
            tb.created_by AS created_by,
            (SELECT MIN(b.created_time) FROM task_behavior b WHERE b.code = tb.code) AS created_time,
            tb.updated_by AS updated_by,
            tb.updated_time AS updated_time,
            (SELECT COUNT(tn.id) > 0 FROM task_node tn WHERE tn.is_deleted = 0 AND tn.behavior_id =tb.id) AS is_used
            FROM task_behavior tb
            WHERE tb.latest = 1 AND tb.is_deleted = 0
             and tb.app_code = ?
            ) temp
		WHERE 1=1
		ORDER BY temp.id DESC) tmp_count

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select count(0) from (SELECT * FROM
        ( SELECT
            tb.id AS id,
            tb.code AS code,
            tb.app_code AS app_code,
            tb.main_resource_type AS main_resource_type,
            tb.main_field AS main_field,
            tb.latest AS latest,
            tb.name AS name,
            tb.remark AS remark,
            tb.type AS type,
            tb.status AS status,
            tb.behavior_action_api AS behavior_action_api,
            tb.invoke_type AS invoke_type,
            tb.edition AS edition,
            tb.behavior_param AS behavior_param,
            tb.tenant_id AS tenant_id,
            tb.is_deleted AS deleted,
            tb.version AS version,
            tb.created_by AS created_by,
            (SELECT MIN(b.created_time) FROM task_behavior b WHERE b.code = tb.code) AS created_time,
            tb.updated_by AS updated_by,
            tb.updated_time AS updated_time,
            (SELECT COUNT(tn.id) > 0 FROM task_node tn WHERE tn.is_deleted = 0 AND tn.behavior_id =tb.id) AS is_used
            FROM task_behavior tb
            WHERE tb.latest = 1 AND tb.is_deleted = 0
               and tb.app_code = ?
         ) temp
        WHERE 1=1
          ORDER BY temp.id DESC) tmp_count
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy134.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy140.findAll(Unknown Source)
	at com.deepexi.task.dao.impl.TaskBehaviorDAOImpl.listTaskBehaviors(TaskBehaviorDAOImpl.java:35)
	at com.deepexi.task.dao.impl.TaskBehaviorDAOImpl$$FastClassBySpringCGLIB$$1a794c21.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.deepexi.task.dao.impl.TaskBehaviorDAOImpl$$EnhancerBySpringCGLIB$$70eeee8.listTaskBehaviors(<generated>)
	at com.deepexi.task.service.impl.TaskBehaviorServiceImpl.listTaskBehaviors(TaskBehaviorServiceImpl.java:52)
	at com.deepexi.task.service.impl.TaskBehaviorServiceImpl$$FastClassBySpringCGLIB$$e5253201.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.deepexi.task.service.impl.TaskBehaviorServiceImpl$$EnhancerBySpringCGLIB$$33414c88.listTaskBehaviors(<generated>)
	at com.deepexi.task.controller.TaskBehaviorController.findTaskBehaviorPage(TaskBehaviorController.java:36)
	at com.deepexi.task.controller.TaskBehaviorController$$FastClassBySpringCGLIB$$d781bf4d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.deepexi.task.aop.LogAspect.aroundApi(LogAspect.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.deepexi.task.controller.TaskBehaviorController$$EnhancerBySpringCGLIB$$d346dccb.findTaskBehaviorPage(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.deepexi.task.filter.TaskFilter$1.doFilter(TaskFilter.java:71)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: select count(0) from (SELECT * FROM
        ( SELECT
            tb.id AS id,
            tb.code AS code,
            tb.app_code AS app_code,
            tb.main_resource_type AS main_resource_type,
            tb.main_field AS main_field,
            tb.latest AS latest,
            tb.name AS name,
            tb.remark AS remark,
            tb.type AS type,
            tb.status AS status,
            tb.behavior_action_api AS behavior_action_api,
            tb.invoke_type AS invoke_type,
            tb.edition AS edition,
            tb.behavior_param AS behavior_param,
            tb.tenant_id AS tenant_id,
            tb.is_deleted AS deleted,
            tb.version AS version,
            tb.created_by AS created_by,
            (SELECT MIN(b.created_time) FROM task_behavior b WHERE b.code = tb.code) AS created_time,
            tb.updated_by AS updated_by,
            tb.updated_time AS updated_time,
            (SELECT COUNT(tn.id) > 0 FROM task_node tn WHERE tn.is_deleted = 0 AND tn.behavior_id =tb.id) AS is_used
            FROM task_behavior tb
            WHERE tb.latest = 1 AND tb.is_deleted = 0
           nd tb.app_code = ?
        ) temp
        WHERE 1=1
         ORDER BY temp.id DESC) tmp_count

**Comment by qmdx** [comment]
太复杂无法自动解决  sqlParser 注解 跳过该 mapper 方法，自己加上租户条件处理下
