### ISSUE TITLE
List<Long> 和List<String> 两个handler 在处理时是随机使用typehandler

### ISSUE THREAD

**Issue by ToryZhou** [baomidou/mybatis-plus#1451]
### 当前使用版本(必须填写清楚，否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.1.2</version>
        </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
List Long> 和List String 两个handler 在处理时是随机使用typehandler

### 重现步骤
public class ListLongTypeHandler extends BaseTypeHandler<List<Long>> {}
public class ListStringTypeHandler extends BaseTypeHandler<List<String>> {}
创建两个TypeHandler, 在查询时有时用的第一个， 有时用的第二个。

### 报错信息
```
Caused by: java.lang.IllegalArgumentException: Can not deserialize value of type java.lang.Long from String "client_credential": not a valid Long value
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3605)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3546)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3534)
	at com.patsnap.uaa.account.entity.rds.type.ListLongTypeHandler.getList(ListLongTypeHandler.java:59)
	at com.patsnap.uaa.account.entity.rds.type.ListLongTypeHandler.getNullableResult(ListLongTypeHandler.java:37)
	at com.patsnap.uaa.account.entity.rds.type.ListLongTypeHandler.getNullableResult(ListLongTypeHandler.java:23)
```

**Comment by miemieYaho** [comment]
mybatis只认你的泛型List

**Comment by ToryZhou** [comment]
@miemieYaho 
这个问题有没有什么办法解决呢？

如果用泛型，从数据库出来的List String是知道的， 可是List Integer还是List Long是分不清的

**Comment by miemieYaho** [comment]
写resultmap
