### ISSUE TITLE
乐观锁使用异常

### ISSUE THREAD

**Issue by zfj0952** [baomidou/mybatis-plus#1467]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
表是树形结构的，插入或修改entity时修改其对应的parent entity，导致抛出异常

### Cause: java.lang.reflect.UndeclaredThrowableException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 156 common frames omitted
Caused by: java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy244.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 161 common frames omitted
Caused by: java.lang.IllegalAccessException: Class **com.baomidou.mybatisplus.extension.plugins.OptimisticLockerInterceptor can not access a member of class BaseEntity with modifiers "protected"**
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.get(Field.java:390)
	at com.baomidou.mybatisplus.extension.plugins.OptimisticLockerInterceptor.intercept(OptimisticLockerInterceptor.java:115)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	... 163 common frames omitted

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by zfj0952** [comment]
已验证是其他插件影响的
