### ISSUE TITLE
mysql 非空字段有默认值，字段未赋值，插入时提示不能为空

### ISSUE THREAD

**Issue by xiaopan0513** [baomidou/mybatis-plus#1468]
### 当前使用版本(必须填写清楚，否则不予处理)

compile 'com.baomidou:mybatis-plus-boot-starter:3.1.2'

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

![image](https://user-images.githubusercontent.com/8357717/62605078-f2380280-b92b-11e9-8a95-a3af50e966fe.png)

![image](https://user-images.githubusercontent.com/8357717/62605028-d6346100-b92b-11e9-8b43-099c51661427.png)

### 重现步骤

创建表

CREATE TABLE `t_brand` (
  `FuiBrandId` bigint(20) unsigned NOT NULL COMMENT '品牌ID',
  `FstrBrandName` varchar(255) NOT NULL DEFAULT '' COMMENT '品牌全称',
  `FstrShortName` varchar(50) NOT NULL COMMENT '品牌简称',
  `FstrLetters` varchar(20) NOT NULL DEFAULT '' COMMENT '品牌首字母',
  `FstrImgUrl` varchar(255) NOT NULL COMMENT '品牌LOGO',
  `FstrWebUrl` varchar(255) NOT NULL COMMENT '品牌官网',
  `FstrIntroduction` varchar(4000) NOT NULL COMMENT '品牌介绍',
  `FuiGoodsNum` int(11) NOT NULL DEFAULT '0' COMMENT '商品数量',
  `FstrOperator` varchar(32) NOT NULL COMMENT '最后操作人',
  `FuiDelStatus` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态(0: 生效中, 1: 已删除)',
  `FstrCreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `FstrUpdateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`FuiBrandId`),
  KEY `FstrName` (`FstrBrandName`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='品牌信息表';

其中FstrShortName等字段为非空字段，单字段有设置默认值，使用insert 语句只要不显示插入NULL值，是可以正常入库的，如：

INSERT INTO t_brand  ( FuiBrandId,  FstrBrandName,    FstrIntroduction,  FstrOperator )  VALUES  ( 111,  'test',    '',  'a' );

当通过MyBatisPlus调用insert方法插入提示为空

Error updating database.  Cause: java.sql.SQLException: Field 'FstrShortName' doesn't have a default value

### 报错信息

org.springframework.dao.DataIntegrityViolationException: 
### Cause: java.sql.SQLException: Field 'FstrShortName' doesn't have a default value
; Field 'FstrShortName' doesn't have a default value; nested exception is java.sql.SQLException: Field 'FstrShortName' doesn't have a default value
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:246)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy95.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy106.insert(Unknown Source)

**Comment by miemieYaho** [comment]
自行排查
