### ISSUE TITLE
返回对象使用同名的内部类

### ISSUE THREAD

**Issue by xzl172259412** [baomidou/mybatis-plus#1485]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
多个不同的返回类型，每个里面有一个同名的内部类: DemoDetails，
使用
`<
collection column="version" property="rateTimeList" ofType="com.test.dto$DemoDetails" javaType="java.util.List">`
 在mapper.xml中定义

### 报错信息
Caused by: org.apache.ibatis.type.TypeException: The alias 'DemoDetails' is already mapped to the value 'com.test.dto$DemoDetails'.
	at org.apache.ibatis.type.TypeAliasRegistry.registerAlias(TypeAliasRegistry.java:157)
	at org.apache.ibatis.type.TypeAliasRegistry.registerAlias(TypeAliasRegistry.java:147)
	at java.lang.Iterable.forEach(Iterable.java:75)

**Comment by miemieYaho** [comment]
返回值封装是mybatis的事,自行排查
