### ISSUE TITLE
Mybatis X插件问题

### ISSUE THREAD

**Issue by Kylelkh** [baomidou/mybatis-plus#1489]
### 当前使用版本(必须填写清楚，否则不予处理)

IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019

Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Memory: 1972M
Cores: 6
Non-Bundled Plugins: cn.wuzhizhan.plugin.mybatis, com.baomidou.plugin.idea.mybatisx

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
升级到最新的稳定版本IDEA，重启后即可发现该问题
![image](https://user-images.githubusercontent.com/10898224/62846733-ecb03300-bd04-11e9-8920-635152e7fe28.png)

### 重现步骤
安装最新的IDEA 并且重启

#### 简略信息：

MybatisMapperMethodInspection 简称不唯一

#### 详细信息如下：

com.intellij.diagnostic.PluginException: Short name 'MybatisMapperMethodInspection' is not unique
class 'com.baomidou.plugin.idea.mybatisx.inspection.MapperMethodInspection' in PluginDescriptor(name=MyBatisX, classpath=C:\Users\***\.IntelliJIdea2019.2\config\plugins\MybatisX-idea.0.1.0.jar)
and
class'com.wuzhizhan.mybatis.inspection.MapperMethodInspection' in PluginDescriptor(name=Free MyBatis plugin, classpath=C:\Users\***\.IntelliJIdea2019.2\config\plugins\free-idea-mybatis)
conflict [Plugin: com.baomidou.plugin.idea.mybatisx]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:64)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.lambda$new$2(InspectionToolRegistrar.java:37)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:104)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.Preloader.lambda$componentsInitialized$2(Preloader.java:71)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by miemieYaho** [comment]
我没有你这问题呢

**Comment by Kylelkh** [comment]
Free Mybatis plugin与Mybatis X这两个插件一起用的时候才会有这个问题的，使用其中一个就不会报错。

**Comment by Kylelkh** [comment]
> 我没有你这问题呢

Free Mybatis plugin与Mybatis X这两个插件一起用的时候才会有这个问题的，使用其中一个就不会报错。

**Comment by miemieYaho** [comment]
那就只用其中之一
