### ISSUE TITLE
2.1.1 MpGenerator 报错

### ISSUE THREAD

**Issue by lg-Cat73** [baomidou/mybatis-plus#150]
2.1.1 报下面的错误，一模一样的代码，一字不改，换回 2.1.0 可以正常生成
```
DEBUG [main] org.apache.ibatis.logging.LogFactory 2017-09-13 15:10:39 
 ---> Logging initialized using 'class org.apache.ibatis.logging.slf4j.Slf4jImpl' adapter.
DEBUG [main] com.baomidou.mybatisplus.generator.AutoGenerator 2017-09-13 15:10:39 
 ---> ==========================准备生成文件...==========================
Wed Sep 13 15:10:40 CST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
SQL Exception：Table 'xxx.%s' doesn't exist
DEBUG [main] com.baomidou.mybatisplus.generator.AutoGenerator 2017-09-13 15:10:41 
 ---> 创建目录： [src/main/java/xx/xxxx/xxx/coin/mapper/xml]

java.lang.NullPointerException
	at com.baomidou.mybatisplus.generator.config.po.TableInfo.isLogicDelete(TableInfo.java:212)
	at com.baomidou.mybatisplus.generator.AutoGenerator.analyzeData(AutoGenerator.java:171)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:97)
	at xx.xxxx.xxx.MpGenerator.generator(MpGenerator.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


```

**Comment by lg-Cat73** [comment]
生成用的代码：

```java
package xx.xxxx.xxx;

import com.baomidou.mybatisplus.generator.AutoGenerator;
import com.baomidou.mybatisplus.generator.config.DataSourceConfig;
import com.baomidou.mybatisplus.generator.config.GlobalConfig;
import com.baomidou.mybatisplus.generator.config.PackageConfig;
import com.baomidou.mybatisplus.generator.config.StrategyConfig;
import com.baomidou.mybatisplus.generator.config.rules.DbType;
import com.baomidou.mybatisplus.generator.config.rules.NamingStrategy;
import org.junit.Test;

public class MpGenerator {
    @Test
    public void generator() {
        AutoGenerator mpg = new AutoGenerator();

        // 全局配置
        GlobalConfig gc = new GlobalConfig();
        gc.setOutputDir("src/main/java");
        gc.setFileOverride(false);
        gc.setActiveRecord(true);
        gc.setEnableCache(false);// XML 二级缓存
        gc.setBaseResultMap(true);// XML ResultMap
        gc.setBaseColumnList(true);// XML columList
        gc.setAuthor("Cat73");
        mpg.setGlobalConfig(gc);

        // 数据源配置
        DataSourceConfig dsc = new DataSourceConfig();
        dsc.setDbType(DbType.MYSQL);
        dsc.setDriverName("com.mysql.jdbc.Driver");
        dsc.setUsername("developer");
        dsc.setPassword("iamadeveloper");
        dsc.setUrl("jdbc:mysql://********:3306/xxx?characterEncoding=utf8");
        mpg.setDataSource(dsc);

        // 策略配置
        StrategyConfig strategy = new StrategyConfig();
        strategy.setNaming(NamingStrategy.underline_to_camel);// 表名生成策略
        strategy.setInclude(new String[] { "user_xxx_recharge_record" }); // 需要生成的表
        strategy.setEntityBuilderModel(true); // setter 方法返回 this
        mpg.setStrategy(strategy);

        // 包配置
        PackageConfig pc = new PackageConfig();
        pc.setParent("xx.xxxx.xxx");
        pc.setModuleName("coin");
        mpg.setPackageInfo(pc);

        // 执行生成
        mpg.execute();
    }
}
```

**Comment by qmdx** [comment]
感谢反馈已经修复 https://gitee.com/baomidou/mybatis-plus/issues/IF2N5
