### ISSUE TITLE
insertBatch批量插入、批量更新出错

### ISSUE THREAD

**Issue by asd8510678** [baomidou/mybatis-plus#152]
ervice.impl.ServiceImpl.sqlSessionBatch(ServiceImpl.java:85) ~[mybatis-plus-2.1.0.jar:na]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at cc.csit.core.service.impl.CrudServiceImpl.sqlSessionBatch(CrudServiceImpl.java) ~[classes/:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy35.saveRes(Unknown Source)
	at cc.csit.core.controller.sys.RoleResController.saveRes(RoleResController.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
	at cc.csit.core.service.impl.RoleResServiceImpl.sqlSessionBatch(RoleResServiceImpl.java) ~[classes/:na]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:125) ~[mybatis-plus-2.1.0.jar:na]
	... 64 common frames omitted
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	... 35 more
Caused by: java.lang.NullPointerException
	at com.baomidou.mybatisplus.toolkit.GlobalConfigUtils.currentSessionFactory(GlobalConfigUtils.java:60)
	at com.baomidou.mybatisplus.mapper.SqlHelper.sqlSessionBatch(SqlHelper.java:70)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.sqlSessionBatch(ServiceImpl.java:85)
	at cc.csit.core.service.impl.CrudServiceImpl.sqlSessionBatch(CrudServiceImpl.java)
	at cc.csit.core.service.impl.RoleResServiceImpl.sqlSessionBatch(RoleResServiceImpl.java)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:125)
	... 64 more

下段跟踪是GlobalConfigUtils 类 currentSessionFactory方法里的
String configMark = TableInfoHelper.getTableInfo(clazz).getConfigMark();
clazz 显示的是mapper  导致getTableInfo 为空，请作者检查一下
![qq 20170914111758](https://user-images.githubusercontent.com/17697008/30410594-ab8d6460-993e-11e7-8007-e5e7f795fc5c.png)

**Comment by asd8510678** [comment]
clazz 应该要是实体类才正常的

**Comment by qmdx** [comment]
clazz 必须是表映射实体对应的类

**Comment by xupengggggg** [comment]
即使是实体也不行  ，错误和题目一样
