### ISSUE TITLE
Generator的ConfigBuilder386行tableInfo.getFields() NPE

### ISSUE THREAD

**Issue by leolztang** [baomidou/mybatis-plus#1547]
### 当前使用版本 
3.2.0

### 该问题是怎么引起的
表的所有字段都在BaseEntity中时，TableInfo将不会初始化List<TableField> fields， 从而导致tableInfo.getFields() NPE
` public TableInfo setFields(List<TableField> fields) {
        if (CollectionUtils.isNotEmpty(fields)) {
            //do init
        }
        return this;
    }`

### 重现步骤
StrategyConfig.setSuperEntityColumns包含了表的所有字段

### 报错信息
`Caused by: java.lang.NullPointerException: null
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.checkImportPackages(ConfigBuilder.java:386) ~[mybatis-plus-generator-3.2.0.jar:3.2.0]
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.processTable(ConfigBuilder.java:362) ~[mybatis-plus-generator-3.2.0.jar:3.2.0]
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:520) ~[mybatis-plus-generator-3.2.0.jar:3.2.0]
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:281) ~[mybatis-plus-generator-3.2.0.jar:3.2.0]
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:142) ~[mybatis-plus-generator-3.2.0.jar:3.2.0]
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:92) ~[mybatis-plus-generator-3.2.0.jar:3.2.0]
`

**Comment by fanlushuai** [comment]
车开的太猛,晕车正常

**Comment by qmdx** [comment]
fixed https://github.com/baomidou/mybatis-plus/commit/0465d89f04e8e32bff8d260222312a6543747689
