### ISSUE TITLE
新版本使用and报错

### ISSUE THREAD

**Issue by xlb** [baomidou/mybatis-plus#1572]
### 版本为3.2.0
这一版本更新了逻辑删除时将and包围的方法（不知道是不是这个原因，个人猜测）；
具体使用如下

`   	QueryWrapper<SysLog> queryWrapper=new  QueryWrapper();
    	queryWrapper.lambda()
       	.and(obj -> obj.like(SysLog::getCreateUser, query.getCreateBy())
       	    	.or().like(SysLog::getCreateUserName, query.getCreateBy())
       	    	.apply("1 = 1")
       	    	)
    	.meq(SysLog::getId, query.getId())
    	.meq(SysLog::getType, query.getType())
    	.meq(SysLog::getStatus, query.getStatus())
    	.mlike(SysLog::getModuleName, query.getModuleName())`

_控制台错误_

`Caused by: java.lang.AbstractMethodError: Method com/baomidou/mybatisplus/core/conditions/query/LambdaQueryWrapper.and(ZLjava/util/function/Function;)Ljava/lang/Object; is abstract
	at com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper.and(LambdaQueryWrapper.java)
	at com.baomidou.mybatisplus.core.conditions.interfaces.Nested.and(Nested.java:35)
	at com.soptop.eam.user.service.impl.SysLogServiceImpl.pageByQuery(SysLogServiceImpl.java:23)
	at com.soptop.eam.user.service.impl.SysLogServiceImpl$$FastClassBySpringCGLIB$$5380086f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.soptop.eam.user.service.impl.SysLogServiceImpl$$EnhancerBySpringCGLIB$$176f413.pageByQuery(<generated>)
	at com.soptop.eam.user.controller.SysLogController.loginPageByQuery(SysLogController.java:40)
	at sun.reflect.GeneratedMethodAccessor459.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	... 49 common frames omitted`

**Comment by xlb** [comment]
meq是我自己封装了一下，做了判空，还是eq对象

**Comment by xlb** [comment]
替换成nested 跟or 也是同样的

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by xlb** [comment]
问题找到了，是因为我之前本地重写了com.baomidou.mybatisplus.core.conditions.interfaces包下的Nested类，新版本对这个类进行了更新，没仔细对比。。
