### ISSUE TITLE
SpringBoot 打war包，部署外部tomcat出错

### ISSUE THREAD

**Issue by dimplememory** [baomidou/mybatis-plus#1608]
### 当前使用版本(必须填写清楚，否则不予处理)
version 3.1.0/3.2.0一样结果

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

SpringBoot 打war包并部署到外部tomcat时引起，如果直接打jar包内置tomcat，正常运行

### 重现步骤
1.通过springboot自带war包打包工具进行打包（过程无出现错误）
2.下载最新tomcat（9.0.24）windows版，不做任何额外的配置。
3.将打好的war包直接放入tomcat的webapps文件夹中，跑起来就出现错误。

### 报错信息
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-09-11 16:47:12.542 ERROR 14644 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap:

    Reason: Failed to extract parameter names for org.apache.ibatis.mapping.ResultMap(org.apache.ibatis.mapping.ResultMap$1)

Action:

Update your application's configuration

11-Sep-2019 16:47:12.546 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [C:\Users\PhoenixTse\Desktop\apache-tomcat-9.0.24\webapps\mockup.war]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/mockup]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                ... 37 more
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mockupController': Unsatisfied dependency expressed through field 'mockupDataMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mockupDataMapper' defined in file [C:\Users\PhoenixTse\Desktop\apache-tomcat-9.0.24\webapps\mockup\WEB-INF\classes\tk\bdpr\mockup\repo\mapper\MockupDataMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'mybatis-plus-com.baomidou.mybatisplus.autoconfigure.MybatisPlusProperties': Could not bind properties to 'MybatisPlusProperties' : prefix=mybatis-plus, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
                at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:638)
                at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
                at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:396)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1430)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:877)
                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
                at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:746)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:396)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:152)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:132)
                at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:92)
                at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                ... 38 more
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mockupDataMapper' defined in file [C:\Users\PhoenixTse\Desktop\apache-tomcat-9.0.24\webapps\mockup\WEB-INF\classes\tk\bdpr\mockup\repo\mapper\MockupDataMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'mybatis-plus-com.baomidou.mybatisplus.autoconfigure.MybatisPlusProperties': Could not bind properties to 'MybatisPlusProperties' : prefix=mybatis-plus, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1534)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1414)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1283)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1203)
                at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:635)
                ... 60 more
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'mybatis-plus-com.baomidou.mybatisplus.autoconfigure.MybatisPlusProperties': Could not bind properties to 'MybatisPlusProperties' : prefix=mybatis-plus, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
                at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:779)
                at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1359)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1205)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1339)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1178)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1283)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1203)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1519)
                ... 71 more
        Caused by: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'mybatis-plus-com.baomidou.mybatisplus.autoconfigure.MybatisPlusProperties': Could not bind properties to 'MybatisPlusProperties' : prefix=mybatis-plus, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
                at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:119)
                at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:94)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
                at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1283)
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1203)
                at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:866)
                at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:770)
                ... 93 more
        Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap
                at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:336)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:296)
                at org.springframework.boot.context.properties.bind.Binder.lambda$null$1(Binder.java:384)
                at org.springframework.boot.context.properties.bind.Binder$Context.withSource(Binder.java:518)
                at org.springframework.boot.context.properties.bind.Binder$Context.access$1000(Binder.java:485)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:385)
                at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:106)
                at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:86)
                at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:71)
                at org.springframework.boot.context.properties.bind.CollectionBinder.bindAggregate(CollectionBinder.java:49)
                at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:387)
                at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:542)
                at org.springframework.boot.context.properties.bind.Binder$Context.access$200(Binder.java:485)
                at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:387)
                at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:348)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:292)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:420)
                at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:88)
                at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:77)
                at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:424)
                at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:542)
                at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:528)
                at org.springframework.boot.context.properties.bind.Binder$Context.access$500(Binder.java:485)
                at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:422)
                at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:363)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:292)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:420)
                at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:88)
                at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:77)
                at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:424)
                at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:542)
                at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:528)
                at org.springframework.boot.context.properties.bind.Binder$Context.access$500(Binder.java:485)
                at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:422)
                at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:363)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:292)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:281)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:211)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
                at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:91)
                at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:116)
                ... 107 more
        Caused by: java.lang.IllegalStateException: Failed to extract parameter names for org.apache.ibatis.mapping.ResultMap(org.apache.ibatis.mapping.ResultMap$1)
                at org.springframework.util.Assert.state(Assert.java:94)
                at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.parseConstructorParameters(ValueObjectBinder.java:176)
                at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.<init>(ValueObjectBinder.java:171)
                at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.get(ValueObjectBinder.java:212)
                at org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.get(ValueObjectBinder.java:205)
                at org.springframework.boot.context.properties.bind.ValueObjectBinder$ValueObject.get(ValueObjectBinder.java:111)
                at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:50)
                at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:424)
                at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:542)
                at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:528)
                at org.springframework.boot.context.properties.bind.Binder$Context.access$500(Binder.java:485)
                at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:422)
                at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:363)
                at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:292)
                ... 149 more

**Comment by miemieYaho** [comment]
自行排查

**Comment by hycx** [comment]
Description:

Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap:

**Comment by ubaycreative** [comment]
+1

**Comment by qinkangdeid** [comment]
我也一样 

```bash

***************************
APPLICATION FAILED TO START
***************************
Description:
Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap:
    Reason: Failed to extract parameter names for org.apache.ibatis.mapping.ResultMap(org.apache.ibatis.mapping.ResultMap$1)
Action:
Update your application's configuration


```

**Comment by niuniu201010** [comment]
+1 一样出现了这个问题，springboot 项目 版本2.2.0.RELEASE，本地windows7 idea启动没问题，centos7.6 tomcat 8 ,java8 部署war包无法启动，报错：org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap

**Comment by niuniu201010** [comment]
> > 本地windows7 idea启动没问题，centos7.6 tomcat 8 ,java8 部署war包无法启动，报错：
> 
> 我也是springboot 2.2.0.RELEASE 启动就报这个错 现在回退到2.1.9.RELEASE了 就没问题了

ok ,我来试一下，看看行不

**Comment by niuniu201010** [comment]
> > 本地windows7 idea启动没问题，centos7.6 tomcat 8 ,java8 部署war包无法启动，报错：
> 
> 我也是springboot 2.2.0.RELEASE 启动就报这个错 现在回退到2.1.9.RELEASE了 就没问题了

可以了，竟然真的是springboot版本的问题，换成2.1.9就可以了，谢谢了，不过浪费了点时间在打包上，2.1.9版本的springboot 打war时，不能再原有的启动上修改，需要另外建一个类，因为如果没有启动类的main主方法，打包回失败；附上另外的一个类代码：
`
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

`
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ServletInitializer extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(SpringBootTestWebDemoApplication.class);
    }
}
`

**Comment by ifu25** [comment]
> > 本地windows7 idea启动没问题，centos7.6 tomcat 8 ,java8 部署war包无法启动，报错：
> 
> 我也是springboot 2.2.0.RELEASE 启动就报这个错 现在回退到2.1.9.RELEASE了 就没问题了

厉害，还真是 2.2.0.RELEASE 的问题，我也换回了 2.1.9 没有问题了。

**Comment by ifu25** [comment]
> > > 本地windows7 idea启动没问题，centos7.6 tomcat 8 ,java8 部署war包无法启动，报错：
> > 
> > 
> > 我也是springboot 2.2.0.RELEASE 启动就报这个错 现在回退到2.1.9.RELEASE了 就没问题了
> 
> 可以了，竟然真的是springboot版本的问题，换成2.1.9就可以了，谢谢了，不过浪费了点时间在打包上，2.1.9版本的springboot 打war时，不能再原有的启动上修改，需要另外建一个类，因为如果没有启动类的main主方法，打包回失败；附上另外的一个类代码：
> `
> import org.springframework.boot.builder.SpringApplicationBuilder;
> import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
> 
> public class ServletInitializer extends SpringBootServletInitializer {
> @override
> protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
> return application.sources(SpringBootTestWebDemoApplication.class);
> }
> }
> `

我换回 2.1.9 问题也没有了，但是你说的 2.1.9 不能在启动类上修改我这里怎么没问题呢，直接用启动类集成了 SpringBootServletInitializer 没有问题。

**Comment by ifu25** [comment]
刚发布的 2.2.1 已经没有这个问题了。
