### ISSUE TITLE
@TableId IdType是NONE(1)，可是调试却发现不是？

### ISSUE THREAD

**Issue by jhd147350** [baomidou/mybatis-plus#1631]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

实体类
``` java
@Data
@Table("TechnicsChemicalSupplier")
@TableName("TechnicsChemicalSupplier")
public class ChemicalSupplier {
    @PK
    @TableId
    private Integer id;
    @NotEmpty(message = "名称不能为空")
    private String name;
    private String shortName;
    private String contactPerson;
    private String contactNum;//联系电话
    private String bank; //开户行
    private String bankAccount; //账户
    private String address;
    private String note;
    private String recordUserName;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Timestamp addDatetime;
    private Boolean enable;
}
```
Dao层代码
```java
@Repository
public interface ChemicalSupplierDao extends BaseMapperJ<ChemicalSupplier>, BaseMapper<ChemicalSupplier> {
}
```
Service层代码
``` java
public boolean addChemicalSupplier(ChemicalSupplier supplier) {
        SecurityUser user = authenticationFacade.getSecurityUser();
        supplier.setRecordUserName(user.getNickname());
        //chemicalSupplierDao.insert(supplier);
        return chemicalSupplierDao.insertJ(supplier);
        //return true;
    }
```
这个insertJ 是我自身 自动生成sql的工具，我都没调用mybatis plus框架的插入方法（我后来用了mybatis plus的insert 也是一样报错），我只用mybatis plus做分页和查询，插入是用我自己实现的sql工具；可是为什么mybatis plus 给我id生成了一个值？我id是数据库自增的

### 重现步骤
因为我这实体类数据记录不会很多，我采用了Integer类型，我其他都是Long 类型就没错，而且我将这个表的ID 改为Integer 之后 也就没事了？我想知道这是bug吗？

### 报错信息
```
console: 2019-09-21 11:35:48.992 ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - Servlet.service() 
for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; 
nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is 
org.apache.ibatis.reflection.ReflectionException: Could not set property 'id' of 'class 
com.gooinfo.erp.b2_technics.model.ChemicalSupplier' with value '1175252261648732161' Cause: 
java.lang.IllegalArgumentException: argument type mismatch] with root cause
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:180)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59)
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.populateKeys(MybatisDefaultParameterHandler.java:178)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.processBatch(MybatisDefaultParameterHandler.java:120)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.<init>(MybatisDefaultParameterHandler.java:51)
	at com.baomidou.mybatisplus.core.MybatisXMLLanguageDriver.createParameterHandler(MybatisXMLLanguageDriver.java:34)
	at com.baomidou.mybatisplus.core.MybatisXMLLanguageDriver.createParameterHandler(MybatisXMLLanguageDriver.java:28)
	at org.apache.ibatis.session.Configuration.newParameterHandler(Configuration.java:550)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:69)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:41)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46)
	at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:563)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy85.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy103.insertJ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy104.insertJ(Unknown Source)
	at com.gooinfo.erp.b2_technics.service.ChemicalService.addChemicalSupplier(ChemicalService.java:88)
	at com.gooinfo.erp.b2_technics.controller.ChemicalAPI.addChemicalSupplier(ChemicalAPI.java:115)

```

**Comment by jhd147350** [comment]
我调试到 mybatis plus的代码，发现mybatis plus 判断了我的idType是ID_WORKER类型，竟然给我赋值了，但是我生成的sql语句 set里面就没id啊；
``` java
    protected static Object populateKeys(MetaObjectHandler metaObjectHandler, TableInfo tableInfo,
                                         MappedStatement ms, Object parameterObject, boolean isInsert) {
        if (null == tableInfo) {
            /* 不处理 */
            return parameterObject;
        }
        /* 自定义元对象填充控制器 */
        MetaObject metaObject = ms.getConfiguration().newMetaObject(parameterObject);
        // 填充主键
        if (isInsert && !StringUtils.isEmpty(tableInfo.getKeyProperty())
            && null != tableInfo.getIdType() && tableInfo.getIdType().getKey() >= 3) {
            Object idValue = metaObject.getValue(tableInfo.getKeyProperty());
            /* 自定义 ID */
            if (StringUtils.checkValNull(idValue)) {
                if (tableInfo.getIdType() == IdType.ID_WORKER) {
                    metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.getId());
                } else if (tableInfo.getIdType() == IdType.ID_WORKER_STR) {
                    metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.getIdStr());
                } else if (tableInfo.getIdType() == IdType.UUID) {
                    metaObject.setValue(tableInfo.getKeyProperty(), IdWorker.get32UUID());
                }
            }
        }
        if (metaObjectHandler != null) {
            if (isInsert && metaObjectHandler.openInsertFill()) {
                // 插入填充
                metaObjectHandler.insertFill(metaObject);
            } else if (!isInsert) {
                // 更新填充
                metaObjectHandler.updateFill(metaObject);
            }
        }
        return metaObject.getOriginalObject();
    }

```

 if (tableInfo.getIdType() == IdType.ID_WORKER) 判断结果为true，可是@TableId注解默认的idType 不是NONE吗？

**Comment by miemieYaho** [comment]
全局配置 idtype

**Comment by jhd147350** [comment]
> 全局配置 idtype

可是我没用mp 的insert ，我执行我自己写的sql也会有这个问题，而且当id换成Long之后就不存在了，就是不懂为什么，问题我解决了，但是不明白为啥出现这个情况

**Comment by jhd147350** [comment]
@miemieYaho 我搞明白了，TableId type虽然默认是NONE，但是在初始化TableInfo的时候，这个NONE会转成ID_WORKER，代码我找到了
``` java
    private static boolean initTableIdWithAnnotation(GlobalConfig.DbConfig dbConfig, TableInfo tableInfo,
                                                     Field field, Class<?> clazz) {
        TableId tableId = field.getAnnotation(TableId.class);
        boolean underCamel = tableInfo.isUnderCamel();
        if (tableId != null) {
            if (StringUtils.isEmpty(tableInfo.getKeyColumn())) {
                /* 主键策略（ 注解 > 全局 ） */
                // 设置 Sequence 其他策略无效
                if (IdType.NONE == tableId.type()) {
                    tableInfo.setIdType(dbConfig.getIdType());
                } else {
                    tableInfo.setIdType(tableId.type());
                }
```
DbConfig的代码
``` java
    @Data
    public static class DbConfig {

        /**
         * 数据库类型
         */
        private DbType dbType = DbType.OTHER;
        /**
         * 主键类型（默认 ID_WORKER）
         */
        private IdType idType = IdType.ID_WORKER;
```
所以是MP 会给所有TableId type为NONE的 转成ID_WORKER，所以在检测到数据库插入时，会自动给主键生成一个long类型的主键，正巧 我之前的主键都是Long类型的，而且我之前所有插入操作 全是我自己工具类通过mybatis provider来生成的sql语句，所以MP给我自动生成了id，并set进去，但是我执行的sql语句没有用到，所以也不会出问题。但是当我id 改成了Integer，set的时候就会出现类型转换异常，是因为long类型不能转Integer；所以出问题的原因我搞清楚了；

**Comment by jhd147350** [comment]
@miemieYaho  所以 建议下：能不能只有在执行Mybatis Plus框架自身的insert方法时才会根据idType 来自动给实体类生成id呢？按我的理解，我自己生成的sql（完全不用mybatis plus来生成，也就是我自己实现的insert语句，也不该被mybatis plus给我生成一个id，因为即用不到，还浪费性能），不因该被mybatis plus来做任何干扰；mybatis plus 也只该干扰自身BaseMapper实现的操作；

**Comment by jhd147350** [comment]
通过
``` java
@TableId(type = IdType.AUTO)
private Integer id;
```
也能避免问题

**Comment by miemieYaho** [comment]
不会去判断insert是不是mp提供的
