### ISSUE TITLE
使用 boot 2.1.6 mybatis-plu3.2.0 在使用sqlrunner的遇到问题

### ISSUE THREAD

**Issue by uncle861001** [baomidou/mybatis-plus#1733]
### 当前使用版本(必须填写清楚，否则不予处理)
spring boot 2.1.6.Release
MyBatis-plus 3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
直接使用SqlRunner运行sql语句;
List<Object> tableLists = SqlRunner.db().selectObjs("SHOW TABLES");
在使用3.1.0版本就没有这个问题

### 重现步骤
直接使用SqlRunner运行sql语句;
List<Object> tableLists = SqlRunner.db().selectObjs("SHOW TABLES");

### 报错信息
reating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@55cb3b7] was not registered for synchronization because synchronization is not active
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@55cb3b7]
控制台- | 2019-10-21 14:14:47 | main | ERROR | o.s.boot.SpringApplication - Application run failed
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.baomidou.mybatisplus.core.mapper.SqlRunner.SelectObjs
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at com.baomidou.mybatisplus.extension.toolkit.SqlRunner.selectObjs(SqlRunner.java:157)
	at cn.biao.epic.core.db.DbInitializer.initTable(DbInitializer.java:82)
	at cn.biao.epic.core.db.DbInitializer.dbInit(DbInitializer.java:57)
	at cn.biao.epic.core.db.listener.InitTableListener.onApplicationEvent(InitTableListener.java:29)
	at cn.biao.epic.core.db.listener.InitTableListener.onApplicationEvent(InitTableListener.java:19)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:102)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at cn.biao.epic.system.SystemApplication.main(SystemApplication.java:27)

**Comment by miemieYaho** [comment]
```yml
mybatis-plus:
  global-config:
    enable-sql-runner: true
```
