### ISSUE TITLE
IdType为AUTO,且dbType为Sqlserver，且使用saveBatch时，报错

### ISSUE THREAD

**Issue by kongwang** [baomidou/mybatis-plus#1734]
### 当前使用版本(必须填写清楚，否则不予处理)

3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

调用**service.saveBatch**

### 重现步骤
1.据库为Sqlserver
2.IdType设置为AUTO
3.执行saveBatch
会直接提示"必须执行该语句才能获得结果"

### 报错信息
Caused by: org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:81)
	at com.baomidou.mybatisplus.core.executor.MybatisBatchExecutor.doFlushStatements(MybatisBatchExecutor.java:138)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.CachingExecutor.flushStatements(CachingExecutor.java:114)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:252)

### 建议
当dbType不支持save/update batch 时，能否文档说明，并且默认使用NoKeyGenerator?

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/1629
