### ISSUE TITLE
JacksonTypeHandler处理带泛型的Map发生转型异常

### ISSUE THREAD

**Issue by dongshaofei666** [baomidou/mybatis-plus#1748]
### 当前使用版本(必须填写清楚，否则不予处理)
3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
当我测试“字段类型处理器”时，在样例上做了一些的修改，具体修改如下。

### 重现步骤
**schema-h2.sql**
```
--- 加了一个json字段：map
CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	wallet VARCHAR(3000) NULL DEFAULT NULL COMMENT '钱包',
	other_info VARCHAR(3000) NULL DEFAULT NULL COMMENT '其他信息',
	map VARCHAR(3000) NULL DEFAULT NULL COMMENT '测试带泛型的Map',
	PRIMARY KEY (id)
);
```

**data-h2.sql**
```
---  给map字段赋了值，请注意map中‘b’，由于mysql5.7版本的json字段类型，会自动把` “b”:4.0 `修改为`“b”:4`，所以我不得不这样写json，这也是我为什么死心眼不直接把4改成4.0的原因
INSERT INTO user (id, name, age, email, wallet, other_info,map) VALUES
(2, 'Jack', 20, 'test2@baomidou.com', '{
    "name": "微信钱包",
    "currencyList": [{
        "type": "USD",
        "amount": 888.18
    },{
        "type": "RMB",
        "amount": 1000.18
    }]
}', '{
        "sex": "男",
        "city": "青岛"
}',
'{ "a":3.1, "b":4, "c":5.0}'
);
```

**User.java**
```
    //同样地，在实体类中添加这个字段，并采用JacksonTypeHandler.class进行解析
    @TableField(typeHandler = JacksonTypeHandler.class)
    private Map<String,Double> map;
```

**SampleTest.java**
```
    @Test
    public void test() {
        User Jack = userMapper.selectById(2);
        System.err.println("我的测试-a："+Jack.getMap().get("a").getClass().getName());
        System.err.println("我的测试-b："+Jack.getMap().get("b").getClass().getName());
    }

```
### 报错信息
ps:  这里测试a是没有问题的，b却报了错
```
我的测试-a：java.lang.Double
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at com.baomidou.mybatisplus.samples.typehandler.SampleTest.test(SampleTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

**Comment by dongshaofei666** [comment]
最初遇到这个问题，我是修改mysql数据库把4改成4.0的，发现mysql会蛋疼的自动再把它改回来😂，数据中出现4.0或3.0是在所难免的，
最终不得不自定义一个typeHandler, 于是照着com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler的源码自己又手写了一个，
发现这个类json解析几乎是写死的，实在不知道咋写了
```
   //这个构造器的参数很不灵活，我想用jackson的：com.fasterxml.jackson.databind.JavaType，因为它还可以自定义集合、Map等类型的解析器
    public JacksonTypeHandler(Class<Object> type) {
        if (log.isTraceEnabled()) {
            log.trace("JacksonTypeHandler(" + type + ")");
        }
        if (null == type) {
            throw new MybatisPlusException("Type argument cannot be null");
        }
        this.type = type;
    }

    private Object parse(String json) {
        try {
            if (json == null || json.length() == 0) {
                return null;
            }
            /**
              这里打算：
              JavaType javaType = objectMapper.getTypeFactory().constructMapType(Map.class, String.class, Double.class);
               return objectMapper.readValue(json, javaType );
           */
            return objectMapper.readValue(json, type);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

```

**Comment by dongshaofei666** [comment]
烦请问一下大牛们，我这个问题还有好的解决办法吗？只要能解决就行

**Comment by miemieYaho** [comment]
把你的问题描述清楚,你想要的效果,实际效果,如何使用,代码贴全

**Comment by dongshaofei666** [comment]
demo已经上传了，运行测试即可，问题描述和想要效果在测试的注释里面
https://github.com/dongshaofei666/mybatis-plus-sample-typehandler.git

**Comment by miemieYaho** [comment]
```java
@TableField(typeHandler = JacksonTypeHandler.class)
private Map<String,Double> map;
```
改成
```java
@TableField(typeHandler = JacksonTypeHandler.class)
private Map<String,Object> map;
```
我们提供的typehandler无法识别带泛型的

**Comment by dongshaofei666** [comment]
不能那样做，因为项目中涉及的这个字段比较复杂，这样做计算时每次都要转型，起先就想到这样做了，我还是用我那个自定义的JsonTypeHandler吧

**Comment by qmdx** [comment]
> 不能那样做，因为项目中涉及的这个字段比较复杂，这样做计算时每次都要转型，起先就想到这样做了，我还是用我那个自定义的JsonTypeHandler吧

mp 默认 JsonTypeHandler 如果无法满足欢迎改进 pr
