### ISSUE TITLE
dubbo2.7.3集成mybatisplus3.1.2问题

### ISSUE THREAD

**Issue by 377796216** [baomidou/mybatis-plus#1906]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.2

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
dubbo2.7.3版本  使用 kryo 序列化协议 会出现问题

### 报错信息
16:43:45.115 [NettyServerWorker-6-1] WARN  org.apache.dubbo.remoting.exchange.codec.ExchangeCodec -  [DUBBO] Skip input stream 6349, dubbo version: 2.7.3, current host: 192.168.1.138
00:00  WARN: [kryo] Unable to load class com.baomidou.mybatisplus.core.conditions.AbstractWrapper$$Lambda$857/938600726 with kryo's ClassLoader. Retrying with current..
00:00  WARN: [kryo] Unable to load class sr !java.lang.invoke.SerializedLambdaoaP with kryo's ClassLoader. Retrying with current..
16:43:45.122 [NettyServerWorker-6-1] WARN  org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation -  [DUBBO] Decode argument failed: com.esotericsoftware.kryo.KryoException: Unable to find class: com.baomidou.mybatisplus.core.conditions.AbstractWrapper$$Lambda$857/938600726
Serialization trace:
normal (com.baomidou.mybatisplus.core.conditions.segments.MergeSegments)
expression (com.baomidou.mybatisplus.core.conditions.query.QueryWrapper), dubbo version: 2.7.3, current host: 192.168.1.138
java.io.IOException: com.esotericsoftware.kryo.KryoException: Unable to find class: com.baomidou.mybatisplus.core.conditions.AbstractWrapper$$Lambda$857/938600726
Serialization trace:
normal (com.baomidou.mybatisplus.core.conditions.segments.MergeSegments)
expression (com.baomidou.mybatisplus.core.conditions.query.QueryWrapper)
	at org.apache.dubbo.common.serialize.kryo.KryoObjectInput.readObject(KryoObjectInput.java:138) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.common.serialize.kryo.KryoObjectInput.readObject(KryoObjectInput.java:147) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:116) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:73) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:132) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:122) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:48) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:90) ~[dubbo-2.7.3.jar:2.7.3]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: com.baomidou.mybatisplus.core.conditions.AbstractWrapper$$Lambda$857/938600726
Serialization trace:

**Comment by miemieYaho** [comment]
不要序列化传输 wrapper
