### ISSUE TITLE
自定义mapper继承basemapper 加入的default方法不会走默认实现

### ISSUE THREAD

**Issue by SixGodloop** [baomidou/mybatis-plus#1972]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
在自定义的basemapper上想加入一些default方法 走默认实现发现不会进入自定义的实现中

### 重现步骤
1.自定义dao继承basemapper
2.dao加入方法 比如
default void methodA(List<V> list, String langType) {
        //逻辑
    }
3.发现不走自定义的default实现，而是永远走从xml去找

### 报错信息
 Invalid bound statement (not found): com.best.oasis.express.biz.dao.scan.ScanRecDao.methodA
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod$SqlCommand.<init>(MybatisMapperMethod.java:242)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.<init>(MybatisMapperMethod.java:54)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.lambda$cachedMapperMethod$0(MybatisMapperProxy.java:65)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.cachedMapperMethod(MybatisMapperProxy.java:65)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:60)

**Comment by tfwx** [comment]
Mybatis本身就支持Dao接口的默认方法，我用默认方法就可以！
