### ISSUE TITLE
3.3.0版本,实体类List中的元素,实际上却是LinkedHashMap

### ISSUE THREAD

**Issue by zhangbro** [baomidou/mybatis-plus#1998]
### 当前使用版本(必须填写清楚，否则不予处理)
当前使用3.3.0   
JDK : 13
源码编译版本 11 

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

如图:

<img width="1297" alt="WeChatc7d43476ccbce13a3404d8f0e4411422" src="https://user-images.githubusercontent.com/28987651/71454366-6edc5800-27cb-11ea-8cf7-34f167d8e58b.png">

这是我的xml  mapper:
![image](https://user-images.githubusercontent.com/28987651/71454397-9af7d900-27cb-11ea-8249-edea0a81cec5.png)

网上也有这种案例 但是没有一个人分析为何产生.只是简单的使用json转换.完全没有营养.我只想知道为何.

### 报错信息
遍历的时候产生:
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class cn.tec42.edu.system.dao.impl.po.User (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; cn.tec42.edu.system.dao.impl.po.User is in unnamed module of loader 'app')
	at cn.tec42.edu.system.dao.impl.UserDaoImpl.getBySignInAccount(UserDaoImpl.java:41)
	at cn.tec42.edu.system.dao.impl.UserDaoImpl$$FastClassBySpringCGLIB$$9cf5337b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	..........

**Comment by miemieYaho** [comment]
去问mybatis
