### ISSUE TITLE
MB-Generator利用Freemarker生成Kotlin类的常量时候报错

### ISSUE THREAD

**Issue by CodingOX** [baomidou/mybatis-plus#2021]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0

### 重现步骤
1. 代码生成的时候，设置生成kotlin类`gc.isKotlin = true`
2. 生成字段常量：`strategy.isEntityColumnConstant=true`
3. 使用Freemarkder模板引擎`mpg.templateEngine = FreemarkerTemplateEngine()`

### 报错信息

```
十二月 30, 2019 4:14:09 下午 freemarker.log._JULLoggerFactory$JULLogger error
严重: Error executing FreeMarker template
FreeMarker template error:
For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> field.name  [in template "templates/entity.kt.ftl" at line 88, column 21]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${field.name.toUpperCase()}  [in template "templates/entity.kt.ftl" at line 88, column 19]
----

Java stack trace (for programmers):
----
freemarker.core.NonHashException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:367)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at freemarker.template.Template.process(Template.java:383)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.writer(FreemarkerTemplateEngine.java:52)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:91)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:103)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt:136)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt)

16:14:09.326 [main] ERROR com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 无法创建文件，请检查配置信息！
freemarker.core.NonHashException: For "." left-hand operand: Expected a hash, but this has evaluated to a string (wrapper: f.t.SimpleScalar):
==> field.name  [in template "templates/entity.kt.ftl" at line 88, column 21]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${field.name.toUpperCase()}  [in template "templates/entity.kt.ftl" at line 88, column 19]
----
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:367)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at freemarker.template.Template.process(Template.java:383)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.writer(FreemarkerTemplateEngine.java:52)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:91)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:103)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt:136)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt)
```

**Comment by nieqiurong** [comment]
尝试使用3.3.1.8-SNAPSHOT

**Comment by CodingOX** [comment]
@CodingOX 继续反馈3.3.0的2个版本。
使用背景如上所述，都是生成Kotlin的问题：
1. 使用Velocity模板引擎，Entity没有生成主键？
2. 使用Beetl模板引擎，报错如下：
```
>>10:14:21:表达式值为空(NULL):field.keyFlag 位于14行 资源:/templates/mapper.xml.vm
空指针
11|    <!-- 通用查询映射结果 -->
    <resultMap id="BaseResultMap" type="${package.Entity}.${entity}">
#foreach($field in ${table.fields})
#if(${field.keyFlag})##生成主键排在第一位
        <id column="${field.name}" property="${field.propertyName}" />
#end
#end
```

**Comment by CodingOX** [comment]
> 尝试使用3.3.1.8-SNAPSHOT

使用快照版本的xml，在生成mapper的时候也报错了：
```
一月 08, 2020 10:21:50 上午 freemarker.log._JULLoggerFactory$JULLogger error
严重: Error executing FreeMarker template
FreeMarker template error:
Can't convert boolean to string automatically, because the "boolean_format" setting was "true,false", which is the legacy deprecated default, and we treat it as if no format was set. This is the default configuration; you should provide the format explicitly for each place where you print a boolean.

----
Tip: Write something like myBool?string('yes', 'no') to specify boolean formatting in place.
----
Tip: If you want "true"/"false" result as you are generating computer-language output (not for direct human consumption), then use "?c", like ${myBool?c}. (If you always generate computer-language output, then it's might be reasonable to set the "boolean_format" setting to "c" instead.)
----
Tip: If you need the same two values on most places, the programmers can set the "boolean_format" setting to something like "yes,no". However, then it will be easy to unwillingly format booleans like that.
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${enableCache}  [in template "templates/mapper.xml.vm" at line 5, column 5]
----

Java stack trace (for programmers):
----
freemarker.core._MiscTemplateException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Configurable.formatBoolean(Configurable.java:1043)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:493)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at freemarker.template.Template.process(Template.java:383)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.writer(FreemarkerTemplateEngine.java:52)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:81)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:103)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt:132)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt)

10:21:50.090 [main] ERROR com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 无法创建文件，请检查配置信息！
freemarker.core._MiscTemplateException: Can't convert boolean to string automatically, because the "boolean_format" setting was "true,false", which is the legacy deprecated default, and we treat it as if no format was set. This is the default configuration; you should provide the format explicitly for each place where you print a boolean.

----
Tip: Write something like myBool?string('yes', 'no') to specify boolean formatting in place.
----
Tip: If you want "true"/"false" result as you are generating computer-language output (not for direct human consumption), then use "?c", like ${myBool?c}. (If you always generate computer-language output, then it's might be reasonable to set the "boolean_format" setting to "c" instead.)
----
Tip: If you need the same two values on most places, the programmers can set the "boolean_format" setting to something like "yes,no". However, then it will be easy to unwillingly format booleans like that.
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${enableCache}  [in template "templates/mapper.xml.vm" at line 5, column 5]
----
	at freemarker.core.Configurable.formatBoolean(Configurable.java:1043)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:493)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at freemarker.template.Template.process(Template.java:383)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.writer(FreemarkerTemplateEngine.java:52)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:81)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:103)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt:132)
	at club.hicode.ktsp.generate.MPGenertorKt.main(MPGenertor.kt)
10:21:50.091 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================

Process finished with exit code 0

```

**Comment by CodingOX** [comment]
> 尝试使用3.3.1.8-SNAPSHOT

再反馈第3个问题，生成kotlin的代码中，如果要求继承父类的某些字段，生成的实体中不会排除他。
比如我的代码中
```
    strategy.setSuperEntityClass(BaseEntity::class.java)
    strategy.setSuperEntityColumns("createTime","updateTime","createUser","updateUser")
```
但是生产的实体中还是有如下信息：
```
    @ApiModelProperty(value = "create_time 添加时间")
    var createTime: LocalDateTime? = null
    @ApiModelProperty(value = "create_user 被谁添加")
    var createUser: Long? = null
    @ApiModelProperty(value = "update_time 更新时间")
    var updateTime: LocalDateTime? = null
    @ApiModelProperty(value = "update_user 更新人")
```
