### ISSUE TITLE
db2数据库，使用wrapper.apply方法添加带数据库函数sql报错

### ISSUE THREAD

**Issue by lucy0417** [baomidou/mybatis-plus#2026]
### 该问题是怎么引起的？

我要在wrapper中添加如下查询条件
```
wrapper.apply("ROUND(double(R_WIDTH) / double(R_HEIGHT), 2) = {0}",1.78);
```

生成的count sql如下：
```
SELECT COUNT(1) FROM table_name WHERE (ROUND(double(column_a) / double(column_b), 2) = ?) 
```
传递的参数：
```
1.78(Double)
```

其中column_a 和 column_b有可能为空，但不可能同时为空，生成的count sql在db2数据库中执行成功，没有问题

### 报错信息如下

```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM terminal_info_table WHERE (ROUND(double(R_WIDTH) / double(R_HEIGHT), 2) = ?) 

### The error may exist in io/renren/modules/ies/dao/TerminalInfoDao.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM terminal_info_table WHERE (ROUND(double(R_WIDTH) / double(R_HEIGHT), 2) = ?) 

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy79.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:115)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy128.selectPage(Unknown Source)
	at io.renren.common.service.impl.CrudServiceImpl.page(CrudServiceImpl.java:37)
	at io.renren.common.service.impl.CrudServiceImpl$$FastClassBySpringCGLIB$$53d38c1f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by miemieYaho** [comment]
`SELECT COUNT(1) FROM terminal_info_table WHERE (ROUND(double(R_WIDTH) / double(R_HEIGHT), 2) = ?)` 你这个数据库能执行?报错全是mybatis的异常

**Comment by lucy0417** [comment]
> `SELECT COUNT(1) FROM terminal_info_table WHERE (ROUND(double(R_WIDTH) / double(R_HEIGHT), 2) = ?)` 你这个数据库能执行?报错全是mybatis的异常

是的，可以正常执行，这也是我觉得奇怪的地方

**Comment by miemieYaho** [comment]
你最好自己先排查一下

**Comment by lucy0417** [comment]
是数据库的问题，谢谢
