### ISSUE TITLE
sqlserver2014 insertOrUpdateBatch插入失败

### ISSUE THREAD

**Issue by tianshishouhu** [baomidou/mybatis-plus#208]
/**
     * 顺序递增，不可重复
     */
	@TableId(value="id", type= IdType.AUTO)
	private Integer id;
Error: Cannot execute insertOrUpdateBatch Method. Cause] with root cause com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190) ~[sqljdbc4-4.0.jar!/:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getGeneratedKeys(SQLServerStatement.java:2040) ~[sqljdbc4-4.0.jar!/:?]

**Comment by tianshishouhu** [comment]
是因为触发器没加SET NOCOUNT ON
