### ISSUE TITLE
IllegalArgumentException: Result Maps collection does not contain value

### ISSUE THREAD

**Issue by inkroom** [baomidou/mybatis-plus#2084]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

mvn test

### 重现步骤

使用junit4做单元测试；
通过idea运行单个测试用例没有问题，直接mvn test就会出错。

### 报错信息

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse
 mapping resource: 'file [/mnt/d/work/java/xxxx/target/classes/mapper/OrderMapper.xml]'; nested exception is org.apache.ibatis.builder.IncompleteElementException: Could not find result map 'cn.com.xxx.mapper.OrderMapper.mybatis-plus_O
rder' referenced from 'cn.com.hongding.seal.apply.mapper.OrderMapper.selectById'
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 81 common frames omitted
Caused by: org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [/mnt/d/work/java/xxx/target/classes/mapper/OrderMapper.xml]'; nested exception is org.apache.ibatis.builder.IncompleteElementException: Could not find re
sult map 'cn.com.xxx.mapper.OrderMapper.mybatis-plus_Order' referenced from 'cn.com.xxx.mapper.OrderMapper.selectById'
        at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:595)
        at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:430)
        at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:628)
        at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:214)
        at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$b4b61811.CGLIB$sqlSessionFactory$2(<generated>)
        at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$b4b61811$$FastClassBySpringCGLIB$$869c4271.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$b4b61811.sqlSessionFactory(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 82 common frames omitted
Caused by: org.apache.ibatis.builder.IncompleteElementException: Could not find result map 'cn.com.xxx.mapper.OrderMapper.mybatis-plus_Order' referenced from 'cn.com.xxx.mapper.OrderMapper.selectById'
        at org.apache.ibatis.builder.MapperBuilderAssistant.getStatementResultMaps(MapperBuilderAssistant.java:341)
        at org.apache.ibatis.builder.MapperBuilderAssistant.addMappedStatement(MapperBuilderAssistant.java:285)
        at com.baomidou.mybatisplus.core.injector.AbstractMethod.addMappedStatement(AbstractMethod.java:315)
        at com.baomidou.mybatisplus.core.injector.AbstractMethod.addSelectMappedStatementForTable(AbstractMethod.java:254)
        at com.baomidou.mybatisplus.core.injector.methods.SelectById.injectMappedStatement(SelectById.java:40)
        at com.baomidou.mybatisplus.core.injector.AbstractMethod.inject(AbstractMethod.java:64)
        at com.baomidou.mybatisplus.core.injector.AbstractSqlInjector.lambda$inspectInject$0(AbstractSqlInjector.java:55)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at com.baomidou.mybatisplus.core.injector.AbstractSqlInjector.inspectInject(AbstractSqlInjector.java:55)
        at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:122)
        at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:82)
        at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:103)
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.bindMapperForNamespace(XMLMapperBuilder.java:436)
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:96)
        at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:593)
        ... 95 common frames omitted
Caused by: java.lang.IllegalArgumentException: Result Maps collection does not contain value for cn.com.xxx.mapper.OrderMapper.mybatis-plus_Order
        at org.apache.ibatis.session.Configuration$StrictMap.get(Configuration.java:964)
        at org.apache.ibatis.session.Configuration.getResultMap(Configuration.java:674)
        at org.apache.ibatis.builder.MapperBuilderAssistant.getStatementResultMaps(MapperBuilderAssistant.java:339)
        ... 109 common frames omitted

```

**Comment by miemieYaho** [comment]
自行排查
