### ISSUE TITLE
entity set方法名重复

### ISSUE THREAD

**Issue by IceFoxs** [baomidou/mybatis-plus#2113]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
public void setSampleDateTime(String sampleDateTime) {
		this.parseDateTime(DateTimeUtil.parse(sampleDateTime, "yyyy-MM-dd HH:mm:ss"));
	}

	public void setSampleDateTime(Date dateTime) {
		this.parseDateTime(dateTime);
	}

### 报错信息

Caused by: java.lang.IllegalArgumentException: org.apache.ibatis.reflection.ReflectionException: Ambiguous setters defined for property 'sampleDateTime' in class 'class cn.com.xxxxx.pojo.NetworkSample' with types 'java.lang.String' and 'java.util.Date'.
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:83)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 45 common frames omitted
Caused by: org.apache.ibatis.reflection.ReflectionException: Ambiguous setters defined for property 'sampleDateTime' in class 'class cn.com..xxx.pojo.NetworkSample' with types 'java.lang.String' and 'java.util.Date'.
	at org.apache.ibatis.reflection.Reflector.pickBetterSetter(Reflector.java:209)
	at org.apache.ibatis.reflection.Reflector.resolveSetterConflicts(Reflector.java:180)
	at org.apache.ibatis.reflection.Reflector.addSetMethods(Reflector.java:157)
	at org.apache.ibatis.reflection.Reflector.<init>(Reflector.java:64)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at org.apache.ibatis.reflection.DefaultReflectorFactory.findForClass(DefaultReflectorFactory.java:42)
	at com.baomidou.mybatisplus.core.metadata.TableInfoHelper.initTableFields(TableInfoHelper.java:253)
	at com.baomidou.mybatisplus.core.metadata.TableInfoHelper.initTableInfo(TableInfoHelper.java:142)
	at com.baomidou.mybatisplus.core.injector.AbstractSqlInjector.inspectInject(AbstractSqlInjector.java:53)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:122)
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:82)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:103)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80)
	... 48 common frames omitted

**Comment by miemieYaho** [comment]
mybatis抛的,去找他
