### ISSUE TITLE
mock单元测试用例，走到自带Service的方法报错

### ISSUE THREAD

**Issue by 1140920375** [baomidou/mybatis-plus#2130]
### 当前使用版本(必须填写清楚，否则不予处理)
当前使用mybatis-plus-boot-starter 版本3.0.1  

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
使用mock进行单元测试 。使用的是Service CRUD 封装IService里面的方法报错。

### 重现步骤
AbcdServiceImpl继承了ServiceImpl

//简单的单元测试类
@RunWith(MockitoJUnitRunner.class)
public class AbcdServiceImplTest{
   @InjectMocks
     AbcdServiceImplServiceImpl abcdStdroleService;

    @Test
    public void syncStdrole() {
        when(abcdStdroleService.remove(new QueryWrapper<>())).thenReturn(true);  //这里执行自带的remove方法的时候报错。
   }
}

### 报错信息
java.lang.NullPointerException
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.remove(ServiceImpl.java:206)
at com.xxxx.service.service.impl.AbcdStdroleServiceImplTest.syncStdroleAbcdServiceImplTest.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by miemieYaho** [comment]
自己排查

**Comment by 404951246** [comment]
我也遇到了，麻烦问一下你是怎么解决的呢 @1140920375
