### ISSUE TITLE
使用 lambdaQuery().eq(Bill::getBlno,param)时如果传入值param为null时会报 Cause: java.sql.SQLException: 无效的列类型: 1111

### ISSUE THREAD

**Issue by devcolt** [baomidou/mybatis-plus#2137]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

使用Service. lambdaQuery().eq(Bill::getBlno,param)时如果传入值param为null时会报 Cause: java.sql.SQLException: 无效的列类型: 1111
能否在使用 lambdaQuery()  根据getBlno 返回类型设置  jdbcType?

### 重现步骤
Service. lambdaQuery().eq(Bill::getBlno,param)时如果传入值param为null
### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL3', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #3 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy83.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy90.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.conditions.query.ChainQuery.list(ChainQuery.java:39)
	at 
...

**Comment by miemieYaho** [comment]
不能
