### ISSUE TITLE
JacksonTypeHandler 在3.3.1 中放弃了empty校验？

### ISSUE THREAD

**Issue by JanYunkai** [baomidou/mybatis-plus#2143]
### 当前使用版本(必须填写清楚，否则不予处理)

mybatis-plus -> 3.3.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

@TableField(typeHandler = JacksonTypeHandler.class)
 private java.util.List<Integer> allowMime;

3.2.0 版本会验证字段值是否为null， 或者“”

### 重现步骤

查询解析的字段值为空字符串

### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'allow_mime' from result set.  Cause: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.sun.proxy.$Proxy150.selectList(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.sun.proxy.$Proxy191.selectByQuery(Unknown Source) ~[?:?]
	at com.mobtech.bgm.repository.publisher.service.impl.SlotServiceImpl.lambda$page$0(SlotServiceImpl.java:130) ~[classes/:?]
	at com.github.pagehelper.Page.doSelectPageInfo(Page.java:352) ~[pagehelper-5.1.2.jar:?]
	at com.mobtech.bgm.repository.publisher.service.impl.SlotServiceImpl.page(SlotServiceImpl.java:130) ~[classes/:?]
	at com.mobtech.bgm.repository.publisher.service.impl.SlotServiceImpl$$FastClassBySpringCGLIB$$7031676d.invoke(<generated>) ~[classes/:?]

**Comment by nieqiurong** [comment]
用3.3.2.1-SNAPSHOT试试，使用方式参考https://mp.baomidou.com/guide/install.html#snapshot
