### ISSUE TITLE
idea 插件(mybaitsX)生成map.xml代码时报null空指针

### ISSUE THREAD

**Issue by Odinysus** [baomidou/mybatis-plus#216]
```
null
java.lang.NullPointerException
	at com.intellij.psi.impl.source.tree.ChangeUtil.decodeInformation(ChangeUtil.java:87)
	at com.intellij.psi.impl.source.tree.ChangeUtil.decodeInformation(ChangeUtil.java:79)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.addAfter(CompositePsiElement.java:164)
	at com.intellij.util.xml.impl.DomInvocationHandler.a(DomInvocationHandler.java:820)
	at com.intellij.util.xml.impl.DomInvocationHandler.addCollectionChild(DomInvocationHandler.java:787)
	at com.intellij.util.xml.impl.AddChildInvocation.invoke(AddChildInvocation.java:43)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:681)
	at com.baomidou.plugin.idea.mybatisx.dom.model.Mapper$$EnhancerByJetBrainsMainCglib$$db699ead.addSelect(<generated>)
	at com.baomidou.plugin.idea.mybatisx.generate.SelectGenerator.getTarget(SelectGenerator.java:25)
	at com.baomidou.plugin.idea.mybatisx.generate.StatementGenerator.setupTag(StatementGenerator.java:160)
	at com.baomidou.plugin.idea.mybatisx.generate.StatementGenerator.access$100(StatementGenerator.java:41)
	at com.baomidou.plugin.idea.mybatisx.generate.StatementGenerator$4.selected(StatementGenerator.java:148)
	at com.baomidou.plugin.idea.mybatisx.ui.UiComponentFacade$3.run(UiComponentFacade.java:117)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.baomidou.plugin.idea.mybatisx.ui.UiComponentFacade.setActionForExecutableListener(UiComponentFacade.java:101)
	at com.baomidou.plugin.idea.mybatisx.ui.UiComponentFacade.access$000(UiComponentFacade.java:26)
	at com.baomidou.plugin.idea.mybatisx.ui.UiComponentFacade$4.run(UiComponentFacade.java:123)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1431)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by miemieYaho** [comment]
实测没有此问题
