### ISSUE TITLE
DM数据库  有歧义的列名[TABLE_NAME]

### ISSUE THREAD

**Issue by sunjianbo404** [baomidou/mybatis-plus#2233]
### 当前使用版本(必须填写清楚，否则不予处理)
3.3.1.tmp

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
按照demo执行，自动生成代码的时候，报错

### 重现步骤
        dsc.setUrl("jdbc:dm://localhost:5236");
        dsc.setDriverName("dm.jdbc.driver.DmDriver");
        dsc.setUsername("SYSDBA");
        dsc.setPassword("adinnet2020");
        dsc.setDbType(DbType.DM);
        dsc.setDbQuery(new DMQuery());
        mpg.setDataSource(dsc);
将DM数据库配置成自己的地址

### 报错信息
dm.jdbc.driver.DMException: 第1 行附近出现错误:
有歧义的列名[TABLE_NAME]
	at dm.jdbc.driver.DBError.throwException(DBError.java:635)
	at dm.jdbc.c.b.n.R(MSG.java:222)
	at dm.jdbc.c.b.n.O(MSG.java:182)
	at dm.jdbc.c.b.n.N(MSG.java:162)
	at dm.jdbc.c.a.a(DBAccess.java:892)
	at dm.jdbc.c.a.a(DBAccess.java:319)
	at dm.jdbc.driver.DmdbPreparedStatement.prepareSql(DmdbPreparedStatement.java:141)
	at dm.jdbc.driver.DmdbPreparedStatement.<init>(DmdbPreparedStatement.java:120)
	at dm.jdbc.driver.DmdbConnection.do_prepareStatement(DmdbConnection.java:717)
	at dm.jdbc.driver.DmdbConnection.do_prepareStatement(DmdbConnection.java:703)
	at dm.jdbc.driver.DmdbConnection.prepareStatement(DmdbConnection.java:1303)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:480)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:291)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:151)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:93)
	at com.adinnet.api.MybatisGenerator.main(MybatisGenerator.java:133)

**Comment by nieqiurong** [comment]
#2102

**Comment by nieqiurong** [comment]
用3.3.2.1-SNAPSHOT试试，使用方式参考https://mp.baomidou.com/guide/install.html#snapshot
