### ISSUE TITLE
动态数据源中，使用druid 数据源max-active 字段不生效，还是默认值8

### ISSUE THREAD

**Issue by Owen0527** [baomidou/mybatis-plus#2286]
### 当前使用版本(必须填写清楚，否则不予处理)
<dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.2.0</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
                <version>2.5.5</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>1.1.10</version>
            </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
DruidDataSource.configFromPropety(Properties properties) 此方法没有更新max-active 字段值

### 重现步骤
yml 配置文件，然后启动直接报错
spring:
  datasource:
    dynamic:
      druid:
        #       配置初始化大小、最大、最小
        max-active: 100
        initial-size: 10
        min-idle: 10

### 报错信息

Caused by: java.lang.IllegalArgumentException: illegal initialSize 10, maxActive 8
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:725)
	at com.baomidou.dynamic.datasource.creator.DruidDataSourceCreator.createDataSource(DruidDataSourceCreator.java:140)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDruidDataSource(DataSourceCreator.java:148)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDataSource(DataSourceCreator.java:82)
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourceMap(AbstractDataSourceProvider.java:44)
	at com.baomidou.dynamic.datasource.provider.YmlDynamicDataSourceProvider.loadDataSources(YmlDynamicDataSourceProvider.java:47)
	at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.afterPropertiesSet(DynamicRoutingDataSource.java:226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 70 common frames omitted

**Comment by miemieYaho** [comment]
去 https://github.com/baomidou/dynamic-datasource-spring-boot-starter 提
