### ISSUE TITLE
为什么我的自定义模板老是报找不到的错误，包括新建项目也是如此

### ISSUE THREAD

**Issue by jiyegege** [baomidou/mybatis-plus#2290]
### 当前使用版本(必须填写清楚，否则不予处理)

3.3.1.tmp

### 该问题是怎么引起的？

![QQ20200328-172739](https://user-images.githubusercontent.com/26988300/77819936-a4ba1100-7119-11ea-8554-920f2c6cfabf.png)

### 报错信息

> freemarker.template.TemplateNotFoundException: Template not found for name "templates/controllerme.java.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine, basePackagePath="/").
	at freemarker.template.Configuration.getTemplate(Configuration.java:2869)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2671)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.writer(FreemarkerTemplateEngine.java:50)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:126)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:103)
	at com.careerai.pqms.mybatisPlus.CodeGenerator.main(CodeGenerator.java:127)
17:26:00.595 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================

**Comment by nieqiurong** [comment]
/templates/controllerme.java.ftl

**Comment by jiyegege** [comment]
> /templates/controllerme.java.ftl

我发现了问题，由于设置了build导致资源没有被打包编译，谢谢你的回复
