### ISSUE TITLE
使用group by date() 导致异常

### ISSUE THREAD

**Issue by stjava** [baomidou/mybatis-plus#2362]
### 当前使用版本(必须填写清楚，否则不予处理)

3.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**

在SQL中使用 group by date() 

### 重现步骤

在SQL中使用 group by date() 

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.ClassCastException: net.sf.jsqlparser.expression.Function cannot be cast to net.sf.jsqlparser.schema.Column
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy146.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy188.querySendCount(Unknown Source)

**Comment by nieqiurong** [comment]
要不把你的完整SQL语句发出来看看.

**Comment by stjava** [comment]
select ifnull(count(*), 0)
        from (
                 select count(*)
                 FROM table_1
                 WHERE user_id = #{userId}
                   AND shop_id = #{shopId}
                 GROUP BY day_str
             ) t1

**Comment by stjava** [comment]
> 要不把你的完整SQL语句发出来看看.

select ifnull(count(*), 0)
from (
select count(*)
FROM table_1
WHERE user_id = #{userId}
AND shop_id = #{shopId}
GROUP BY date(time1)
) t1

**Comment by stjava** [comment]
select ifnull(count(1), 0)
        from (
                 select count(1)
                 FROM record_1
                 WHERE user_id = #{userId}
                   AND shop_id = #{shopId}
                 GROUP BY date(date_time1)
             ) t1

**Comment by timandy** [comment]
ifnull 加个别名试试

**Comment by nieqiurong** [comment]
问题还是在group by 函数列的问题，并非前面的语句

**Comment by stjava** [comment]
是的，是函数列的问题。如果不用函数，用一个字段来group by 就没有问题。

**Comment by miemieYaho** [comment]
ClassCastException 发生在哪个位置? 或者说你用了哪些插件?
