### ISSUE TITLE
使用 saveOrUpdateBatch(Collection<T> entityList) 出现问题

### ISSUE THREAD

**Issue by b4ping** [baomidou/mybatis-plus#2399]
### 当前使用版本(必填,否则不予处理)
3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
批量插入或更新时，使用 saveOrUpdateBatch(Collection<T> entityList) 此方法，会引起 Mapped Statements collection does not contain value for xxx.xxxMapper.updateById(insert) 问题

### 重现步骤(如果有就写完整)
迭代使用 saveOrUpdate(T entity) 不会出现问题；
直接使用 saveOrUpdateBatch(Collection<T> entityList) 出现异常

### 报错信息
Caused by: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for xxx.mapper.XxxMapper.updateById
	at org.apache.ibatis.session.Configuration$StrictMap.get(Configuration.java:964)
	at org.apache.ibatis.session.Configuration.getMappedStatement(Configuration.java:755)
	at org.apache.ibatis.session.Configuration.getMappedStatement(Configuration.java:748)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	... 77 common frames omitted

**Comment by miemieYaho** [comment]
怎么用的给个复现demo

**Comment by b4ping** [comment]
> 怎么用的给个复现demo

使用过程中出现，但是我专门单测demo却不出现该问题，可能是我哪个地方没有照顾到，我先关闭这个 issue 吧

**Comment by Ivan97** [comment]
我遇到了同样的问题
