### ISSUE TITLE
java version 1.8.0_111,使用QueryWrapper查询出现  This is impossible to happen

### ISSUE THREAD

**Issue by dataSpark-ux** [baomidou/mybatis-plus#2419]
### 当前使用版本(必填,否则不予处理)
3.0.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
本地环境 java version "1.8.0_201" 没有此问题

### 报错信息

Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: This is impossible to happen
        at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:41)
        at com.baomidou.mybatisplus.core.toolkit.support.SerializedLambda.resolve(SerializedLambda.java:69)
        at com.baomidou.mybatisplus.core.toolkit.LambdaUtils.lambda$resolve$24(LambdaUtils.java:61)
        at java.util.Optional.orElseGet(Optional.java:267)
        at com.baomidou.mybatisplus.core.toolkit.LambdaUtils.resolve(LambdaUtils.java:60)
        at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:55)
        at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:37)
        at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.lambda$addCondition$7fff9b71$1(AbstractWrapper.java:358)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList.getSqlSegment(NormalSegmentList.java:92)
        at com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.getSqlSegment(MergeSegments.java:66)
        at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.getSqlSegment(AbstractWrapper.java:465)
        at sun.reflect.GeneratedMethodAccessor331.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:899)
        at org.apache.ibatis.ognl.OgnlRuntime.getMethodValue(OgnlRuntime.java:1709)
        ... 125 common frames omitted

**Comment by nieqiurong** [comment]
应该是分离依赖打包的问题,并不是你说的java版本问题.

**Comment by miemieYaho** [comment]
使用 3.3.2
