### ISSUE TITLE
mysql关键字会报错

### ISSUE THREAD

**Issue by maojing123** [baomidou/mybatis-plus#2427]
麻烦了 
### 当前使用版本(必填,否则不予处理)
3.3.1

 <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version3.3.1/version>
            </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://user-images.githubusercontent.com/48919665/80856294-3c5fd180-8c7b-11ea-8f09-399d9e2ff5b8.png)

问题描述，就是原来的数据库表 有一个字段 status ,是mysql的关键字。
对应请求参数里面 带有status 则会报错如下：Caused by: org.apache.ibatis.binding.BindingException: Parameter 'status' not found. Available parameters are [p, arg0, param1, param2]

我的xml如下
![image](https://user-images.githubusercontent.com/48919665/80856304-4bdf1a80-8c7b-11ea-8f01-e162ca65c2e7.png)

实体bean如下：
![image](https://user-images.githubusercontent.com/48919665/80856309-53062880-8c7b-11ea-802e-7a3ccd3ed953.png)

mapper如下：

![image](https://user-images.githubusercontent.com/48919665/80856310-58637300-8c7b-11ea-853a-f1176932e57e.png)

### 报错信息

[content-center:192.168.101.26:7011] 2020-05-02 13:34:50.545 ERROR 37305 [884e3b6322f6412e8ea17601e42936fb] [http-nio-7011-exec-5] com.central.common.exception.DefaultExceptionAdvice nested exception is org.apache.ibatis.binding.BindingException: Parameter 'status' not found. Available parameters are [p, arg0, param1, param2]

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'status' not found. Available parameters are [p, arg0, param1, param2]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.sun.proxy.$Proxy146.selectList(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) ~[mybatis-spring-2.0.3.jar:2.0.3]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96) ~[mybatis-plus-core-3.3.1.jar:3.3.1]
	at com.sun.proxy.$Proxy147.selectListPage(Unknown Source) ~[na:na]
	at com.central.content.service.impl.CarouselServiceImpl.findList(CarouselServiceImpl.java:34) ~[classes/:na]
	at com.central.content.service.impl.CarouselServiceImpl$$FastClassBySpringCGLIB$$e81551b.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) ~[spring-aop-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at com.central.content.service.impl.CarouselServiceImpl$$EnhancerBySpringCGLIB$$44c81cc2.findList(<generated>) ~[classes/:na]
	at com.central.content.controller.CarouselController.list(CarouselController.java:41) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893) ~[spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798) ~[spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) [spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at com.central.common.filter.TraceFilter.doFilterInternal(TraceFilter.java:43) [eyolo-common-spring-boot-starter-3.5.0.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at com.central.common.filter.TenantFilter.doFilterInternal(TenantFilter.java:39) [eyolo-common-spring-boot-starter-3.5.0.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88) [spring-boot-actuator-2.1.12.RELEASE.jar:2.1.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilte

**Comment by maojing123** [comment]
截图有问题看不见 我直接贴代码谢谢：

@Mapper
public interface CarouselMapper extends SuperMapper<Carousel> {
    /**
     * 分页查询
     * @param page
     * @param params
     * @return
     */
    List<Carousel> selectListPage(Page<Carousel> page, @Param("p") Map<String, Object> params);
}


@Getter
@Setter
@EqualsAndHashCode(callSuper = false)
@TableName("carousel")
public class Carousel extends SuperEntity {
    private static final long serialVersionUID = 1L;

    private String channel;
    @TableField("`name`")
    private String name;
    private String title;
    private String linkUrl;
    private Integer index;
    @TableField(value = "`status`")
    private Integer status;
    private String imgUrl;
    private Date createTime;
    private Date updateTime;
    private String remark;
    private Date beginTime;
    private Date endTime;
    private Integer mediaType;
}




 <select id="selectListPage" resultType="com.central.content.model.Carousel">
        select * from carousel t
        <trim prefix="where" suffixOverrides="and|or">
            <if test="p.id != null">
                `id` = p.#{id} and
            </if>
            <if test="p.channel != null">
                `channel` = p.#{channel} and
            </if>
            <if test="p.name != null">
                `name` = p.#{name} and
            </if>
            <if test="p.title != null">
                `title` = p.#{title} and
            </if>
            <if test="p.linkUrl != null">
                `link_url` = p.#{linkUrl} and
            </if>
            <if test="p.index != null">
                `index` = p.#{index} and
            </if>
            <if test="p.status != null">
                `status` = p.#{status} and
            </if>
            <if test="p.imgUrl != null">
                `img_url` = p.#{imgUrl} and
            </if>
            <if test="p.createTime != null">
                `create_time` = p.#{createTime} and
            </if>
            <if test="p.updateTime != null">
                `update_time` = p.#{updateTime} and
            </if>
            <if test="p.remark != null">
                `remark` = p.#{remark} and
            </if>
            <if test="p.isValidityTime != null and p.isValidityTime==true">
                `begin_time` &lt;= now() and (`end_time` is null or now() &lt;= `end_time`)
            </if>
            <if test="p.mediaType != null">
                `media_type` = p.#{mediaType} and
            </if>
        </trim>
    </select>

**Comment by maojing123** [comment]
看了你们官网 加了 @tablefield也没有用。还是会报这个错误，然后如果将数据库改成非status则不会报错。

**Comment by miemieYaho** [comment]
你自己代码问题，自己查
