### ISSUE TITLE
queryWrapper查询报错 Parameter 'name' not found. Available parameters are [ew, param1]

### ISSUE THREAD

**Issue by joey-happy** [baomidou/mybatis-plus#2458]
### 当前使用版本(必填,否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus</artifactId>
            <version>3.3.1</version>
            <scope>provided</scope>
        </dependency>

        QueryWrapper<Shop> queryWrapper = new QueryWrapper<Shop>().likeRight("geoHashCode",centerGeoHash.toBase32());

        GeoHash[] adjacentGeoHashArray = centerGeoHash.getAdjacent();
        Stream.of(adjacentGeoHashArray).forEach(geoHash -> queryWrapper.or().likeRight("geoHashCode", geoHash.toBase32()));
        List<Shop> queryShopList = shopMapper.selectList(queryWrapper);

        System.out.println(queryShopList);
### 报错信息
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'name' not found. Available parameters are [ew, param1]

**Comment by miemieYaho** [comment]
本地报错?

**Comment by joey-happy** [comment]
是的

**Comment by miemieYaho** [comment]
最好给出你的复现demo

**Comment by joey-happy** [comment]
spring boot 2 本地单元测试就报错了

**Comment by miemieYaho** [comment]
你这个我们无法复现

**Comment by joey-happy** [comment]
[joey-play-mybatisPlus.zip](https://github.com/baomidou/mybatis-plus/files/4619560/joey-play-mybatisPlus.zip)
麻烦您看看 我这里的单元测试 运行就报错
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.joey.play.mybatisPlus.mapper.UserMapper.selectList

**Comment by miemieYaho** [comment]
Invalid bound statement,扫码mapper 啊

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/81770085-cc223d00-9511-11ea-911a-dead3bb56f86.png)
这么写不对吗？

**Comment by cangshantiannan** [comment]
![image](https://user-images.githubusercontent.com/17872477/81892236-2b994f00-95dd-11ea-8cef-9ff3ee081fb3.png)
 依赖冲突了  建议将

        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus</artifactId>
            <version>3.3.1</version>
        </dependency>


修改为

       <dependency>
          <groupId>com.baomidou</groupId>
          <artifactId>mybatis-plus</artifactId>
         <version>3.3.1.tmp</version>
      </dependency>

**Comment by joey-happy** [comment]
去掉之后 还是报错
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userMapper' defined in file [com/joey/play/mybatisPlus/mapper/UserMapper.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

**Comment by miemieYaho** [comment]
boot 项目只需要一个 `mybatis-plus-boot-starter`

**Comment by joey-happy** [comment]
<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.3.1</version>
		</dependency>

![image](https://user-images.githubusercontent.com/16012082/82014573-74b9d380-96af-11ea-8013-0b8cd5dc13ea.png)
还是报错

**Comment by joey-happy** [comment]
Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.MybatisConfiguration.getLanguageDriver(Ljava/lang/Class;)Lorg/apache/ibatis/scripting/LanguageDriver;
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.getLanguageDriver(MybatisMapperAnnotationBuilder.java:369)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parseStatement(MybatisMapperAnnotationBuilder.java:280)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:112)
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:82)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:103)
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80)
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)

**Comment by miemieYaho** [comment]
NoSuchMethodError = 没找到method = jar包有误 = 依赖冲突

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/82018449-ec8bfc00-96b7-11ea-90fb-6e85bba33f21.png)
没有冲突 还是报错

能否把我的demo运行一下 您那边改好了 在回复啊  每次改一点 每次还是报错

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/82018624-3f65b380-96b8-11ea-9dd5-4985ca91a3f3.png)
依然报错

**Comment by miemieYaho** [comment]
你直接发个git的demo出来

**Comment by joey-happy** [comment]
算了  我放弃了

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/82020808-5efedb00-96bc-11ea-8486-5211bec4c798.png)
这里有demo 就这样吧
