### ISSUE TITLE
达梦数据库查询，Error attempting to get column 'create_time' from result set.  Cause: dm.jdbc.driver.DMException: 不支持的接口或功能

### ISSUE THREAD

**Issue by quezhihui** [baomidou/mybatis-plus#2548]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

执行查询List方法

### 报错信息

org.springframework.jdbc.UncategorizedSQLException: Error attempting to get column 'create_time' from result set.  Cause: dm.jdbc.driver.DMException: 不支持的接口或功能
; uncategorized SQLException; SQL state [HYC00]; error code [6030]; 不支持的接口或功能; nested exception is dm.jdbc.driver.DMException: 不支持的接口或功能
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy188.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy189.selectList(Unknown Source)
	at com.ytszh.ytcloud.admin.service.impl.SysRouteConfServiceImpl.routes(SysRouteConfServiceImpl.java:74)
	at com.ytszh.ytcloud.admin.service.impl.SysRouteConfServiceImpl$$FastClassBySpringCGLIB$$126a62c8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.ytszh.ytcloud.admin.service.impl.SysRouteConfServiceImpl$$EnhancerBySpringCGLIB$$2f4c832a.routes(<generated>)
	at com.ytszh.ytcloud.admin.config.DynamicRouteInitRunner.initRoute(DynamicRouteInitRunner.java:64)
	at com.ytszh.ytcloud.admin.config.DynamicRouteInitRunner$$FastClassBySpringCGLIB$$6992bc0e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: dm.jdbc.driver.DMException: 不支持的接口或功能
	at dm.jdbc.driver.DBError.throwException(DBError.java:678)
	at dm.jdbc.driver.DmdbResultSet.do_getObject(DmdbResultSet.java:1887)
	at dm.jdbc.driver.DmdbResultSet.getObject(DmdbResultSet.java:5052)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_getObject(FilterChainImpl.java:1431)
	at com.alibaba.druid.filter.stat.StatFilter.resultSet_getObject(StatFilter.java:846)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_getObject(FilterChainImpl.java:1427)
	at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.getObject(ResultSetProxyImpl.java:1561)
	at com.alibaba.druid.pool.DruidPooledResultSet.getObject(DruidPooledResultSet.java:1777)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.ResultSetLogger.invoke(ResultSetLogger.java:69)
	at com.sun.proxy.$Proxy298.getObject(Unknown Source)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:38)
	at org.apache.ibatis.type.LocalDateTimeTypeHandler.getNullableResult(LocalDateTimeTypeHandler.java:28)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:521)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:402)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy295.query(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy295.query(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:163)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:90)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)

**Comment by quezhihui** [comment]
数据库字段的类型是TIMESTAMPE(6),实体的类型为LocalDateTime

**Comment by miemieYaho** [comment]
驱动不支持jdbc4

**Comment by quezhihui** [comment]
那如何解决呢

**Comment by miemieYaho** [comment]
升级驱动,升级连接池,java8新时间类型换date

**Comment by quezhihui** [comment]
我这个希望继续用LocalDateTime类型的
具体驱动和连接池要升级
到什么版本您知道吗，知道的话发一下，感谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miemieYaho"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 中午1:49
收件人:&nbsp;"baomidou/mybatis-plus"<mybatis-plus@noreply.github.com&gt;;
抄送:&nbsp;"孟辰"<875975617@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus] 达梦数据库查询，Error attempting to get column 'create_time' from result set.  Cause: dm.jdbc.driver.DMException: 不支持的接口或功能 (#2548)





 
升级驱动,升级连接池,java8新时间类型换date

**Comment by imic07** [comment]
https://blog.csdn.net/imyc7/article/details/118824310?spm=1001.2014.3001.5502

**Comment by qianxiaoning** [comment]
换达梦新驱动就行，比如：
```
<!-- 达梦 -->
  <dependency>
      <groupId>com.dameng</groupId>
      <artifactId>DmJdbcDriver18</artifactId>
      <version>8.1.1.193</version>
  </dependency>
```
