### ISSUE TITLE
Mapper同方法名不同参数数量导致的绑定异常

### ISSUE THREAD

**Issue by wo94zj** [baomidou/mybatis-plus#2567]
### 当前使用版本(必填,否则不予处理)
3.3.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Mapper接口中同方法名不同数量参数导致Mybatis参数绑定异常。

### 重现步骤(如果有就写完整)
Mapper中写两个同名方法，参数个数可不相同。先后执行即可

### 报错信息
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'total' not found. Available parameters are [mediaId, param1, status, param2]
	at org.apache.ibatis.binding.MapperMethod$ParamMap.get(MapperMethod.java:212)
	at org.apache.ibatis.reflection.wrapper.MapWrapper.get(MapWrapper.java:45)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at com.baomidou.mybatisplus.core.executor.**AbstractBaseExecutor.createCacheKey**(AbstractBaseExecutor.java:81)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.createCacheKey(MybatisCachingExecutor.java:248)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:89)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)

**Comment by miemieYaho** [comment]
mybatis就是这样的
