### ISSUE TITLE
 找不到方法 setDefaultEnumTypeHandler 

### ISSUE THREAD

**Issue by DontDream1** [baomidou/mybatis-plus#2608]
### 当前使用版本(必填,否则不予处理)

3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
把老项目的 mybatis 1.3.2升级到 mybatis plus 重新启动就出现了这样的问题

### 重现步骤(如果有就写完整)
升级了版本  启动时报错  

### 报错信息
2020-06-15 10:27:39.501 [restartedMain] DEBUG o.s.b.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception
java.lang.NoSuchMethodError: org.apache.ibatis.session.Configuration.setDefaultEnumTypeHandler(Ljava/lang/Class;)V
	at com.baomidou.mybatisplus.core.MybatisXMLConfigBuilder.settingsElement(MybatisXMLConfigBuilder.java:277)
	at com.baomidou.mybatisplus.core.MybatisXMLConfigBuilder.parseConfiguration(MybatisXMLConfigBuilder.java:127)
	at com.baomidou.mybatisplus.core.MybatisXMLConfigBuilder.parse(MybatisXMLConfigBuilder.java:111)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:574)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:434)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:633)
	at org.fh.config.MasterDataSourceConfig.masterSqlSessionFactory(MasterDataSourceConfig.java:88)
	at org.fh.config.MasterDataSourceConfig$$EnhancerBySpringCGLIB$$a3cd62b6.CGLIB$masterSqlSessionFactory$3(<generated>)
	at org.fh.config.MasterDataSourceConfig$$EnhancerBySpringCGLIB$$a3cd62b6$$FastClassBySpringCGLIB$$f35ed849.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
......
An attempt was made to call the method org.apache.ibatis.session.Configuration.setDefaultEnumTypeHandler(Ljava/lang/Class;)V but it does not exist. Its class, org.apache.ibatis.session.Configuration, is available from the following locations:

    jar:file:/D:/repo/org/mybatis/mybatis/3.4.2/mybatis-3.4.2.jar!/org/apache/ibatis/session/Configuration.class

It was loaded from the following location:

    file:/D:/repo/org/mybatis/mybatis/3.4.2/mybatis-3.4.2.jar

**Comment by miemieYaho** [comment]
自己排查依赖冲突

**Comment by 76teuscher** [comment]
You should not have used my credit card

**Comment by 76teuscher** [comment]
That I can prove

**Comment by 76teuscher** [comment]
You definitely should not have used Tonya and Cindy's. Wait til she sees
that shit

**Comment by qmdx** [comment]
@76teuscher 

What happened?

**Comment by hbuxzy** [comment]
> 自己排查依赖冲突
自己排查不出来啊

**Comment by Luo271** [comment]
@76teuscher sounds wonderful！

**Comment by VampireAchao** [comment]
？
