### ISSUE TITLE
加行级锁越界

### ISSUE THREAD

**Issue by alilcu** [baomidou/mybatis-plus#2611]
### 当前使用版本(必填,否则不予处理)

3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

SELECT
           *
        FROM
         XXXXX
        WHERE
         XXXXX
        FOR UPDATE
加行级锁
### 重现步骤(如果有就写完整)
currentToken应为 变为update 数组越界

### 报错信息
![image](https://user-images.githubusercontent.com/35524997/84653320-ce781c80-af3f-11ea-97c6-46fb1f38bcc1.png)

Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
	at com.baomidou.mybatisplus.core.toolkit.TableNameParser.<init>(TableNameParser.java:92) ~[mybatis-plus-core-3.3.1.tmp.jar:3.3.1.tmp]
	at com.baomidou.mybatisplus.extension.parsers.DynamicTableNameParser.parser(DynamicTableNameParser.java:48) ~[mybatis-plus-extension-3.3.1.tmp.jar:3.3.1.tmp]

**Comment by nieqiurong** [comment]
#2229
