### ISSUE TITLE
同一个package(包括子包)不能同时出现多个package-info.java文件

### ISSUE THREAD

**Issue by haroldyong** [baomidou/mybatis-plus#2729]
### 当前使用版本(必填,否则不予处理)
3.1.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

定义db操作的domain。
比如:

com.sample.data.domain
--package-info.java
com.sample.data.domain.req
--package-info.java
com.sample.data.domain.resp
--package-info.java

问题描述

只要出现多个 package-info.java 在同一个包下面，比如上文列子com.sample.data.domain

则运行 junit时会出现

Caused by: org.apache.ibatis.type.TypeException: The alias 'package-info' is already mapped to the value 'com.sample.data.domain.package-info'.
  at org.apache.ibatis.type.TypeAliasRegistry.registerAlias(TypeAliasRegistry.java:157)
  at org.apache.ibatis.type.TypeAliasRegistry.registerAlias(TypeAliasRegistry.java:147)
  at java.lang.Iterable.forEach(Iterable.java:75)
  at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFacto
ryBean.java:524)
  at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBe
an.java:433)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapab
leBeanFactory.java:1689)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableB
eanFactory.java:1627)
  ... 103 common frames omitted

### 重现步骤(如果有就写完整)

必现

### 报错信息

Caused by: org.apache.ibatis.type.TypeException: The alias 'package-info' is already mapped to the value 'com.sample.data.domain.package-info'.
  at org.apache.ibatis.type.TypeAliasRegistry.registerAlias(TypeAliasRegistry.java:157)
  at org.apache.ibatis.type.TypeAliasRegistry.registerAlias(TypeAliasRegistry.java:147)
  at java.lang.Iterable.forEach(Iterable.java:75)
  at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFacto
ryBean.java:524)
  at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBe
an.java:433)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapab
leBeanFactory.java:1689)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableB
eanFactory.java:1627)
  ... 103 common frames omitted

**Comment by miemieYaho** [comment]
去找mybatis

**Comment by haroldyong** [comment]
好的。谢谢。
