### ISSUE TITLE
自动填充疑问 setFieldValByName

### ISSUE THREAD

**Issue by jingzhe123** [baomidou/mybatis-plus#2779]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
通过以下代码进行了自动填充设置：
 @Override
    public void insertFill(MetaObject metaObject) {
        //log.info("start insert fill ....");
        this.setFieldValByName("df", 0, metaObject);
        this.setFieldValByName( "addDate", new Date(), metaObject); // 起始版本 3.3.0(推荐使用)
        this.setFieldValByName("updateDate", new Date(),metaObject); // 也可以使用(3.3.0 该方法有bug请升级到之后的版本如`3.3.1.8-SNAPSHOT`)
        /* 上面选其一使用,下面的已过时(注意 strictInsertFill 有多个方法,详细查看源码) */

        //this.setInsertFieldValByName("operator", "Jerry", metaObject);
    }
但我不是所有的实体类都有这三个字段，如果没有情况下就报错，请问如何解决，我查看了您3.30以后的更新日志没有看到这方面的更新
### 报错信息

org.apache.ibatis.reflection.ReflectionException: There is no setter for property named 'df' in 'class com.gooinfo.jiwuliao.jichuxinxi.model.JiWuLiaoPrice'
	at org.apache.ibatis.reflection.Reflector.getSetInvoker(Reflector.java:365) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.reflection.MetaClass.getSetInvoker(MetaClass.java:167) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:177) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.core.handlers.MetaObjectHandler.setFieldValByName(MetaObjectHandler.java:90) ~[mybatis-plus-core-3.3.0.jar:3.3.0]
	at com.gooinfo.jiwuliao.handler.MyHandler.insertFill(MyHandler.java:17) ~[classes/:na]

**Comment by miemieYaho** [comment]
用最新版
