### ISSUE TITLE
MyBatisPlusGenerater不支持虚谷数据库

### ISSUE THREAD

**Issue by unique1319** [baomidou/mybatis-plus#2808]
### 当前使用版本(必填,否则不予处理)

<mybatisplus.version>3.3.2</mybatisplus.version>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

MyBatisPlus 的 Generater 功能无法兼容虚谷数据库，应该是虚谷不支持SQL语句
```show table status WHERE 1=1  AND NAME IN (表名')```

### 重现步骤(如果有就写完整)

MyBatisPlusGenerater示例程序连接虚谷数据库，执行main方法即可重现

### 报错信息
```
14:12:04.147 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
java.sql.SQLException: [E19132] 语法错误
	[E19132 L1 C21] 意外符号: 'show' 
	at com.xugu.cloudjdbc.Error.createSQLException(Error.java:46)
	at com.xugu.cloudjdbc.Statement.prepare(Statement.java:455)
	at com.xugu.cloudjdbc.PreparedStatement.<init>(PreparedStatement.java:65)
	at com.xugu.cloudjdbc.Connection.prepareStatement(Connection.java:1567)
	at com.xugu.cloudjdbc.Connection.prepareStatement(Connection.java:1287)
	at com.xugu.cloudjdbc.Connection.prepareStatement(Connection.java:823)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:491)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:291)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:151)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)
	at com.hxgis.commondb.MyBatisPlusGenerater.main(MyBatisPlusGenerater.java:60)
14:26:57.944 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================
Disconnected from the target VM, address: '127.0.0.1:58940', transport: 'socket'

Process finished with exit code 0
```

**Comment by miemieYaho** [comment]
欢迎pr

**Comment by qmdx** [comment]
@unique1319  参考 https://github.com/baomidou/mybatis-plus/pull/2825/files
