### ISSUE TITLE
 org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.OutOfMemoryError: Java heap space]

### ISSUE THREAD

**Issue by butter-fly** [baomidou/mybatis-plus#2810]
### 当前使用版本(必填,否则不予处理)
	
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-boot-starter</artifactId>
				<version>3.1.0</version>
			</dependency>
			

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
业务代码：
QueryWrapper<UserMember> queryWrapper = new QueryWrapper<>();
        queryWrapper.lambda().eq(UserMember::getUserId, userId)
                .eq(UserMember::getIdentityType, PlatformUserTypeEnum.PLATFORM_WECHAT.getPlatformType())
                .orderByDesc(UserMember::getId);
        queryWrapper.last(MyBatisConstant.QUERY_LIMIT_ONE);
        UserMember entity = this.getOne(queryWrapper);

### 重现步骤(如果有就写完整)
使用一年多，第一次出现该问题；

### 报错信息
服务名：user-service, 系统内部错误：org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.OutOfMemoryError: Java heap space]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy144.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:99)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy145.selectOne(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.getOne(ServiceImpl.java:255)
	at com.baomidou.mybatisplus.extension.service.IService.getOne(IService.java:192)
	at com.nipudun.user.service.impl.UserMemberServiceImpl.getWxBindInfoByUserId(UserMemberServiceImpl.java:374)
	at com.nipudun.user.service.impl.UserMemberServiceImpl$$FastClassBySpringCGLIB$$d4acf00.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.nipudun.user.service.impl.UserMemberServiceImpl$$EnhancerBySpringCGLIB$$19ed480e.getWxBindInfoByUserId(<generated>)
	at com.nipudun.user.controller.UserMemberController$8.execute(UserMemberController.java:212)
	at com.nipudun.user.controller.UserMemberController$8.execute(UserMemberController.java:207)
	at com.nipudun.rigger.template.provider.AbstractControllerTemplate.doBiz(AbstractControllerTemplate.java:46)
	at com.nipudun.rigger.template.ControllerTemplate.execute(ControllerTemplate.java:22)
	at com.nipudun.user.controller.UserMemberController.getWxBindInfoByUserId(UserMemberController.java:207)
	at com.nipudun.user.controller.UserMemberController$$FastClassBySpringCGLIB$$207d7a6e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.nipudun.rigger.log.aspect.ProfilerAspect.aroundProfiler(ProfilerAspect.java:92)
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by miemieYaho** [comment]
要靠我们猜吗?

**Comment by qmdx** [comment]
@butter-fly 请问是否解决？升级到 `3.4.0` 看看，如果还是无法解决给出你的重新 demo 并打开该 issue

**Comment by zjl-bright** [comment]
@butter-fly  使用 3.1.2版本 遇到同样的问题，你们最后是怎么解决的

**Comment by yipianfan** [comment]
使用3.4.0今天突然出现这个问题，服务重启后，问题又不无法重现。

**Comment by jijinghuli** [comment]
大佬们，你们解决了这个问题吗？这个换版本没有用吧？具体是啥情况导致的呀？

**Comment by marshalby2** [comment]
这应该是JDK版本的问题，我使用jdk11就正常，使用jdk16就有问题

**Comment by dasheng20** [comment]
我也遇到同样问题，有解决方案了没？

**Comment by butter-fly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wfxssky** [comment]
这个问题困扰了好久，3.4也有这个问题，有解决方案了吗

**Comment by jijinghuli** [comment]
好早的问题了。我都忘记我发布了这个问题。应该是版本问题。更换一下jdk版本试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baomidou/mybatis-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月25日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baomidou/mybatis-plus]  org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.OutOfMemoryError: Java heap space] (#2810)





 
这个问题困扰了好久，3.4也有这个问题，有解决方案了吗

**Comment by hankXusAy** [comment]
> 这应该是JDK版本的问题，我使用jdk11就正常，使用jdk16就有问题

你出现这种情况的时候，是偶发的，还是频繁出现呢？

**Comment by butter-fly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
