### ISSUE TITLE
代码生成关于达梦1.6版本数据库sql语句不匹配

### ISSUE THREAD

**Issue by chen1749144759** [baomidou/mybatis-plus#2855]
### 当前使用版本(必填,否则不予处理)
- mybatis-plus generater 3.3.0
- DM数据库1.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.generator.config.builder 包
ConfigBuilder 类
getTablesInfo 方法 
this.dataSourceConfig.getDbQuery().tablesSql(); 获取SQL语句问题
```
SELECT * FROM (SELECT DISTINCT T1.TABLE_NAME AS TABLE_NAME,T2.COMMENTS AS TABLE_COMMENT FROM USER_TAB_COLUMNS T1 INNER JOIN USER_TAB_COMMENTS T2 ON T1.TABLE_NAME = T2.TABLE_NAME) WHERE 1=1 
```
### 重现步骤(如果有就写完整)
正常配置逆向工程参数

### 报错信息
java.sql.SQLException: 无效的表或视图名 'USER_TAB_COLUMNS' 
	at dm.jdbc.dbaccess.DBError.throwSQLException(Unknown Source)
	at dm.jdbc.driver.DmdbCSI.prepareSQL(Unknown Source)
	at dm.jdbc.driver.DmdbStatement.directExec(Unknown Source)
	at dm.jdbc.driver.DmdbPreparedStatement.initialize(Unknown Source)
	at dm.jdbc.driver.DmdbPreparedStatement.<init>(Unknown Source)
	at dm.jdbc.driver.DmdbConnection.prepareStatement(Unknown Source)
	at dm.jdbc.driver.DmdbConnection.prepareStatement(Unknown Source)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:471)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:277)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:137)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)
	at net.yk.wind_p4.config.MybatisPlusGenerator.generator(MybatisPlusGenerator.java:86)
	at net.yk.wind_p4.config.MybatisPlusGenerator.main(MybatisPlusGenerator.java:62)
![微信截图_20200831130928](https://user-images.githubusercontent.com/45381400/91684854-3deac900-eb8b-11ea-8025-0c757ad578e6.png)

**Comment by yuxb** [comment]
可以检查一下你的 数据库用户 是否有访问这个表的权限，直接grant dba to user  试试

**Comment by chen1749144759** [comment]
操作用户为 SYSDBA 默认管理员账户 使用数据库版本为 dm1.6 可能是语法不兼容

发自我的iPhone

在 2020年9月18日，下午5:11，yuxb <notifications@github.com> 写道：

﻿

可以检查一下你的 数据库用户 是否有访问这个表的权限，直接grant dba to user 试试

**Comment by nieqiurong** [comment]
这玩意是不是老版本了?前面PR过来的数据库可能没考虑到这种,缺少这块数据库环境,可能没法处理.

**Comment by chen1749144759** [comment]
我重写了一下 , 如后续需要支持DM6数据库 我可以提供环境

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: nieqiuqiu<mailto:notifications@github.com>
发送时间: 2020年10月9日 13:40
收件人: baomidou/mybatis-plus<mailto:mybatis-plus@noreply.github.com>
抄送: chen1749144759<mailto:chenzeshi@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [baomidou/mybatis-plus] 代码生成关于达梦1.6版本数据库sql语句不匹配 (#2855)


这玩意是不是老版本了?前面PR过来的数据库可能没考虑到这种,缺少这块数据库环境,可能没法处理.

―
