### ISSUE TITLE
mybatis plus对拦截器的支持

### ISSUE THREAD

**Issue by ericql** [baomidou/mybatis-plus#2891]
### 当前使用版本(必填,否则不予处理)
mybatis plus version：3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用mybatis的拦截器，直接报错

### 重现步骤(如果有就写完整)
进行自定义拦截器，后executor没有加载进来，为null

### 报错信息

java.lang.NullPointerException: null
	at org.apache.ibatis.session.defaults.DefaultSqlSession.close(DefaultSqlSession.java:263) ~[mybatis-3.5.5.jar:3.5.5]
	at org.mybatis.spring.SqlSessionUtils.closeSqlSession(SqlSessionUtils.java:195) ~[mybatis-spring-2.0.5.jar:2.0.5]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:448) ~[mybatis-spring-2.0.5.jar:2.0.5]
	at com.sun.proxy.$Proxy67.selectList(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) ~[mybatis-spring-2.0.5.jar:2.0.5]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:173) ~[mybatis-plus-core-3.4.0.jar:3.4.0]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78) ~[mybatis-plus-core-3.4.0.jar:3.4.0]

**Comment by miemieYaho** [comment]
给出你的复现demo

**Comment by ericql** [comment]
[spring-boot-mybatis-sensitive.zip](https://github.com/baomidou/mybatis-plus/files/5205927/spring-boot-mybatis-sensitive.zip)

**Comment by miemieYaho** [comment]
你自己写的插件自己处理
