### ISSUE TITLE
项目在引入 mybatis-plus-generator 3.2.0 之后，LocalDateTime类型接收mysql timestamp 会报错

### ISSUE THREAD

**Issue by dackh** [baomidou/mybatis-plus#2902]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-generator 3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
应该是mybatis-plus-generator 3.2.0这个jar包依赖的包导致的....

我还没来得及排查一下具体的原因

通过这个工具生成的timestamp类型默认是localDateTime类型的，但是一跑就会报错，所以还是有点恶心的

### 重现步骤(如果有就写完整)
项目引入mybatis-plus-generator 3.2.0包，通过它生成对应db实体类，包含timestamp --> LocalDateTime

对这个实体类 进行select 就会报错了

### 报错信息

org.springframework.dao.InvalidDataAccessApiUsageException: Error attempting to get column 'update_time' from result set.  Cause: java.sql.SQLFeatureNotSupportedException
; null; nested exception is java.sql.SQLFeatureNotSupportedException
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:96)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy87.selectList(Unknown Source)

**Comment by dackh** [comment]
https://github.com/baomidou/mybatis-plus/issues/1864

这里也有差不多的问题

最新3.3.0版本也没解决这个问题

**Comment by miemieYaho** [comment]
升级druid
