### ISSUE TITLE
mybatis plus saveBatch 批量插入报错

### ISSUE THREAD

**Issue by zhaohr1107** [baomidou/mybatis-plus#2932]
### 当前使用版本(必填,否则不予处理)

3.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

调用saveBatch批量插入报错。

### 重现步骤(如果有就写完整)

调用saveBatch批量插入报错。

### 报错信息

com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234) ~[mssql-jdbc-7.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getGeneratedKeys(SQLServerStatement.java:2207) ~[mssql-jdbc-7.4.1.jre8.jar:na]
	at com.alibaba.druid.pool.DruidPooledStatement.getGeneratedKeys(DruidPooledStatement.java:835) ~[druid-1.1.20.jar:1.1.20]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:78) ~[mybatis-3.5.3.jar:3.5.3]
	at com.sun.proxy.$Proxy242.getGeneratedKeys(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:75) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.core.executor.MybatisBatchExecutor.doFlushStatements(MybatisBatchExecutor.java:139) ~[mybatis-plus-core-3.3.1.tmp.jar:3.3.1.tmp]
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129) ~[mybatis-3.5.3.jar:3.5.3]
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122) ~[mybatis-3.5.3.jar:3.5.3]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.flushStatements(MybatisCachingExecutor.java:216) ~[mybatis-plus-core-3.3.1.tmp.jar:3.3.1.tmp]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:252) ~[mybatis-3.5.3.jar:3.5.3]

**Comment by miemieYaho** [comment]
sqlserver驱动不支持

**Comment by lcb1208** [comment]
> sqlserver驱动不支持

8.4.0以上已经支持了，详情：https://github.com/microsoft/mssql-jdbc/issues/1360

**Comment by zhaohr1107** [comment]
> > sqlserver驱动不支持
> 
> 8.4.0以上已经支持了，详情：[microsoft/mssql-jdbc#1360](https://github.com/microsoft/mssql-jdbc/issues/1360)

已使用8.4.0测试，依然报错

**Comment by zhaohr1107** [comment]
> sqlserver驱动不支持

目前没有解决方法吗?
