### ISSUE TITLE
代码生成器不支持clickhouse数据库

### ISSUE THREAD

**Issue by YSY79** [baomidou/mybatis-plus#2941]
### 当前使用版本(必填,否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.4.0</version>
        </dependency>
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
     MyBatisPlus 的 Generater 不兼容clickhouse数据库
     不支持sql语句：show table status WHERE 1=1 AND NAME IN (表名') 
     可用 DESCRIBE TABLE (表名) 查询表信息
### 重现步骤(如果有就写完整)
连接clickhouse数据库，执行生成代码main方法
### 报错信息
```
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 62, host: 192.168.130.159, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6 (line 1, col 6): table status WHERE 1=1  AND NAME IN ('test')
FORMAT TabSeparatedWithNamesAndTypes;. Expected one of: TABLES, GRANTS, CREATE, ACCESS, QUOTA, CURRENT ROLES, PRIVILEGES, PROCESSLIST, CURRENT QUOTA, ENABLED ROLES, CREATE, DICTIONARIES, QUOTAS, ROW POLICIES, POLICIES, SETTINGS PROFILES, PROFILES, ROLES, USERS (version 20.6.4.44 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeQuery(ClickHousePreparedStatementImpl.java:110)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:472)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:277)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:137)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)
	at com.bsj.utils.MybatisPlusGeneratorUtil.generator(MybatisPlusGeneratorUtil.java:160)
	at com.bsj.utils.MybatisPlusGeneratorUtil.main(MybatisPlusGeneratorUtil.java:44)
Caused by: java.lang.Throwable: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 6 (line 1, col 6): table status WHERE 1=1  AND NAME IN ('test2')
FORMAT TabSeparatedWithNamesAndTypes;. Expected one of: TABLES, GRANTS, CREATE, ACCESS, QUOTA, CURRENT ROLES, PRIVILEGES, PROCESSLIST, CURRENT QUOTA, ENABLED ROLES, CREATE, DICTIONARIES, QUOTAS, ROW POLICIES, POLICIES, SETTINGS PROFILES, PROFILES, ROLES, USERS (version 20.6.4.44 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 14 more
```

**Comment by miemieYaho** [comment]
pr啊

**Comment by mythosguo** [comment]
啥时候能支持？？
