### ISSUE TITLE
调用removeIds 报错

### ISSUE THREAD

**Issue by SmallRen** [baomidou/mybatis-plus#2954]
### 当前使用版本(必填,否则不予处理)

3.3.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

removeIds(List)

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/24424101/94551430-ede54c00-0287-11eb-85c7-6e8119f85171.png)

### 报错信息

![image](https://user-images.githubusercontent.com/24424101/94551246-a2cb3900-0287-11eb-9ccb-980ba9f14bd1.png)

**Comment by SmallRen** [comment]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '__frch_item_0'. It was either not specified and/or could not be found for the javaType (com.ctfo.prod.iles.tcle.module.business.entity.DailyAffairsScheduleGroup) : jdbcType (null) combination.
### The error may exist in com/ctfo/prod/iles/tcle/module/business/mapper/DailyAffairsScheduleGroupMapper.java (best guess)
### The error may involve com.ctfo.prod.iles.tcle.module.business.mapper.DailyAffairsScheduleGroupMapper.deleteBatchIds
### The error occurred while executing an update
### Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '__frch_item_0'. It was either not specified and/or could not be found for the javaType (com.ctfo.prod.iles.tcle.module.business.entity.DailyAffairsScheduleGroup) : jdbcType (null) combination.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92) ~[mybatis-spring-2.0.5.jar:2.0.5]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440) ~[mybatis-spring-2.0.5.jar:2.0.5]
	at com.sun.proxy.$Proxy136.delete(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:303) ~[mybatis-spring-2.0.5.jar:2.0.5]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:70) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.sun.proxy.$Proxy156.deleteBatchIds(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.removeByIds(ServiceImpl.java:215) ~[mybatis-plus-extension-3.3.0.jar:3.3.0]
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$76535273.invoke(<generated>) ~[mybatis-plus-extension-3.3.0.jar:3.3.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.ctfo.prod.iles.tcle.module.business.service.impl.DailyAffairsScheduleGroupServiceImpl$$EnhancerBySpringCGLIB$$a8f435c4.removeByIds(<generated>) ~[classes/:na]
	at com.ctfo.prod.iles.tcle.module.business.service.impl.DailyAffairsScheduleMonthServiceImpl.update(DailyAffairsScheduleMonthServiceImpl.java:150) ~[classes/:na]
	at com.ctfo.prod.iles.tcle.module.business.service.impl.DailyAffairsScheduleMonthServiceImpl$$FastClassBySpringCGLIB$$78dc744d.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.ctfo.prod.iles.tcle.module.business.service.impl.DailyAffairsScheduleMonthServiceImpl$$EnhancerBySpringCGLIB$$c3907541.update(<generated>) ~[classes/:na]
	at com.ctfo.prod.iles.tcle.module.business.controller.DailyAffairsScheduleMonthController.update(DailyAffairsScheduleMonthController.java:59) ~[classes/:na]
	at com.ctfo.prod.iles.tcle.module.business.controller.DailyAffairsScheduleMonthController$$FastClassBySpringCGLIB$$21746467.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.ctfo.common.web.validation.ValidationAspect.arround(ValidationAspect.java:103) ~[ctfo-common-util-1.1-20200917.121444-2.jar:1.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]

**Comment by miemieYaho** [comment]
只能传入id的list

**Comment by wangjia2016** [comment]
@SmallRen 解决了吗？

**Comment by forever14998** [comment]
换成 id的list 就好了。

**Comment by LSyz123** [comment]
I think i am wrong on here with this problem , just i change the id to the list , also still get the same wrong, can you give me some good advice. How to fix this problem. I got the data is list type, but I still wrong on there, PLZ response me , thank you.
