### ISSUE TITLE
开启乐观锁插件updateById(子类)的时候会报nullpointer

### ISSUE THREAD

**Issue by BestBurning** [baomidou/mybatis-plus#299]
开启乐观锁插件`updateById(子类)`的时候会报`NullPointerException` :
`Caused by: java.lang.NullPointerException: null
	at com.baomidou.mybatisplus.plugins.OptimisticLockerInterceptor.intercept(OptimisticLockerInterceptor.java:127)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy126.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 79 common frames omitted`

原因是
`Class<?> entityClass = ClassUtils.getUserClass(et.getClass());`
` TableInfo tableInfo = TableInfoHelper.getTableInfo(entityClass);`
这里拿不到

**Comment by qmdx** [comment]
merge https://github.com/baomidou/mybatis-plus/pull/301
