### ISSUE TITLE
集成mybatis,项目启动报错

### ISSUE THREAD

**Issue by dingyong-hm** [baomidou/mybatis-plus#3061]
### 当前使用版本(必填,否则不予处理)
                <dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.3.2</version>
		</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
集成入项目，服务启动时报错

### 重现步骤(如果有就写完整)

服务启动报错

### 报错信息

Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(Depende

**Comment by zhangxieyin** [comment]
Hi,do you solve this problem? I meet zhe same error,when my project started

**Comment by miemieYaho** [comment]
see https://github.com/baomidou/mybatis-plus-samples

**Comment by zhangxieyin** [comment]
@miemieYaho  can you give me detailed page address, thanks.

**Comment by miemieYaho** [comment]
@zhangxieyin mybatis-plus-sample-quickstart

**Comment by zhangxieyin** [comment]
@miemieYaho  I start another project successfully,but i failed to start this project when i use zhe same config .
