### ISSUE TITLE
3.4.0设置多租户后异步执行sql报错

### ISSUE THREAD

**Issue by Wxdddd** [baomidou/mybatis-plus#3080]
### 当前使用版本(必填,否则不予处理)

3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

@Async("executor")异步执行的mapper报错，发现与行级租户设置有关。

### 重现步骤(如果有就写完整)

![image](https://user-images.githubusercontent.com/20082827/99777049-b50d7900-2b4c-11eb-9f17-66388223434d.png)

### 报错信息
2020-11-20 16:25:03 xtt-1 ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void com.xtt.qc.service.BaseServiceImpl.updateLatestData(com.xtt.qc.pojo.base.BaseLatestData)
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy77.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:65)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy106.updatePatientLatestData(Unknown Source)
	at com.xtt.qc.service.BaseServiceImpl.lambda$updateLatestData$0(BaseServiceImpl.java:33)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.xtt.qc.service.BaseServiceImpl.updateLatestData(BaseServiceImpl.java:32)
	at com.xtt.qc.service.BaseServiceImpl$$FastClassBySpringCGLIB$$feca7672.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by miemieYaho** [comment]
你租户信息存线程里异步取不到怪我们?

**Comment by Wxdddd** [comment]
不好意思 疏忽了
