### ISSUE TITLE
南大通用GBase怎么使用？

### ISSUE THREAD

**Issue by xiaoqhuang** [baomidou/mybatis-plus#3100]
### 当前使用版本(必填,否则不予处理)
v3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
GBase版本v8.8 3.0.0
jdbc driver: com.gbasedbt.jdbc.Driver
jdbc url: jdbc:gbasedbt-sqli://ip

### 重现步骤(如果有就写完整)
配置gbase连接后运行代码生成报错，
能确认连接是成功的
说语法错误，跟踪SQL语句为"show table status where 1=1 and name in ('某个表名')"
改语句客户端执行也不支持

### 报错信息
java.sql.SQLException: A syntax error has occurred.

at com.gbasedbt.util.IfxErrMsg.getSQLException(IfxErrMsg.java:408)

at com.gbasedbt.jdbc.IfxSqli.a(IfxSqli.java:3502)

at com.gbasedbt.jdbc.IfxSqli.D(IfxSqli.java:3782)

at com.gbasedbt.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2684)

at com.gbasedbt.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2609)

at com.gbasedbt.jdbc.IfxSqli.executePrepare(IfxSqli.java:1244)

at com.gbasedbt.jdbc.IfxPreparedStatement.f(IfxPreparedStatement.java:307)

at com.gbasedbt.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:288)

at com.gbasedbt.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:181)

at com.gbasedbt.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:6181)

at com.gbasedbt.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:2486)

at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:363)

at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:113)

at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)

at com.xmgps.api.prototype.BaseCodeGenerator.generate(BaseCodeGenerator.java:102)

at com.xmgps.api.prototype.BaseCodeGenerator.generate(BaseCodeGenerator.java:117)

at com.xmgps.api.prototype.BaseCodeGenerator.main(BaseCodeGenerator.java:326)

Caused by: java.sql.SQLException

at com.gbasedbt.util.IfxErrMsg.getSQLException(IfxErrMsg.java:408)

at com.gbasedbt.jdbc.IfxSqli.D(IfxSqli.java:3787)

... 14 more

**Comment by xiaoqhuang** [comment]
看DbQueryRegistry里面没有为GBase注册表信息查询语句，默认走mysql方式。看来这个版本是不支持GBase代码生成

**Comment by miemieYaho** [comment]
你可以pr

**Comment by qmdx** [comment]
建议支持后pull request

**Comment by 836219171** [comment]
gbase我们也在用，我们的是8a版本，你们应该是8s版本吧
GBase版本v8.3.81.53
jdbc driver: com.gbase.jdbc.Driver
jdbc url: jdbc:gbase://ip
我们用的是gbase8a  8.6.2.43版本，jdbc驱动jar 8.3.81.53
可以正常生成，gbase本身基于mysql。
