### ISSUE TITLE
无法支持批量更新语句(mysql)

### ISSUE THREAD

**Issue by largeTree** [baomidou/mybatis-plus#3176]
### 当前使用版本(必填,否则不予处理)
3.0.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用**批量更新**语句
```
    update xx_table xx
    join (
        select
              '1' as id,
              'qiuxs' as name
        union all 
        select 
             '2' as id,
             'baomidou' as name
   ) T
   set xx.name = T.name
   where xx.id = T.id
```

### 重现步骤(如果有就写完整)
执行类似sql则报错

### 报错信息

```
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL:     update xx_table xx
                      join (
                          select
                              '1' as id,
                              'qiuxs' as name
                         union all 
                         select 
                             '2' as id,
                             'baomidou' as name
                    ) T
                    set xx.name = T.name
                    where xx.id = T.id
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:41)
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:78)
	at com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler.sqlParser(AbstractSqlParserHandler.java:63)
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:129)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy382.prepare(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.pig4cloud.pigx.common.data.datascope.DataScopeInterceptor.intercept(DataScopeInterceptor.java:79)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy382.prepare(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 134 common frames omitted
```

**Comment by miemieYaho** [comment]
去掉不必要的插件
