### ISSUE TITLE
MyBatis-plus 分页中Count缓存createCacheKey 与 getCountCacheKey 缓存Hash值不一致

### ISSUE THREAD

**Issue by ContinueOneSecond** [baomidou/mybatis-plus#3249]
### 当前使用版本(必填,否则不予处理)
3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用Redis代理二级缓存中发现存在两个Count缓存，并且总是获取错的Count缓存
Count缓存createCacheKey的 与 getCountCacheKey 结果不一致

### 重现步骤(如果有就写完整)
在MybatisCachingExecutor类中

`
//确定原本的key有正确的值 
Object result = this.tcm.getObject(cache, key);`

`if (pageOptional.isPresent()) {
                    page = (IPage)pageOptional.get();
                    if (page.isSearchCount()) {
//在这里获取缓存的的key被改变，最终获取了错误的值
                        cacheKey = this.getCountCacheKey(ms, boundSql, parameterObject, RowBounds.DEFAULT);
                        count = (Number)this.tcm.getObject(cache, cacheKey);
                        if (count != null) {
                            page.hitCount(true);
                            return new PageList((List)result, count.longValue());
                        }`

导致在
`Object result = executor.query(countMs, parameter, rowBounds, resultHandler, cacheKey, countSql).get(0);`
数组越界

望解答

### 报错信息
`org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy89.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:122)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:87)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy90.selectPage(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.page(IService.java:298)
	at com.nacos.demo.repository.demo.service.impl.DemoServiceImpl.page(DemoServiceImpl.java:63)
	at com.nacos.demo.repository.demo.service.impl.DemoServiceImpl.page(DemoServiceImpl.java:21)
	at com.nacos.demo.repository.demo.service.impl.DemoServiceImpl$$FastClassBySpringCGLIB$$f20e5108.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.nacos.demo.repository.demo.service.impl.DemoServiceImpl$$EnhancerBySpringCGLIB$$197f6a56.page(<generated>)
	at com.nacos.demo.demo.provider.impl.DemoProviderImpl.getPage(DemoProviderImpl.java:32)
	at com.nacos.demo.demo.rest.DemoController.getPage(DemoController.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 73 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor.willDoQuery(PaginationInnerInterceptor.java:134)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:59)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy111.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 79 more`

**Comment by miemieYaho** [comment]
https://mybatis.plus/guide/interceptor.html

**Comment by ContinueOneSecond** [comment]
我已经在Mybatis中配置了新的分页配置，但是没有解决这个问题。这个问题只会在redis代理二级缓存的时候出现该问题，我的redis是哨兵模式启动，二级缓存采用hash格式，fastJson的序列化格式，请问是否有影响？

**Comment by ContinueOneSecond** [comment]
> https://mybatis.plus/guide/interceptor.html

我已经在Mybatis中配置了新的分页配置，但是没有解决这个问题。这个问题只会在redis代理二级缓存的时候出现该问题，我的redis是哨兵模式启动，二级缓存采用hash格式，fastJson的序列化格式，请问是否有影响？

**Comment by miemieYaho** [comment]
```java
@Bean
    public ConfigurationCustomizer configurationCustomizer() {
        return configuration -> configuration.setUseDeprecatedExecutor(false);
    }
```

**Comment by ContinueOneSecond** [comment]
> ```java
> @Bean
>     public ConfigurationCustomizer configurationCustomizer() {
>         return configuration -> configuration.setUseDeprecatedExecutor(false);
>     }
> ```

已解决： 
我是采用自定义配置类的形式
仔细看过 `ConfigurationCustomizer` 后发现是 通过 自定义 `MybatisConfiguration中 mybatisConfiguration.setUseDeprecatedExecutor(false);`进行配置
同样插件需要通过 `sqlSessionFactory.setPlugins(mybatisPlusInterceptor);`进行手动配置
新版本配置，建议可以写在官方文档。
感谢您的帮助。

**Comment by gathercode** [comment]
你好，具体怎么解决的，可以交流下吗？

**Comment by ContinueOneSecond** [comment]
> 你好，具体怎么解决的，可以交流下吗？

我可以怎么样帮助到你？

**Comment by gathercode** [comment]
您好，方便加我QQ吗？77826118，谢谢

**Comment by gathercode** [comment]
<dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
      <version>3.4.2</version>
    </dependency>
    

public class MybatisPlusConfig {

  @Bean
  public MybatisPlusInterceptor mybatisPlusInterceptor() {
    var interceptor = new MybatisPlusInterceptor();
    interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
    return interceptor;
  }

  @Bean
  public ConfigurationCustomizer configurationCustomizer() {
    return configuration -> configuration.setUseDeprecatedExecutor(false);
  }
}


configuration.setUseDeprecatedExecutor(false);这个不存在

**Comment by WhatIsGhost** [comment]
> ```
> <dependency>
>   <groupId>com.baomidou</groupId>
>   <artifactId>mybatis-plus-boot-starter</artifactId>
>   <version>3.4.2</version>
> </dependency>
> ```
> 
> public class MybatisPlusConfig {
> 
> @bean
> public MybatisPlusInterceptor mybatisPlusInterceptor() {
> var interceptor = new MybatisPlusInterceptor();
> interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
> return interceptor;
> }
> 
> @bean
> public ConfigurationCustomizer configurationCustomizer() {
> return configuration -> configuration.setUseDeprecatedExecutor(false);
> }
> }
> 
> configuration.setUseDeprecatedExecutor(false);这个不存在

同样的问题  版本 3.4.3.3

**Comment by heidanzhang** [comment]
mybatis-plus 版本 3.4.0 
问题已解决!!!
使用spring-boot配置

@bean
public ConfigurationCustomizer configurationCustomizer() {
return configuration -> configuration.setUseDeprecatedExecutor(false);
}

事隔3年了,遇到同样的坑,感谢以上大神们的解答!!!!
