### ISSUE TITLE
我使用了@Resultmap 注解以后解决了映射实体但是出现了mybaits plus自带的crud方法不能使用

### ISSUE THREAD

**Issue by sihouzi08** [baomidou/mybatis-plus#328]
我使用了@Resultmap 注解以后解决了映射实体但是出现了mybaits plus自带的crud方法不能使用

        @Select({"<script>", "SELECT *",
                " FROM levy_table u"+
                      " LEFT JOIN project project1 on project1.id = u.project_id"+
                " WHERE 1 = 1",
                "</script>"})
        @ResultMap("com.alibaba.edas.springboot.mapper.LevyTableMapper.LevyTableEoResult")
        List<LevyTableDto> selectLevyTableList(Pagination page, @Param("levyTableEo" ) LevyTableEo levyTableEo);

下面是异常部分信息

org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.alibaba.edas.springboot.mapper.LevyTableMapper.selectById
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:225)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:48)
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:65)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy118.selectById(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy119.selectById(Unknown Source)

**Comment by sihouzi08** [comment]
不好意思啊 原来springboot里的配置错了
