### ISSUE TITLE
MyBatisExceptionTranslator不能转换的异常会吃掉原异常并抛出空指针异常

### ISSUE THREAD

**Issue by shiylqq** [baomidou/mybatis-plus#3359]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

数据库字段类型定义和pojo属性类型定义不一致

### 重现步骤(如果有就写完整)

数据库字段定义为decimal，pojo类属性定义为string，保存数据时报空指针

### 报错信息

Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_231]
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:185) ~[mybatis-plus-extension-3.4.2.jar:3.4.2]
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:207) ~[mybatis-plus-extension-3.4.2.jar:3.4.2]
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.executeBatch(ServiceImpl.java:239) ~[mybatis-plus-extension-3.4.2.jar:3.4.2]
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveBatch(ServiceImpl.java:135) ~[mybatis-plus-extension-3.4.2.jar:3.4.2]
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$76535273.invoke(<generated>) ~[mybatis-plus-extension-3.4.2.jar:3.4.2]

**Comment by qmdx** [comment]
`3.4.3` 已经解决试试
