### ISSUE TITLE
3.4.2版本saveBatch报错

### ISSUE THREAD

**Issue by jwytd** [baomidou/mybatis-plus#3382]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus</artifactId>
    <version>3.4.2</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
saveBatch  报错  3.2.0版本不会
报错信息：
Caused by: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.xxxx.xxMapper.insert
	at com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap.get(MybatisConfiguration.java:448)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMappedStatement(MybatisConfiguration.java:330)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMappedStatement(MybatisConfiguration.java:322)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	... 155 common frames omitted

### 报错信息
Caused by: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.xxxx.xxMapper.insert
	at com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap.get(MybatisConfiguration.java:448)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMappedStatement(MybatisConfiguration.java:330)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMappedStatement(MybatisConfiguration.java:322)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	... 155 common frames omitted

**Comment by Venus-WXP** [comment]
老哥，我也遇到了同样的问题，请问解决了吗？

**Comment by Ivan97** [comment]
同版本同样的问题 在batch操作时发现的

**Comment by liukeshao** [comment]
自己写batch吧，这个兼容性有问题，里边的语法是mysql的，我遇到过sql server有问题

**Comment by Ivan97** [comment]
> 自己写batch吧，这个兼容性有问题，里边的语法是mysql的，我遇到过sql server有问题

我用的数据库就是mysql语法的。很奇怪。。

**Comment by qmdx** [comment]
请测试 3.4.3 版本是否正常，如果问题给出重现 demo

**Comment by liu-xinhui** [comment]
3.4.4.3-SNAPSHOT saveBatch仍会报这个错误，mysql

**Comment by qmdx** [comment]
> 3.4.4.3-SNAPSHOT saveBatch仍会报这个错误，mysql

给出你使用 demo
