### ISSUE TITLE
使用 GraalVM 报错

### ISSUE THREAD

**Issue by cuihj** [baomidou/mybatis-plus#3403]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用 GraalVM 构建后 ，启动报错

### 报错信息
2021-03-24 12:28:46.316  WARN 9016 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.mybatis.spring.mapper.MapperScannerConfigurer]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.mybatis.spring.mapper.MapperScannerConfigurer.<init>()
2021-03-24 12:28:46.317  INFO 9016 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-24 12:28:46.318 ERROR 9016 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.mybatis.spring.mapper.MapperScannerConfigurer]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.mybatis.spring.mapper.MapperScannerConfigurer.<init>()
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[na:na]
        at org.springframework.beans.AbstractNestablePropertyAccessor.<init>(AbstractNestablePropertyAccessor.java:131) ~[na:na]
        at org.springframework.beans.BeanWrapperImpl.<init>(BeanWrapperImpl.java:111) ~[na:na]

**Comment by miemieYaho** [comment]
java.lang.NoSuchMethodException: org.mybatis.spring.mapper.MapperScannerConfigurer 去找mybatis
