### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by darkgirl** [baomidou/mybatis-plus#3407]
Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invokeDefaultMethod(MybatisMapperProxy.java:71)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:55)
	... 64 common frames omitted

**Comment by miemieYaho** [comment]
自行排查
