### ISSUE TITLE
Service  SaveOrUpdate接口对已有数据修改报错

### ISSUE THREAD

**Issue by tiancaishuhe** [baomidou/mybatis-plus#3412]
### 当前使用版本(必填,否则不予处理)

3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

saveorupdate方法 对已有数据的修改 提示缺包 java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

### 报错信息

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.baomidou.mybatisplus.extension.plugins.inner.BlockAttackInnerInterceptor.getTableLogicField(BlockAttackInnerInterceptor.java:119)
	at com.baomidou.mybatisplus.extension.plugins.inner.BlockAttackInnerInterceptor.checkWhere(BlockAttackInnerInterceptor.java:72)
	at com.baomidou.mybatisplus.extension.plugins.inner.BlockAttackInnerInterceptor.processUpdate(BlockAttackInnerInterceptor.java:68)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.processParser(JsqlParserSupport.java:78)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserMulti(JsqlParserSupport.java:54)
	at com.baomidou.mybatisplus.extension.plugins.inner.BlockAttackInnerInterceptor.beforePrepare(BlockAttackInnerInterceptor.java:57)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:80)

**Comment by huayanYu** [comment]
先加依赖吧，或者去掉BlockAttackInnerInterceptor
