### ISSUE TITLE
openjdk8 IService的实现类中使用getOne方法造成异常问题

### ISSUE THREAD

**Issue by andotorg** [baomidou/mybatis-plus#3420]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
实现了IService 接口之后
调用相应的实现类的getOne方法

### 重现步骤(如果有就写完整)
//1. 校验用户是否有效
		//update-begin-author:wangshuai date:20200601 for: 登录代码验证用户是否注销bug，if条件永远为false
		LambdaQueryWrapper<SysUser> queryWrapper = new LambdaQueryWrapper<>();
		queryWrapper.eq(SysUser::getUsername,username);
		SysUser sysUser = sysUserService.getOne(queryWrapper);

### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfWhere'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [java.lang.NullPointerException]
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92) ~[mybatis-spring-2.0.4.jar!/:2.0.4]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440) ~[mybatis-spring-2.0.4.jar!/:2.0.4]
        at com.sun.proxy.$Proxy156.selectList(Unknown Source) ~[?:?]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) ~[mybatis-spring-2.0.4.jar!/:2.0.4]
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:177) ~[mybatis-plus-core-3.3.2.jar!/:3.3.2]

**Comment by huayanYu** [comment]
无法复现，请自己简单。 或者提供复现的方式。 如已解决请回复原因。
