### ISSUE TITLE
3.4.2 Caused by: java.lang.ClassNotFoundException: com.baomidou.mybatisplus.extension.plugins.inner.InnerInterceptor

### ISSUE THREAD

**Issue by xieshenace** [baomidou/mybatis-plus#3534]
### 当前使用版本(必填,否则不予处理)
3.4.2（之前用的3.1是正常的，更新后就不正常了）
配置文件：
```
/**
 * @description: ㅤ
 * @author: Zek @Date: 2020/4/29 on 1:04 下午
 */
@Slf4j
@MapperScan(basePackages = {"cn.nocov.hospital.*.mapper"})
@Configuration
@EnableTransactionManagement
public class MybatisPlusConfig {

  @Bean
  public MybatisPlusInterceptor mybatisPlusInterceptor() {
    MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
    PaginationInnerInterceptor innerInterceptor = new PaginationInnerInterceptor();
    innerInterceptor.setDbType(DbType.MYSQL);
    interceptor.addInnerInterceptor(innerInterceptor);
    return interceptor;
  }
}
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
打包运行时

### 重现步骤(如果有就写完整)
打包运行时

### 报错信息
```
 Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [cn.nocov.hospital.payment.PaymentApplication]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class cn.nocov.hospital.common.config.MybatisPlusConfig
[2021-05-18 17:08:59][main][ERROR][org.springframework.boot.SpringApplication:826][][]
 Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [cn.nocov.hospital.payment.PaymentApplication]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class cn.nocov.hospital.common.config.MybatisPlusConfig
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:609)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:310)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at cn.nocov.hospital.payment.PaymentApplication.main(PaymentApplication.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class cn.nocov.hospital.common.config.MybatisPlusConfig
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:164)
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:402)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:325)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:599)
	... 25 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [cn.nocov.hospital.common.config.MybatisPlusConfig] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@37f8bb67]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:455)
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:153)
	... 29 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/extension/plugins/inner/InnerInterceptor
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
	... 31 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.baomidou.mybatisplus.extension.plugins.inner.InnerInterceptor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 35 common frames omitted
```

**Comment by nishimoguima** [comment]
ClassNotFoundException发生的原因与mybatisPlus无关，请自行检查依赖冲突等原因
