### ISSUE TITLE
容器化运行时Sequence.getLocalHost无法获取IP地址导致UnknownHostException

### ISSUE THREAD

**Issue by cxdbq2012** [baomidou/mybatis-plus#3692]
### 当前使用版本(必填,否则不予处理)
3.4.3
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.4.3</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
新版本同样有

本地运行不存在这个问题，能够正常获取IP，在测试服务器运行，应用在容器中，会遇到无法获取IP地址的情况。
最终导致如下异常

Caused by: java.net.UnknownHostException: B4-JLTEST-10: 系统错误
        
经过跟踪代码发现如下问题：

![image](https://user-images.githubusercontent.com/3038777/124097834-87978f00-da8e-11eb-86ac-badc99ca87d7.png)

![image](https://user-images.githubusercontent.com/3038777/124097913-9f6f1300-da8e-11eb-9231-eeb20b7c6812.png)

![image](https://user-images.githubusercontent.com/3038777/124097950-a7c74e00-da8e-11eb-82f6-2d0b6348a64b.png)

![image](https://user-images.githubusercontent.com/3038777/124097982-b1e94c80-da8e-11eb-8245-68438fccbc37.png)

### 报错信息

Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: java.net.UnknownHostException: B4-JLTEST-10: B4-JLTEST-10: 系统错误
        at com.baomidou.mybatisplus.core.toolkit.Sequence.getLocalHost(Sequence.java:100)
        at com.baomidou.mybatisplus.core.toolkit.Sequence.<init>(Sequence.java:85)
        at com.baomidou.mybatisplus.core.incrementer.DefaultIdentifierGenerator.<init>(DefaultIdentifierGenerator.java:39)
        at com.baomidou.mybatisplus.core.toolkit.IdWorker.<clinit>(IdWorker.java:38)
        ... 83 common frames omitted
Caused by: java.net.UnknownHostException: B4-JLTEST-10: B4-JLTEST-10: 系统错误
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at com.baomidou.mybatisplus.core.toolkit.Sequence.getLocalHost(Sequence.java:98)
        ... 86 common frames omitted
Caused by: java.net.UnknownHostException: B4-JLTEST-10: 系统错误
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 87 common frames omitted

**Comment by qmdx** [comment]
请关注 3.4.3.2 发布 https://gitee.com/baomidou/mybatis-plus/commit/f63065270cf62b87104cf9d84a2eacbde3a7da61
