### ISSUE TITLE
3.4.3.1版本ReflectionKit.getSuperClassGenericType方法不兼容

### ISSUE THREAD

**Issue by Surrin1999** [baomidou/mybatis-plus#3725]
### 当前使用版本(必填,否则不予处理)
mybatis-plus 3.4.3.1
mybatis-plus-generator 3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
mapper代理类生成直接失败，切换回3.4.3版本就可以

### 报错信息
<pre>
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.surrin.ssm.service.impl.DeptServiceImpl]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.toolkit.ReflectionKit.getSuperClassGenericType(Ljava/lang/Class;I)Ljava/lang/Class;
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1308)
	... 40 more
Caused by: java.lang.NoSuchMethodError: com.baomidou.mybatisplus.core.toolkit.ReflectionKit.getSuperClassGenericType(Ljava/lang/Class;I)Ljava/lang/Class;
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.currentModelClass(ServiceImpl.java:87)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.<init>(ServiceImpl.java:61)
	at cn.surrin.ssm.service.impl.DeptServiceImpl.<init>(DeptServiceImpl.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212)
	... 42 more
</pre>

**Comment by qmdx** [comment]
请给出重现 demo

**Comment by qmdx** [comment]
版本 `3.4.3.2` 已发布，请升级验证修复该问题，有任何问题 issue 该问题关闭！
