### ISSUE TITLE
新版3.4.3当在serviceImpl中间加一层继承时启动报错

### ISSUE THREAD

**Issue by lyq0205** [baomidou/mybatis-plus#3771]
### 当前使用版本(必填,否则不予处理)
3.4.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/19677772/126768095-f8b46ee7-f6cb-4aeb-84a8-3317d35cade7.png)
![image](https://user-images.githubusercontent.com/19677772/126768300-5c976f60-1838-4a5b-a590-1518e585b7fa.png)

### 重现步骤(如果有就写完整)
当代码中有自己类的继承时启动报错

### 报错信息

Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.currentModelClass(ServiceImpl.java:88)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.<init>(ServiceImpl.java:62)
	at com.tellhow.core.service.impl.BaseServiceImpl.<init>(BaseServiceImpl.java:21)
	at com.tellhow.sys.modules.sys.user.service.impl.SysUserServiceImpl.<init>(SysUserServiceImpl.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
	... 40 common frames omitted

**Comment by nancheung97** [comment]
升级到最新版

**Comment by huayanYu** [comment]
3.4.3.1
