### ISSUE TITLE
3.4.2升级到3.4.3.2后selectOne报Invalid bound statement (not found)

### ISSUE THREAD

**Issue by yujian340** [baomidou/mybatis-plus#3855]
### 当前使用版本(必填,否则不予处理)
3.4.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.2升级到3.4.3.2
3.4.2可正常使用

### 重现步骤(如果有就写完整)
SqlSessionFactory用的MybatisSqlSessionFactoryBean、MybatisConfiguration

BaseMapper继承com.baomidou.mybatisplus.core.mapper.Mapper
接口：T selectOne(@Param("ew") Wrapper<T> queryWrapper);

QueryWrapper<SysUserInfo> queryWrapper = new QueryWrapper<>();
queryWrapper.eq("user_name", userName);
return Optional.ofNullable(userInfoMapper.selectOne(queryWrapper));

### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.testDemo.mybatisDemo.mapper.UserInfoMapper.selectOne
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.<init>(MybatisMapperMethod.java:50)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.lambda$cachedInvoker$0(MybatisMapperProxy.java:111)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.baomidou.mybatisplus.core.toolkit.CollectionUtils.computeIfAbsent(CollectionUtils.java:115)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.cachedInvoker(MybatisMapperProxy.java:98)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy111.selectOne(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy112.selectOne(Unknown Source)
	at com.testDemo.mybatisDemo.service.impl.UserServiceImpl.findByUsername(UserServiceImpl.java:210)

**Comment by nieqiurong** [comment]
3.4.3.2取消了SelectOne注入,改成了default方法.
如果是自定义的BaseMapper就要去同步下逻辑或者自定义方法注入把SelectOne注入进去.
[精简 mapper 方法注入，优化 selectOne 查询方式](https://github.com/baomidou/mybatis-plus/commit/3f814124e3ea87356142ca7d12c8865954b13d08)
