### ISSUE TITLE
removeByIds方法报错

### ISSUE THREAD

**Issue by orchjoe** [baomidou/mybatis-plus#3874]
### 当前使用版本(必填,否则不予处理)
v3.4.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
应该是更新版本后更新方法deleteById 引起的

### 重现步骤(如果有就写完整)
v3.4.3.2
List<String> idList = Lists.newArrayList(idArray);
removeByIds(idList);
报错
v3.4.2
是可以的

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'id' in 'class java.lang.String'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy136.delete(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:304)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:69)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy170.deleteBatchIds(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by weishd** [comment]
一样的问题。怎么解决呢

**Comment by xcxzzx-1** [comment]
已经修复了，参见PR 修复 removeByIds方法报错 #3878

**Comment by weishd** [comment]
> 已经修复了，参见PR 修复 removeByIds方法报错 #3878

请问版本什么时候出来呢，可以更新。

**Comment by xcxzzx-1** [comment]
> > 已经修复了，参见PR 修复 removeByIds方法报错 #3878
> 
> 请问版本什么时候出来呢，可以更新。

我提了pr，不知道会不会合并呢

**Comment by ilaotan** [comment]
这个错简直是炸弹.. 哎 回滚了,不赶时髦了

**Comment by qmdx** [comment]
已发布 `3.4.3.3` 欢迎尝鲜
