### ISSUE TITLE
升级3.4.3.3启动报错，缺少org.springframework.cloud.commons.util.InetUtils

### ISSUE THREAD

**Issue by tomatoTed** [baomidou/mybatis-plus#3910]
### 当前使用版本(必填,否则不予处理)
mybatis-plus: 3.4.3.3
jdk: 16

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动时报错，缺少org.springframework.cloud.commons.util.InetUtils类

### 重现步骤(如果有就写完整)
启动时会出现

### 报错信息
Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/commons/util/InetUtils
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2446)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.commons.util.InetUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 18 common frames omitted

**Comment by 986510453** [comment]
已修复 #3890

**Comment by Robert-PF** [comment]
升级到了3.4.3.4 也报这个错，
<img width="247" alt="image" src="https://github.com/user-attachments/assets/b44b3576-f87e-4975-accb-25740e44a367">
spring-cloud-common包用的是3.0.4
