### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil

### ISSUE THREAD

**Issue by chenhl05** [baomidou/mybatis-plus#3995]
### 当前使用版本(必填,否则不予处理)
3.4.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
偶然后会出现，出现之后就一直会报错，重启之后过5天左右又会出现

### 重现步骤(如果有就写完整)
非必然出现

### 报错信息
Caused by: java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:92)
	at com.sun.proxy.$Proxy90.myMethodC(Unknown Source)
	at com.xxxx.xxxx.service.impl.UserServiceImpl.myMethodA(UserServiceImpl.java:441)
	at com.xxxx.xxxx.service.impl.UserServiceImpl.myMethodB(UserServiceImpl.java:429)
	at com.xxxx.xxxx.service.impl.UserServiceImpl$$FastClassBySpringCGLIB$$f928a5f2.invoke(<generated>)

**Comment by qmdx** [comment]
无法定位

**Comment by guanqing7011** [comment]
同样出现相同问题  版本 3.4.2  重启之后就好了   是否会再次出现不定

堆栈信息
Caused by: java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:92)
	at com.sun.proxy.$Proxy132.selectOrderListByForm(Unknown Source)
	at com.wolwo.manage.app.service.impl.DrugOrderServiceImpl.pageOrder(DrugOrderServiceImpl.java:80)
	at com.wolwo.manage.app.service.impl.DrugOrderServiceImpl$$FastClassBySpringCGLIB$$61e80eb5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.wolwo.manage.app.service.impl.DrugOrderServiceImpl$$EnhancerBySpringCGLIB$$f9e4b179.pageOrder(<generated>)
	at com.wolwo.manage.api.controller.DrugOrderController.page(DrugOrderController.java:48)
	at sun.reflect.GeneratedMethodAccessor380.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	... 52 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.ibatis.reflection.ExceptionUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 70 common frames omitted

**Comment by cc-Liu** [comment]
我也是出现同样的问题，偶尔打包部署后会出现这种问题，重新打包即可解决
Caused by: java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:92)
        at com.sun.proxy.$Proxy182.chargebackRecordList(Unknown Source)
        at com.furen.order.core.service.impl.TChargebackServiceImpl.chargebackRecordList(TChargebackServiceImpl.java:81)
        at com.furen.order.core.service.impl.TChargebackServiceImpl$$FastClassBySpringCGLIB$$c7dd349b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at com.furen.order.core.service.impl.TChargebackServiceImpl$$EnhancerBySpringCGLIB$$10d40b39.chargebackRecordList(<generated>)
        at com.furen.order.core.controller.TChargebackController.chargebackRecordList(TChargebackController.java:36)
        at sun.reflect.GeneratedMethodAccessor1789.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
