### ISSUE TITLE
Java花括号语法糖中调用Model中的Select方法导致连接池无法释放

### ISSUE THREAD

**Issue by masteranthoneyd** [baomidou/mybatis-plus#402]
偶然发现这个神奇的事情...
MP版本：`gamma`
SB版本：`2.0.3.RELEASE`

核心代码：
```
@GetMapping("/jdbc")
public TestVo jdbcTest() {
	return new TestVo() {{
		setActivity(this.selectById(6666L)); //这里的this指向TestVo
	}};
}

@Data
@Accessors(chain = true)
public static class TestVo extends FlashSale{
	private FlashSale activity;

}

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class FlashSale extends Model<FlashSale> {

    private static final long serialVersionUID = 1L;

    private Long id;
}
```

访问`/jdbc`，到达链接池上限之后（我这里设置为10），抛出如下异常：
```
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:338) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.6.jar:3.4.6]
	... 85 more
```
链接无法释放，通过ServiceImpl查询是OK的，就是Model会有这个问题...

**Comment by qmdx** [comment]
关注最新版本发布以优化
