### ISSUE TITLE
配置多数据源后自动填充失效

### ISSUE THREAD

**Issue by MrCloudsman** [baomidou/mybatis-plus#4213]
### 当前使用版本(必填,否则不予处理)
3.0.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
单数据源配置MetaObjectHandler后可以自动填充，配置两个数据源后无法填充，SqlSessionFactory中加入相关配置，无法启动，去掉后正常启动，但是无法自动填充
       `MybatisSqlSessionFactoryBean sqlSessionFactory = new MybatisSqlSessionFactoryBean();
        GlobalConfig globalConfig=new GlobalConfig();
        globalConfig.setMetaObjectHandler(new MyMetaObjectHandler());
        sqlSessionFactory.setGlobalConfig(globalConfig);`

### 报错信息
`Caused by: java.lang.NullPointerException: null
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:603)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:398)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:687)`

**Comment by MrCloudsman** [comment]
resolved
