### ISSUE TITLE
3.4.3.1及其以上版本 依赖于Spring-core，无法脱离Spring使用

### ISSUE THREAD

**Issue by jvbac123** [baomidou/mybatis-plus#4223]
### 当前使用版本(必填,否则不予处理)
3.4.3.1及其以上版本
3.4.3不会
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
启动
### 重现步骤(如果有就写完整)
直接通过 java 代码 创建DataSource  然后
创建Environment ，然后 创建MybatisConfiguration 
在MybatisConfiguration  中 addMapper
### 报错信息
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/GenericTypeResolver
	at com.baomidou.mybatisplus.core.toolkit.ReflectionKit.getSuperClassGenericType(ReflectionKit.java:97)
	at com.baomidou.mybatisplus.core.injector.AbstractSqlInjector.inspectInject(AbstractSqlInjector.java:43)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parserInjector(MybatisMapperAnnotationBuilder.java:131)
	at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:121)
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:83)
	at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:119)

**Comment by jptx1234** [comment]
升级到3.5.0

**Comment by qmdx** [comment]
up

**Comment by leezicai** [comment]
使用3.5版本 implementation 'com.baomidou:mybatis-plus:3.5.3.1', 不使用sprintboot
也会有这样的问题

**Comment by leezicai** [comment]
> 

要使用3.5.3.1 也要添加spring 进来, 以gradle 示例.
3.4.3 的lambda 表达式有问题, 使用3.5.3.1 就成了必须的了.
```
implementation 'com.baomidou:mybatis-plus:3.5.3.1'
implementation 'org.springframework:spring-core:6.0.7' 
```
