### ISSUE TITLE
批量插入时报错类型转换异常

### ISSUE THREAD

**Issue by tangjian335** [baomidou/mybatis-plus#4229]
### 当前使用版本(必填,否则不予处理)
3.3.2及以上

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
项目原来只使用了mybatis，后面为了简化开发引入了mybatis plus,在执行一个批量插入的方法时，报错类型转换错误。经排查，在
com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler#getParameters方法里面，因为参数的名字是list，但实际传入的是一个非list的Collection，导致强转时出现异常。

### 重现步骤(如果有就写完整)
批量插入或者批量更新时，参数定义为@Param("list") Collection list,在执行的时候报类型转换错误

### 报错信息
Caused by: java.lang.ClassCastException: java.util.HashMap$Values cannot be cast to java.util.List
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.getParameters(MybatisDefaultParameterHandler.java:140)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.processParameter(MybatisDefaultParameterHandler.java:79)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.(MybatisDefaultParameterHandler.java:55)
	at com.baomidou.mybatisplus.core.MybatisXMLLanguageDriver.createParameterHandler(MybatisXMLLanguageDriver.java:34)
	at com.baomidou.mybatisplus.core.MybatisXMLLanguageDriver.createParameterHandler(MybatisXMLLanguageDriver.java:28)
	at org.apache.ibatis.session.Configuration.newParameterHandler(Configuration.java:579)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.(BaseStatementHandler.java:69)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.(PreparedStatementHandler.java:41)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.(RoutingStatementHandler.java:46)
	at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:592)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:52)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83)

**Comment by mabyoung** [comment]
@tangjian335 您好，方便提过一下完整的demo，或者贴一下关键的使用截图吗

**Comment by tangjian335** [comment]
@mabyoung 我写了个demo，其中User不是mybatis plus管理的类；
![image](https://user-images.githubusercontent.com/24770227/149082586-cef33a4e-3f1a-42b6-948d-c56f1f97854c.png)
![image](https://user-images.githubusercontent.com/24770227/149082619-4e493ed4-db14-4edd-ae82-e3bc185e6513.png)

**Comment by mabyoung** [comment]
您可以改成这样试试：
int batchInsert(@Param("list") List<User> list);
<insert id='batchInsert'>
    insert into user(id, name, gender, role_name)
    VALUES
    <foreach collection="list" item="item" separator=",">
        (#{item.id},#{item.name},#{item.gender},#{item.roleName})
    </foreach>
</insert>

**Comment by tangjian335** [comment]
我知道怎么改是正确的，我只是觉得MybatisDefaultParameterHandler里面对参数的处理逻辑可以优化一下。我知道getParameter的本意是把mybatis放到map里面的集合参数给取出来，但是有可能map里面的参数不是wrappedCollection方法放进去的

**Comment by Sdky** [comment]
![image](https://user-images.githubusercontent.com/29597396/159395903-4b254a6f-4e0c-47ae-80a8-d31bbb42e20f.png)

com.baomidou.mybatisplus.core.MybatisParameterHandler#getParameters 方法，第 194 行，改为强转为 Collection，是不是就可以了？我看方法的返回值类型也是 Collection。

**Comment by VampireAchao** [comment]
既然`@Param`命名都叫`list`了，尽量还是传入`list`为好
