### ISSUE TITLE
DDL语句执行不了

### ISSUE THREAD

**Issue by chen-better-and-better** [baomidou/mybatis-plus#4315]
### 当前使用版本(必填,否则不予处理)
3.4.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
对Mysql数据源执行ALTER TABLE 语句时，报错Failed to process

### 重现步骤(如果有就写完整)
执行一个ALTER TABLE 语句

### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: ALTER TABLE chen_test_01 DROP day,CHANGE product_name product_name varchar (10),CHANGE num num bigint (10),CHANGE id id bigint (20)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy138.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)

**Comment by chen-better-and-better** [comment]
这里是Mapper方法：
	@InterceptorIgnore(illegalSql = "true", dynamicTableName = "true", blockAttack = "true")
	@Update("${sql}")
	void operateTable(@Param("sql") String sql);

**Comment by qmdx** [comment]
新版本将支持ddl执行  https://github.com/baomidou/mybatis-plus/commit/0c5704d6bfa2bf0fc97db673cacce0f30c4d5318
