### ISSUE TITLE
调用model.insert()方法报class must not be null

### ISSUE THREAD

**Issue by liufangpu** [baomidou/mybatis-plus#4318]
### 当前使用版本(必填,否则不予处理)
3.4.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

最新版3.5.1也有这个问题， 3.4.2就没这个问题，我从3.4.2升级到3.4.3.3后就开始出现

### 重现步骤(如果有就写完整)

entity 继承 Model然后调用 insert()方法出现这个错误

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Class must not be null
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49) ~[mybatis-plus-core-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.core.toolkit.Assert.isTrue(Assert.java:38) ~[mybatis-plus-core-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.core.toolkit.Assert.notNull(Assert.java:72) ~[mybatis-plus-core-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.core.toolkit.GlobalConfigUtils.currentSessionFactory(GlobalConfigUtils.java:53) ~[mybatis-plus-core-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.sqlSession(SqlHelper.java:86) ~[mybatis-plus-extension-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.extension.activerecord.Model.sqlSession(Model.java:248) ~[mybatis-plus-extension-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.extension.activerecord.Model.insert(Model.java:56) ~[mybatis-plus-extension-3.5.1.jar:3.5.1]

**Comment by miemieYaho** [comment]
代码呢

**Comment by VampireAchao** [comment]
麻烦提供一下测试用例，可以吗

**Comment by ethanbing** [comment]
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Class must not be null

我这边是用了多租户，看log 租户id已经拼接了但是查询还是报错
SELECT id, user_type, tenant_id, user_name, user_phone, user_nick, id_num, go_secret, role_ids, del_flag, gmt_create, gmt_update FROM admin_info WHERE del_flag = 0 AND (user_phone = '18518xxx') AND admin_info.tenant_id = 10000

**Comment by a386572631** [comment]
我也发现了，只要是.one()的没找到记录好像就会报，以前是会返回个null的。
3.5.3版本

**Comment by wheatmai** [comment]
> 我也发现了，只要是.one()的没找到记录好像就会报，以前是会返回个null的。 3.5.3版本

对，我也是 3.5.3, lambda使用one()时，如果没记录就报异常。BaseMapper的selectOne方法正常返回了Null，但后面那个包装方法里面wrapper的entityclass是空的

**Comment by nieqiurong** [comment]
> Reference in new issu

这个应该更新到3.5.3.1试试.

**Comment by bydongxing** [comment]
直接使用 QueryWrapper 也是同样的问题，版本是 3.5.3.1的
QueryWrapper entityWrapper = new QueryWrapper();
model.selectList(entityWrapper)；

**Comment by nieqiurong** [comment]
> 直接使用 QueryWrapper 也是同样的问题，版本是 3.5.3.1的 QueryWrapper entityWrapper = new QueryWrapper(); model.selectList(entityWrapper)；

还有问题就提供一个工程过来看看吧

![image](https://github.com/baomidou/mybatis-plus/assets/15142701/50e28560-3d6e-4afb-9b85-2e4fe727fdc5)

**Comment by honestAnt** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15356873/c6edb61c-730a-42a4-a774-7eefa27ee295)
![image](https://github.com/baomidou/mybatis-plus/assets/15356873/0d0d92d8-c517-4e64-b067-c74fb58665e7)
![image](https://github.com/baomidou/mybatis-plus/assets/15356873/0ae1230f-9983-4aed-b973-208c77c7952c)

![image](https://github.com/baomidou/mybatis-plus/assets/15356873/dd4ce2d4-6054-47ca-b4ca-7c1c289ef07b)
问题其实出现在 使用service的lambdaQuery()方法，该方法内部初始化entityClass的时候 把对象设置为 wrapperChildren 的属性了，外面的entityClass属性没设置，导致获取的时候为null ；建议官方在 LambdaQueryChainWrapper.getEntityClass()方法内部做个优化处理

**Comment by honestAnt** [comment]
或者升级到最新版本 3.5.3.2 已经修复了；
![image](https://github.com/baomidou/mybatis-plus/assets/15356873/4374307b-985d-49bd-a3b3-2efce3e48fc2)
