### ISSUE TITLE
db2-saveOrUpdateBatch 空指针问题

### ISSUE THREAD

**Issue by zhangchuangxx** [baomidou/mybatis-plus#4352]
### 当前使用版本(必填,否则不予处理)

3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

确定

### 重现步骤(如果有就写完整)

使用db2数据库 saveOrUpdateBatch（) 报空指针异常

### 报错信息

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: java.lang.NullPointerException

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:192)
	。。。。

**Comment by qmdx** [comment]
不确定是不是  db2 不支持批量操作 id 生成逻辑？
