### ISSUE TITLE
SpringBootTest 单元测试无法识别 mpw: 配置文件加密的 jdbc url

### ISSUE THREAD

**Issue by rockyyu66** [baomidou/mybatis-plus#4383]
### 当前使用版本(必填,否则不予处理)
<dependency>
	<groupId>com.baomidou</groupId>
	<artifactId>mybatis-plus-boot-starter</artifactId>
	<version>3.5.1</version>
</dependency>

Springboot 版本：2.5.10

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
@SpringBootTest 执行单元测试，向数据库插入一条数据。

### 报错信息
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.RuntimeException: Driver com.mysql.jdbc.Driver claims to not accept jdbcUrl, mpw:Fi0UC04R0svzvfbH7ndd2q9XXE7YwkA7H7KN5Qe6ettJGjrdUvOevBsCNVlwjl3uP0L8vw3kT5sZQ0FikYEgIGID3CMlORETAS9CW/15syLf4oEO0r5agRqyK28wNZeu6W9fX824c8nYWaP5d6ZZ60L3XqdEBsg0z23dsfsdf=
### The error may exist in com/fhs/server/dao/UserMapper.java (best guess)
### The error may involve com.fhs.server.dao.UserMapper.insert
### The error occurred while executing an update
### Cause: java.lang.RuntimeException: Driver com.mysql.jdbc.Driver claims to not accept jdbcUrl, mpw:Fi0UC04R0svzvfbH7ndd2q9XXE7YwkA7H7KN5Qe6ettJGjrdUvOevBsCNVlwjl3uP0L8vw3kT5sZQ0FikYEgIGID3CMlORETAS9CW/15syLf4oEO0r5agRqyK28wNZeu6W9fX824c8nYWaP5d6ZZ60L3XqdEBsg0z23dsfsdf=

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at jdk.proxy2/jdk.proxy2.$Proxy93.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:59)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy117.insert(Unknown Source)
	at com.fhs.server.FhsServerApplicationTests.userInsertTest(FhsServerApplicationTests.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by fortunateY** [comment]
I also encountered this problem, how should solve it？

**Comment by VampireAchao** [comment]
https://github.com/baomidou/mybatis-plus/issues/4417
