### ISSUE TITLE
SimpleQuery.list报错

### ISSUE THREAD

**Issue by sunran** [baomidou/mybatis-plus#4523]
### 当前使用版本(必填,否则不予处理)

jdk 17 ， 版本 mybatis-plus-boot-starter: 3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

List<Long> shopIdList = SimpleQuery.list(Wrappers.<UserShopRelDO>lambdaQuery().eq(UserShopRelDO::getUserId, UserContext.get()), UserShopRelDO::getShopId);

### 报错信息

java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class com.baomidou.mybatisplus.core.override.MybatisMapperProxyFactory (java.util.HashMap$Node is in module java.base of loader 'bootstrap'; com.baomidou.mybatisplus.core.override.MybatisMapperProxyFactory is in unnamed module of loader 'app')
	at com.baomidou.mybatisplus.core.MybatisMapperRegistry.getMapper(MybatisMapperRegistry.java:54) ~[mybatis-plus-core-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMapper(MybatisConfiguration.java:190) ~[mybatis-plus-core-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.getMapper(SqlHelper.java:315) ~[mybatis-plus-extension-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.extension.toolkit.SimpleQuery.selectList(SimpleQuery.java:323) ~[mybatis-plus-extension-3.5.1.jar:3.5.1]
	at com.baomidou.mybatisplus.extension.toolkit.SimpleQuery.list(SimpleQuery.java:141) ~[mybatis-plus-extension-3.5.1.jar:3.5.1]

**Comment by VampireAchao** [comment]
该问题已于版本`3.5.2`修复
