### ISSUE TITLE
当字段名长度为1的时候会字符串数组越界

### ISSUE THREAD

**Issue by xiaopeidesubaozi** [baomidou/mybatis-plus#4597]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
当字段名长度为1的时候会字符串数组越界

### 报错信息

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.baomidou.mybatisplus.core.toolkit.StringUtils.getTargetColumn(StringUtils.java:140)
	at com.baomidou.mybatisplus.core.metadata.TableInfoHelper.checkRelated(TableInfoHelper.java:478)

**Comment by miemieYaho** [comment]
比如呢?

**Comment by xiaopeidesubaozi** [comment]
![image](https://user-images.githubusercontent.com/61820462/174275723-a49c3abd-0320-4dcc-af72-ecd18d4dde9e.png)

**Comment by miemieYaho** [comment]
不支持非正经字段名
