### ISSUE TITLE
神通数据库insert报错

### ISSUE THREAD

**Issue by MdcGIt** [baomidou/mybatis-plus#4610]
神通数据库使用mp insert或者update都会报错,无法自增id,请问需要怎么配置呢, mybatis 使用useGeneratedKeys=false和selectKey搭配使用可以解决，mybatis-plus有没有类似的解决方案
错误信息:
org.springframework.jdbc.UncategorizedSQLException: Error getting generated key or setting result to parameter object. Cause: java.sql.SQLException: Error
; uncategorized SQLException; SQL state [null]; error code [0]; Error; nested exception is java.sql.SQLException: Error
 at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
 at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:192)
 at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:217)
 at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.executeBatch(ServiceImpl.java:240)
 at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveBatch(ServiceImpl.java:136)

**Comment by qmdx** [comment]
自定义 id 生成器 https://baomidou.com/pages/568eb2/ 或者使用自带的雪花算法，再或者你可以考虑重写注入 insert sql 部分逻辑
参考 https://baomidou.com/pages/42ea4a/

**Comment by Jean-Jacques-Nuoan** [comment]
> 自定义 id 生成器 https://baomidou.com/pages/568eb2/ 或者使用自带的雪花算法，再或者你可以考虑重写注入 insert sql 部分逻辑 参考 https://baomidou.com/pages/42ea4a/

404了
