### ISSUE TITLE
关于spring boot项目IDEA启动没问题 打成jar后启动报错

### ISSUE THREAD

**Issue by Alexonylll** [baomidou/mybatis-plus#465]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus 3.0.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
spring boot项目打成jar包之后引起的

### 重现步骤
我在spring boot的配置中设置了MybatisSqlSessionFactoryBean的TypeAliasesPackage属性后xml里面没有写全名 IDEA开发工具启动后无异常  但是项目打成jar包后 启动会报错说找不到那个类 填写全名就可以了
(我的配置是通过类来配置 并非通过yml或者properties文件配置让spring自己配置的)

### 报错信息
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'class path resource [mapper/auction/SysUserMapper.xml]'. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'SysUser'.  Cause: java.lang.ClassNotFoundException: Cannot find class: SysUser
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120)
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
        at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:632)
        ... 132 common frames omitted
Caused by: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'SysUser'.  Cause: java.lang.ClassNotFoundException: Cannot find class: SysUser
        at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:118)
        at org.apache.ibatis.builder.xml.XMLStatementBuilder.parseStatementNode(XMLStatementBuilder.java:68)
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:135)
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:128)
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:118)
        ... 134 common frames omitted
Caused by: org.apache.ibatis.type.TypeException: Could not resolve type alias 'SysUser'.  Cause: java.lang.ClassNotFoundException: Cannot find class: SysUser
        at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:120)
        at org.apache.ibatis.builder.BaseBuilder.resolveAlias(BaseBuilder.java:149)
        at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:116)
        ... 138 common frames omitted
Caused by: java.lang.ClassNotFoundException: Cannot find class: SysUser
        at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:200)
        at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:89)
        at org.apache.ibatis.io.Resources.classForName(Resources.java:261)
        at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:116)
        ... 140 common frames omitted

**Comment by miemieYaho** [comment]
开发期间能用,打成jar包就不行了,这也怪我们吗?
