### ISSUE TITLE
java.util.ConcurrentModificationException异常

### ISSUE THREAD

**Issue by fahualei** [baomidou/mybatis-plus#4666]
### 当前使用版本(必填,否则不予处理)
3.5.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
该异常为偶发，主要是进行大量多次综合业务查询请求（7张表数据），单次前端接口请求最多包含3张表，且并未做left join，而是依次查询代码组合。异常出现在很多普通查询，批量查询，对象为属性为常规varchar，bigint，int类型，也有部分对象包含json类型属性（采用数组接收）。

### 报错信息

异常随机出现在某次查询：
### Cause: java.util.ConcurrentModificationException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy167.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy168.selectBatchIds(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.listByIds(IService.java:301)
	at com.baomidou.mybatisplus.extension.service.IService$$FastClassBySpringCGLIB$$f8525d18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.**.dao.repository.impl.ProductAttributeRepositoryImpl$$EnhancerBySpringCGLIB$$2b863b04.listByIds(<generated>)
	at com.**.service.ProductContactAttributeService.listByCondition(ProductContactAttributeService.java:329)

### Cause: java.util.ConcurrentModificationException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy167.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy178.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:370)
	at com.**.dao.repository.impl.ProductContactAttributeRepositoryImpl.listByProductIdAndAttributeTypeAndBackup(ProductContactAttributeRepositoryImpl.java:113)
	at com.**.dao.repository.impl.ProductContactAttributeRepositoryImpl$$FastClassBySpringCGLIB$$5fbbd7f6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.**.dao.repository.impl.ProductContactAttributeRepositoryImpl$$EnhancerBySpringCGLIB$$596207e4.listByProductIdAndAttributeTypeAndBackup(<generated>)
	at com.**.service.ProductContactAttributeService.listByCondition(ProductContactAttributeService.java:322)

**Comment by miemieYaho** [comment]
你有排查过是不是你的代码问题吗?有了解`java.util.ConcurrentModificationException`这是什么异常吗?

**Comment by fahualei** [comment]
当然了解了这个异常，java中集合相关的异常，正因为如此该异常由框架抛出来的，且注意是sql查询执行时抛出，单次接口代码是没有问题，逻辑并不复杂，且做过并发。综合多个接口还在排查，这相当异步了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月22日(周五) 中午11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baomidou/mybatis-plus] java.util.ConcurrentModificationException异常 (Issue #4666)




 
你有排查过是不是你的代码问题吗?有了解java.util.ConcurrentModificationException这是什么异常吗?

**Comment by miemieYaho** [comment]
框架又不会对集合内元素进行删改

**Comment by fahualei** [comment]
结果集不是框架返回吗？异常就是映射结果集报错了呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月22日(周五) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baomidou/mybatis-plus] java.util.ConcurrentModificationException异常 (Issue #4666)




 
框架又不会对集合内元素进行删改

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/180387743-9495f7c4-d2ae-408d-89c4-e4551f47e2f7.png)

**Comment by fahualei** [comment]
这个有啥问题呢？一个传参而已，也是框架提供的传批量id查询。你不会觉得我把传入的集合进行修改吧。这没有的，不过我用的Arrays.asList包装的集合传入



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月22日(周五) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baomidou/mybatis-plus] java.util.ConcurrentModificationException异常 (Issue #4666)

**Comment by miemieYaho** [comment]
数据封装和sq执行的活都是mybatis在干,你觉得会有问题吗?

**Comment by fahualei** [comment]
不好意思~我排查到了问题，是自定义了实现org.apache.ibatis.logging.Log这个日志打印，有集合操作。
