### ISSUE TITLE
逻辑删除开启，3.5.2版本removeByIds抛出异常，无法正确执行

### ISSUE THREAD

**Issue by DevForJava** [baomidou/mybatis-plus#4752]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
版本由3.4.3.4升级至3.5.2
开启了逻辑删除
IService中default boolean removeByIds(Collection<? extends Serializable> idList)调用时传入List《String》ids主键数组，对应的Entity ID主键为Long类型，抛出异常

### 重现步骤(如果有就写完整)
3.5.0开始3.5.1，3.5.2三个版本均出现同样错误

### 报错信息
Exception:MybatisPlusException: java.lang.IllegalArgumentException: java.lang.ClassCastException@31dcf00f - IllegalArgumentException: java.lang.ClassCastException@31dcf00fjava.lang.IllegalArgumentException: java.lang.ClassCastException@31dcf00f
出错位置为
　　at com.baomidou.mybatisplus.core.metadata.TableInfo.setPropertyValue(TableInfo.java:546)
　　at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.lambda$removeBatchByIds$4(ServiceImpl.java:309)
　　at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.lambda$executeBatch$1(SqlHelper.java:222)

**Comment by miemieYaho** [comment]
` removeByIds(idList,false)`

**Comment by DevForJava** [comment]
> ` removeByIds(idList,false)`

多谢，解决了

**Comment by xhc-code** [comment]
> removeByIds

我也出现这个问题了，为什么会出现啊？改动的地方太多了
