### ISSUE TITLE
No typehandler found for property xxx

### ISSUE THREAD

**Issue by mostcool** [baomidou/mybatis-plus#4765]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Entity的某个属性上配置了typeHandler=JacksonTypeHandler.class
```java

    @TableField(typeHandler = JacksonTypeHandler.class)
    private List<String> xxx;

```
启动程序，报错：
```java

java.lang.IllegalStateException: No typehandler found for property xxx

```

### 报错信息
```java

Caused by: java.lang.IllegalStateException: No typehandler found for property xxx
	at org.apache.ibatis.mapping.ResultMapping$Builder.validate(ResultMapping.java:151)
	at org.apache.ibatis.mapping.ResultMapping$Builder.build(ResultMapping.java:140)
	at org.apache.ibatis.builder.MapperBuilderAssistant.buildResultMapping(MapperBuilderAssistant.java:446)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildResultMappingFromContext(XMLMapperBuilder.java:393)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:280)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:254)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElements(XMLMapperBuilder.java:246)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:119)
	... 71 common frames omitted

```

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/TableField.java
