### ISSUE TITLE
字段使用了Typehandler通过Wrapper update该字段时不生效

### ISSUE THREAD

**Issue by Jovons** [baomidou/mybatis-plus#4789]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
LambdaUpdateWrapper 更新字段A，A通过注解使用了TypeHandler，在调用IService接口的update接口的A字段，TypeHandler不生效。

### 重现步骤(如果有就写完整)
```
@Service
public class NodeDaoManagerImpl extends ServiceImpl<NodeMapper, NodeDO> implements NodeDaoManager {
    public boolean updateNodeTagChainById(NodeDO parent, NodeDO child) {
        LambdaUpdateWrapper<NodeDO> updateWrapper = Wrappers.<NodeDO>lambdaUpdate();
        updateWrapper.eq(NodeDO::getId, child.getId())
                .set(NodeDO::getTagChain, tagChain);
        boolean result = this.update(child, updateWrapper);
        return result;
    }
}
```

```
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName(value = "node", autoResultMap = true)
public class NodeDO extends Model<NodeDO> implements DOBase{
         @TableField(typeHandler = TagChainTypeHandler.class, jdbcType = JdbcType.VARCHAR)
         private List<Integer> tagChain;
}
```
```
@MappedTypes({List.class})
@MappedJdbcTypes(JdbcType.VARCHAR)
public class TagChainTypeHandler extends BaseTypeHandler<List<Integer>> {
    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, List<Integer> parameter, JdbcType jdbcType) throws SQLException {
        ps.setString(i, StrUtil.join("-", parameter));
    }
```

### 报错信息

下面的错误信息，是因为存的字符串ArrayList... Java的toString
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'tag_chain' at row 1
### The error may exist in com/industry/tree/dao/mapper/NodeMapper.java (best guess)
### The error may involve com.industry.tree.dao.mapper.NodeMapper.update-Inline
### The error occurred while setting parameters
### SQL: UPDATE node  SET tag=?,    branch_name=?, project_id=?, parent_id=?, longitude=?, latitude=?, location=?, create_time=?, update_time=?,  tag_chain=?    WHERE  deleted=0  AND (id = ?)
### Cause: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'tag_chain' at row 1
; uncategorized SQLException; SQL state [HY000]; error code [1366]; Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'tag_chain' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'tag_chain' at row 1
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.1.6.Final.jar:2.1.6.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.1.6.Final.jar:2.1.6.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.1.6.Final.jar:2.1.6.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.1.6.Final.jar:2.1.6.Final]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.1.6.Final.jar:2.1.6.Final]
```

**Comment by Jovons** [comment]
知道原因了。在3.5.2版本里才可以用wrapper的set方法让更新的字段typeHandler生效；3.5.2之前的版本，需要更新bean的这个字段。即nodeDO.setTagChain

**Comment by 0501wenjie** [comment]
我从3.3.2改成3.5.2，直接项目闪退，没有任务报错，从nacos拉完配置，直接"exit" ：），有人遇到一样的情况吗

**Comment by gm100861** [comment]
> 

我升级到了3.5.2, 一样不生效.
