### ISSUE TITLE
mybatisplus对fastjson2的支持

### ISSUE THREAD

**Issue by 274574162** [baomidou/mybatis-plus#4801]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
fastjson 依赖升级到fastjson2

### 报错信息

Caused by: java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
	at com.baomidou.mybatisplus.extension.handlers.FastjsonTypeHandler.parse(FastjsonTypeHandler.java:48)
	at com.baomidou.mybatisplus.extension.handlers.AbstractJsonTypeHandler.getNullableResult(AbstractJsonTypeHandler.java:41)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:85)

**Comment by huayanYu** [comment]
自己改一下就好了。
