### ISSUE TITLE
 Encountered unexpected token: "MEMBER" 

### ISSUE THREAD

**Issue by lovlyhao** [baomidou/mybatis-plus#4816]
### 当前使用版本(必填,否则不予处理)

version: 3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

.apply(" '{0}' MEMBER OF (cxr_post_id->'$.value') ", PostType.RESERVE_DIRECTOR.getValue())

### 重现步骤(如果有就写完整)
使用mysql8 member of 语法

### 报错信息

aused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT  
 id,cxr_employee_id,cxr_post_id,cxr_site_id,cxr_region_id,in_charge_start_time,in_charge_end_time,charge_status,create_by,create_time,update_by,update_time,revision,create_by_name,create_by_type,update_by_name,update_by_type,delete_by,delete_by_name,delete_by_type,delete_time,delete_status,sort_num,remark,sys_dept_id,spare_id 
  FROM cxr_employee_post      

 
 WHERE (cxr_employee_id IN (?,?,?,?,?,?,?,?) AND  '?' MEMBER OF (cxr_post_id->'$.value') )
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
	at com.ruoyi.common.mybatis.interceptor.PlusDataPermissionInterceptor.beforeQuery(PlusDataPermissionInterceptor.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy351.query(Unknown Source)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:111)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy351.query(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.github.yulichang.interceptor.MPJInterceptor.intercept(MPJInterceptor.java:82)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy351.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 64 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "MEMBER" <S_IDENTIFIER>
    at line 6, column 55.

Was expecting one of:

    "&"
    ")"
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:31468)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:31301)
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:9750)
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:9696)
	at net.sf.jsqlparser.parser.CCJSqlParser.XorExpression(CCJSqlParser.java:9678)
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:9649)
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:9037)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:5667)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:5867)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:5516)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:5511)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:232)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:153)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:188)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:49)
	... 80 common frames omitted

**Comment by miemieYaho** [comment]
jsqlparser 不支持解析

**Comment by qmdx** [comment]
https://baomidou.com/pages/223848/#interceptorignore  忽略方法对应异常拦截器
