### ISSUE TITLE
MybatisPlusAutoConfiguration 中启动报告 java.lang.NullPointerException

### ISSUE THREAD

**Issue by chings** [baomidou/mybatis-plus#492]
### 当前使用版本(必须填写清楚，否则不予处理)
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.0.2</version>
            </dependency>

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
mybatis-plus/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java中

`    private void applyConfiguration(MybatisSqlSessionFactoryBean factory) {
        MybatisConfiguration configuration = this.properties.getConfiguration();
        if (configuration == null && !StringUtils.hasText(this.properties.getConfigLocation())) {
            configuration = new MybatisConfiguration();
        }

        if (configuration != null && !CollectionUtils.isEmpty(this.configurationCustomizers)) {
            Iterator var3 = this.configurationCustomizers.iterator();

            while(var3.hasNext()) {
                ConfigurationCustomizer customizer = (ConfigurationCustomizer)var3.next();
                customizer.customize(configuration);
            }
        }

        if (null != configuration) {
            configuration.setDefaultScriptingLanguage(MybatisXMLLanguageDriver.class);
        }

        //此处仍然可能会报告Null指针异常
        factory.setConfiguration(configuration.printBanner(this.properties.getGlobalConfig().isBanner()));
    }`

### 重现步骤
application.yml中设置
mybatis-plus:
  config-location: classpath:mybatis-config.xml

工程启动报错

### 报错信息
Caused by: java.lang.NullPointerException
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.applyConfiguration(MybatisPlusAutoConfiguration.java:189)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:121)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$e382760f.CGLIB$sqlSessionFactory$0(<generated>)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$e382760f$$FastClassBySpringCGLIB$$41785881.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$e382760f.sqlSessionFactory(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 67 more

**Comment by vindell** [comment]
遇到同样问题;

    private void applyConfiguration(MybatisSqlSessionFactoryBean factory) {
        **MybatisConfiguration configuration = this.properties.getConfiguration();**  
        if (configuration == null && !StringUtils.hasText(this.properties.getConfigLocation())) {
            configuration = new MybatisConfiguration();
        }
        if (configuration != null && !CollectionUtils.isEmpty(this.configurationCustomizers)) {
            for (ConfigurationCustomizer customizer : this.configurationCustomizers) {
                customizer.customize(configuration);
            }
        }
        // TODO 自定义配置
        if (null != configuration) {
            configuration.setDefaultScriptingLanguage(MybatisXMLLanguageDriver.class);
        }
        factory.setConfiguration(configuration.init(this.properties.getGlobalConfig()));
    }

作者是否这里逻辑是否有点问题，如果只用外部配置，这个对象是为空的

**Comment by chings** [comment]
https://github.com/baomidou/mybatis-plus/issues/255

类似的问题几个月前已经报告过，似乎不太被重视……

**Comment by jonerxq** [comment]
最新的版本还是有问题3.03还是有问题！我也碰到了

**Comment by miemieYaho** [comment]
使用 `3.0.5-SNAPSHOT` 版本

**Comment by qmdx** [comment]
如上
