### ISSUE TITLE
删除数据时锁表了

### ISSUE THREAD

**Issue by kiwi-field** [baomidou/mybatis-plus#4973]
### 当前使用版本(必填,否则不予处理)
3.2.0

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
执行以下代码
         LambdaQueryWrapper<TaskDataSource> eq = new LambdaQueryWrapper<TaskDataSource>()
         .eq(TaskDataSource::getTaskId, taskId);
         taskDatasourceService.remove(eq);
执行的sql是
UPDATE t_vi_task_datasource SET deleted=1   WHERE  deleted=0  AND (task_id = ?)

### 重现步骤(如果有就写完整)
使用了动态数据源   dynamic-datasource-spring-boot-starter的注解 @DSTransactional

### 报错信息

SQL: UPDATE t_vi_task_datasource SET deleted=1   WHERE  deleted=0  AND (task_id = ?)
Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
; Lock wait timeout exceeded; try restarting transaction; nested exception is com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException:
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:267)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:74)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy137.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:63)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy249.delete(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.remove(ServiceImpl.java:197)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)

**Comment by miemieYaho** [comment]
和mp无关
