### ISSUE TITLE
为升级springboot3.0.0将mybatisplus升级到3.5.2.7-SNAPSHOT后报错：java.lang.NoClassDefFoundError: org/springframework/core/NestedIOException

### ISSUE THREAD

**Issue by arygos** [baomidou/mybatis-plus#4988]
### 当前使用版本(必填,否则不予处理)
3.5.2.7-SNAPSHOT

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
springboot程序升级到3.0.0版本后，启动程序时报错

### 报错信息
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/NestedIOException
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:164) ~[mybatis-plus-boot-starter-3.5.2.7-20221129.052155-1.jar:3.5.2.7-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.2.jar:6.0.2]
	... 71 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.core.NestedIOException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 77 common frames omitted
![image](https://user-images.githubusercontent.com/33365031/205422898-d2cb6fd7-cb8f-45b3-8872-b896dc285424.png)

**Comment by arygos** [comment]
**新的问题：**
Caused by: java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/core/handlers/JoinTableInfoInitHandler
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:212) ~[mybatis-plus-boot-starter-3.5.2.7-20221129.052155-1.jar:3.5.2.7-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.2.jar:6.0.2]
	... 71 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.baomidou.mybatisplus.core.handlers.JoinTableInfoInitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 77 common frames omitted

**Comment by xingyuv** [comment]
将MybatisSqlSessionFactoryBean 复制出来一份，把 NestedIOException  替换成 IOException

**Comment by miemieYaho** [comment]
jar包拉取到盗版去了吧?

**Comment by shuaizai88** [comment]
重新下载依赖，最新版本已经改为IOException了
