### ISSUE TITLE
saveBatch 报错

### ISSUE THREAD

**Issue by jsercom** [baomidou/mybatis-plus#5012]
### 当前使用版本(必填,否则不予处理)

3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

批量插入的时候报空指针

### 重现步骤(如果有就写完整)
我的sql
`==>  Preparing: INSERT INTO TDTEP01 ( REC_CREATOR, REC_CREATE_TIME, PROJECT_CODE, CODE_CLASS, CODE_CLASS_DESC ) VALUES ( ?, ?, ?, ?, ? )
==> Parameters: admin(String), 20221209152221(String), TEST_FORM_DEV(String), EPTEST01(String), 测试(String)`

我的实体类 ID
    @TableId(value = "ID", type = IdType.AUTO)
    private Integer id;

### 报错信息

`org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: java.lang.NullPointerException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:192)
	at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:217)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.executeBatch(ServiceImpl.java:240)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveBatch(ServiceImpl.java:136)
`
`Caused by: java.lang.NullPointerException
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:82)
	... 136 more
`

**Comment by jsercom** [comment]
数据库用的DB2 主键设置自增

**Comment by miemieYaho** [comment]
org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:82)

**Comment by jsercom** [comment]
重写saveBatch###

**Comment by 12345ZMTHL** [comment]
所以咱们这个bug定位到是什么原因导致的嘛，昨天刚上线一个功能就出现这个异常，人都干冒烟了都
