### ISSUE TITLE
实体类继承了父类BaseEntity，MyBatis-Plus也要映射父类的字段，有点不灵活

### ISSUE THREAD

**Issue by andy65007** [baomidou/mybatis-plus#5034]
### 当前使用版本(必填,否则不予处理)

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.5.2</version>
</dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
兄弟，我使用若依框架，实体类子类继承了父类BaseEntity，父类中定义的一些字段，子类表可能根本不需要（这些字段如查询条件、数据权限过滤等），按照MPP目前逻辑必须映射，不然报错，这是不是有些不灵活了？希望增加全局配置项，对数据库表中或实体中没有对应的字段忽略。这样合适吗，会有哪些问题？
有些时候，开发者引用的可能是jar，也无法给父类添加 @TableField(exist =  false)

### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'search_value' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'search_value' in 'field list'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy99.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy129.selectList(Unknown Source)

**Comment by miemieYaho** [comment]
`TableName`注解指定排除父类字段

**Comment by andy65007** [comment]
还有这功能，来我试试。非常感谢@miemieYaho
