### ISSUE TITLE
springboot3 build with process-aot  have error...

### ISSUE THREAD

**Issue by gogolin001** [baomidou/mybatis-plus#5044]
when `gradle nativeCompile`, I got this:
~~~
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
        org.apache.ibatis.builder.CacheRefResolver
        org.apache.ibatis.parsing.XNode
        org.apache.ibatis.mapping.ResultFlag
        org.apache.ibatis.builder.ResultMapResolver
        org.apache.ibatis.builder.annotation.MethodResolver

        at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:87)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:70)    
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
~~~

it happened in spring-boot:3.0.0:process-aot    native build

**Comment by qmdx** [comment]
使用最新  `3.5.3`  版本

**Comment by the-tsing** [comment]
3.5.3版本也有这个问题

**Comment by tiro8183** [comment]
![image](https://user-images.githubusercontent.com/28704881/209897523-38ae113d-cfb8-450f-84c3-dcadbd6ccefe.png)
3.5.3版本也有这个问题

**Comment by ijry** [comment]
+1

**Comment by Abandoned9** [comment]
+1 <kbd>3.5.3</kbd>也有这个问题 @qmdx

**Comment by lizhuoxuan** [comment]
我使用3.5.3.1也有这个问题，是mybatis plus的问题，还是gradle的问题？

**Comment by gogolin001** [comment]
> 

是mybatis的问题

**Comment by 02uk** [comment]
我使用3.5.13添加<buildArgs>
                                --initialize-at-build-time=org.codehaus.groovy.util.LazyReference
                                --initialize-at-build-time=java.beans.Introspector
                                --initialize-at-build-time=com.sun.beans.introspect.ClassInfo
                                --initialize-at-build-time=com.sun.beans.finder.MethodFinder
                            </buildArgs>
  能打包成功，但是运行的时候  Caused by: java.lang.NullPointerException: null
	at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:52)
	... 15 common frames omitted
