### ISSUE TITLE
Dubbo中通过QueryWrapper 查询报错？

### ISSUE THREAD

**Issue by nanshandashan** [baomidou/mybatis-plus#508]
当前版本：
   mybatis-plus-boot-starter     版本号：3.0-RELEASE
   dubbo-spring-boot-starter    dubbo版本号：0.2.0

该问题是怎么引起的？
   跨进程查询，QueryWrapper 报错

 

### 重现步骤
  在 Dubbo的Consumer的Controller中执行以下代码，则报错
    QueryWrapper<SysUser>  queryWrapper = new QueryWrapper<>();
        if(params.containsKey("username")){
            queryWrapper.eq("username",params.get("username").toString());
        }
        int pageNo = Integer.parseInt(params.get("page").toString());
        int pageSize = Integer.parseInt(params.get("limit").toString());

        IPage<SysUser>  page = sysUserService.page(new Page<>(pageNo,pageSize),queryWrapper);

### 报错信息
2018-09-24 09:48:14.024  WARN 16957 --- [ver worker #1-1] c.a.d.r.p.dubbo.DecodeableRpcInvocation  :  [DUBBO] Decode argument failed: com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.normal: java.util.ArrayList ([]) cannot be assigned to 'com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList', dubbo version: 2.6.2, current host: 192.168.3.33

com.alibaba.com.caucho.hessian.io.HessianFieldException: com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.normal: java.util.ArrayList ([]) cannot be assigned to 'com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList'
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.logDeserializeError(JavaDeserializer.java:171) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:412) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:276) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:203) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2808) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2146) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2075) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2119) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2075) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:408) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:276) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:203) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2808) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2146) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2075) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2119) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2075) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.common.serialize.hessian2.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:91) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:110) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:70) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:129) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:124) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:84) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133) [dubbo-2.6.2.jar:2.6.2]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.2.5.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44) [netty-3.2.5.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Can not set com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList field com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.normal to java.util.ArrayList
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_181]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_181]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.8.0_181]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_181]
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:410) ~[dubbo-2.6.2.jar:2.6.2]
	... 36 common frames omitted

2018-09-24 09:48:14.024  WARN 16957 --- [ver worker #1-1] c.a.d.r.exchange.codec.ExchangeCodec     :  [DUBBO] Skip input stream 37, dubbo version: 2.6.2, current host: 192.168.3.33

**Comment by miemieYaho** [comment]
使用最新版试试.3.0.3

**Comment by nanshandashan** [comment]
试了，不行，QueryWrapper无法解析

**Comment by cjcj125125** [comment]
> 使用最新版试试.3.0.3
我使用最新的3.0.6 也是这个问题
