### ISSUE TITLE
v3.5.3版本开始lambdaQuery.one()报错！！！

### ISSUE THREAD

**Issue by dc1314** [baomidou/mybatis-plus#5084]
### 重现步骤(如果有就写完整)
SysRole role = this.lambdaQuery()
                .ne(SysRole::getId, id)
                .eq(SysRole::getCode, code)
                .eq(SysRole::getTenantId, tenantId)
                .last(StrPools.LIMIT_ONE)
                .one();

### 报错信息
Request processing failed; nested exception is com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Class must not be null
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920) ~[spring-webmvc-5.3.24.jar:5.3.24]

**Comment by miemieYaho** [comment]
3.5.3.1
