### ISSUE TITLE
使用多租户插件功能，解析SQL语句中有表别名为`ur`时，解析报错

### ISSUE THREAD

**Issue by ShepherdZFJ** [baomidou/mybatis-plus#5086]
### 当前使用版本(必填,否则不予处理)
3.5.2

### 重现步骤(如果有就写完整)
在代码中编写xml sql语句如下：
  <select id="getUserList" resultType="com.plasticene.textile.entity.User">
        select u.* from `user` u
        left join user_role ur on u.id = ur.user_id
        group by u.id
        order by u.id desc
    </select>
开启多租户插件功能执行该语句就会报错

### 报错信息：
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: select u.* from `user` u
        left join user_role ur on u.id = ur.user_id
        group by u.id
        order by u.id desc
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:65)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy178.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 101 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ur" <K_ISOLATION>
    at line 2, column 29.

**Comment by miemieYaho** [comment]
net.sf.jsqlparser.parser.ParseException

**Comment by ShepherdZFJ** [comment]
> ur



> net.sf.jsqlparser.parser.ParseException


> net.sf.jsqlparser.parser.ParseException

什么时候修复呢

**Comment by ShepherdZFJ** [comment]
> net.sf.jsqlparser.parser.ParseException

什么时候修复呢

**Comment by miemieYaho** [comment]
https://github.com/JSQLParser/JSqlParser

**Comment by Seam088** [comment]
ur可能是mybatisPlus的关键字吧？

**Comment by Seam088** [comment]
将 ur 别名更换成其他别名就可以解决了。

**Comment by peachyy** [comment]
升级jsqlparser 到4.5 @ShepherdZFJ 

```xml		
<dependency>
	<groupId>com.github.jsqlparser</groupId>
	<artifactId>jsqlparser</artifactId>
	<version>4.5</version>
</dependency>
```

**Comment by ShepherdZFJ** [comment]
> 升级jsqlparser 到4.5 @ShepherdZFJ
> 
> ```
> <dependency>
> 	<groupId>com.github.jsqlparser</groupId>
> 	<artifactId>jsqlparser</artifactId>
> 	<version>4.5</version>
> </dependency>
> ```

好的，我试试

**Comment by nieqiurong** [comment]
#5142   合并至此处讨论.
