### ISSUE TITLE
Db 下通过 LambdaQueryWrapper 查询报错

### ISSUE THREAD

**Issue by LoptrX** [baomidou/mybatis-plus#5103]
### 当前使用版本(必填,否则不予处理)

3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

获取不到泛型

### 重现步骤(如果有就写完整)
Entity demo = new Entity();

- error
Db.list(new LambdaQueryWrapper< Entity >()
                .eq(Entity::getId, demo.getId()));

- success
Db.list(new LambdaQueryWrapper<>(Entity.class)
                .eq(Entity::getId, demo.getId()));

- success
Db.list(Wrappers.lambdaQuery(Entity.class)
                .eq(Entity::getId, demo.getId()));

### 报错信息

com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: error: can not get entityClass from wrapper
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49)
	at com.baomidou.mybatisplus.core.toolkit.Assert.isTrue(Assert.java:38)
	at com.baomidou.mybatisplus.core.toolkit.Assert.notNull(Assert.java:72)
	at com.baomidou.mybatisplus.extension.toolkit.Db.getEntityClass(Db.java:555)
	at com.baomidou.mybatisplus.extension.toolkit.Db.list(Db.java:346)

**Comment by LoptrX** [comment]
注意看文档

**Comment by liLong1314** [comment]
> 注意看文档

请问，看哪个文档？在网址是？找不到相关的东西啊

**Comment by LoptrX** [comment]
> > 注意看文档
> 
> 请问，看哪个文档？在网址是？找不到相关的东西啊

Db 类文档里已经说明了，只能使用 class 或者实例的方式去创建 wrapper 不能使用泛型去描述 wrapper
