### ISSUE TITLE
3.5.3.1版本postgresql找不到表

### ISSUE THREAD

**Issue by dirac921** [baomidou/mybatis-plus#5126]
### 当前使用版本(必填,否则不予处理)
3.5.3.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
升级3.5.3.1，springboot3，java17

### 报错信息
org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: FORECAST_RESULT_B in statement [SELECT  id,range  FROM forecast_result_b]
; bad SQL grammar []
 at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate([SQLExceptionSubclassTranslator.java:101](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate([AbstractFallbackSQLExceptionTranslator.java:70](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate([AbstractFallbackSQLExceptionTranslator.java:79](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible([MyBatisExceptionTranslator.java:91](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke([SqlSessionTemplate.java:441](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at jdk.proxy2/jdk.proxy2.$Proxy77.selectList(Unknown Source)
 at org.mybatis.spring.SqlSessionTemplate.selectList([SqlSessionTemplate.java:224](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany([MybatisMapperMethod.java:166](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute([MybatisMapperMethod.java:77](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke([MybatisMapperProxy.java:148](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke([MybatisMapperProxy.java:89](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at jdk.proxy2/jdk.proxy2.$Proxy107.selectList(Unknown Source)
 at org.hrc.swj.models.GridxajApplicationTests.test([GridxajApplicationTests.java:19](vscode-file://vscode-app/d:/program/VSCode-win32-x64-1.74.2-hw-hsyb/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)

Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: FORECAST_RESULT_B in statement [SELECT  id,range  FROM forecast_result_b]
 at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)

**Comment by miemieYaho** [comment]
at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)?

**Comment by dirac921** [comment]
> at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)?

用了动态数据源，也要更新版本，现在可以了
