### ISSUE TITLE
使用ActiveRecord模式报 Not Found TableInfoCache.

### ISSUE THREAD

**Issue by liuximeng** [baomidou/mybatis-plus#513]
### 重现步骤
实体继承   Model, 进行删除操作

### 报错信息
       at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:51)
	at com.baomidou.mybatisplus.core.toolkit.Assert.isTrue(Assert.java:41)
	at com.baomidou.mybatisplus.core.toolkit.Assert.notNull(Assert.java:75)
	atcom.baomidou.mybatisplus.core.toolkit.GlobalConfigUtils.currentSessionFactory(GlobalConfigUtils.java:65)
	at com.baomidou.mybatisplus.core.toolkit.sql.SqlHelper.getSqlSession(SqlHelper.java:67)
	at com.baomidou.mybatisplus.core.toolkit.sql.SqlHelper.sqlSession(SqlHelper.java:79)
	at com.baomidou.mybatisplus.extension.activerecord.Model.sqlSession(Model.java:312)
	at com.baomidou.mybatisplus.extension.activerecord.Model.delete(Model.java:126)

**Comment by miemieYaho** [comment]
有 mapper 吗?没有就写上, mapper 能用 ar 才能用
