### ISSUE TITLE
SpringMVC无法编译，报空指针异常

### ISSUE THREAD

**Issue by SignorinoY** [baomidou/mybatis-plus#534]
### 当前使用版本
```xml
<dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus</artifactId>
      <version>3.0.4</version>
</dependency>
```

### 重现步骤
由2.3更新至3.0.4后按照文档对原先代码进行部分修改，修改后，发现无法进行编译。
使用代码生成entity,service,mapper,controller,生成代码如下
```java
public class MpCodeGenerator {

  public static void main(String[] args) {
    String packageName = "cn.ghy";
    generateByTables(packageName, "file", "user");
  }

  public static void generateByTables(String packageName, String... tableNames) {

    final String projectPath = System.getProperty("user.dir");

    GlobalConfig globalConfig = new GlobalConfig().setOutputDir(projectPath + "/src/main/java")
        .setAuthor("Ziyang").setFileOverride(false).setOpen(false).setServiceName("%sService");

    DataSourceConfig dataSourceConfig = new DataSourceConfig().setUrl(
        "jdbc:mysql://localhost:3306/larva?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false")
        .setUsername("root").setPassword("root").setDriverName("com.mysql.cj.jdbc.Driver");

    StrategyConfig strategyConfig = new StrategyConfig().setCapitalMode(true)
        .setRestControllerStyle(true)
        .setNaming(NamingStrategy.underline_to_camel)
        .setInclude(tableNames)
        .setControllerMappingHyphenStyle(true);

    final PackageConfig packageConfig = new PackageConfig().setParent(packageName);

    TemplateConfig templateConfig = new TemplateConfig().setXml(null);

    InjectionConfig injectionConfig = new InjectionConfig() {
      @Override
      public void initMap() {

      }
    };
    List<FileOutConfig> fileOutConfigs = new ArrayList<>();
    fileOutConfigs.add(new FileOutConfig("/templates/mapper.xml.ftl") {
      @Override
      public String outputFile(TableInfo tableInfo) {
        // 自定义输入文件名称
        return projectPath + "/src/main/resources/mapper/" + "/" + tableInfo.getEntityName()
            + "Mapper.xml";
      }
    });
    injectionConfig.setFileOutConfigList(fileOutConfigs);

    AutoGenerator autoGenerator = new AutoGenerator().setGlobalConfig(globalConfig)
        .setDataSource(dataSourceConfig).setStrategy(strategyConfig).setPackageInfo(packageConfig)
        .setCfg(injectionConfig).setTemplate(templateConfig)
        .setTemplateEngine(new FreemarkerTemplateEngine());

    autoGenerator.execute();
  }
}
```
mybatis配置文件如下
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:context="http://www.springframework.org/schema/context"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
                        http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
                        http://www.springframework.org/schema/context
                        http://www.springframework.org/schema/context/spring-context-3.1.xsd">
  <!-- Spring Auto scanning components -->
  <context:component-scan base-package="cn.ghy.service"/>

  <!-- 引入配置文件 -->
  <bean id="propertyConfigurer"
    class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
    <property name="location" value="classpath:jdbc.properties"/>
  </bean>
  <!--数据库连接池-->
  <bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
    <property name="driverClassName" value="${jdbc.driverClass}"/>
    <property name="url" value="${jdbc.connectionURL}"/>
    <property name="username" value="${jdbc.username}"/>
    <property name="password" value="${jdbc.password}"/>
    <!-- 初始化连接大小 -->
    <property name="initialSize" value="${jdbc.initialSize}"/>
    <!-- 连接池最大数量 -->
    <property name="maxActive" value="${jdbc.maxActive}"/>
    <!-- 连接池最大空闲 -->
    <property name="maxIdle" value="${jdbc.maxIdle}"/>
    <!-- 连接池最小空闲 -->
    <property name="minIdle" value="${jdbc.minIdle}"/>
    <!-- 获取连接最大等待时间 -->
    <property name="maxWait" value="${jdbc.maxWait}"/>
  </bean>

  <!-- SqlSessionFactory -->
  <bean id="sqlSessionFactory"
    class="com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean">
    <property name="dataSource" ref="dataSource"/>
    <property name="mapperLocations" value="classpath:/mapper/*.xml"/>
    <!--  配置实体扫描路径，多个package可以用分号; 逗号, 分隔， 支持通配符*-->
    <property name="typeAliasesPackage" value="cn.ghy.entity"/>
  </bean>

  <!-- 配置mybatis 扫描mapper接口的路径, 相当于注解@MapperScan，@MapperScan("com.baomidou.mybatisplus.test.h2.entity.mapper")-->
  <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
    <property name="basePackage" value="cn.ghy.mapper"/>
  </bean>
  <!-- 事务管理 : DataSourceTransactionManager dataSource:引用上面定义的数据源 -->
  <bean id="transactionManager"
    class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
    <property name="dataSource" ref="dataSource"/>
  </bean>

</beans>
```

### 报错信息
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [D:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\ROOT\WEB-INF\classes\cn\ghy\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [spring-mybatis.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
```

**Comment by miemieYaho** [comment]
什么叫无法编译?你这不是运行时报错吗?是在哪个环节报错的? generator 还是项目启动?

**Comment by SignorinoY** [comment]
> 什么叫无法编译?你这不是运行时报错吗?是在哪个环节报错的? generator 还是项目启动?

generator正常运行，项目启动时出现如上报错

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples

**Comment by dljunzhuo** [comment]
哥们  你的这个问题解决了吗

**Comment by dljunzhuo** [comment]
哥们 怎么解决的 能告诉下吗

**Comment by miemieYaho** [comment]
使用 `3.0.5-SNAPSHOT` 版本
