### ISSUE TITLE
mp批量操作失败：Mapped Statements collection does not contain value for com.baomidou.mybatisplus.core.mapper.BaseMapper.insert。

### ISSUE THREAD

**Issue by Zhanrunfeng** [baomidou/mybatis-plus#5367]
### 当前使用版本(必填,否则不予处理)

<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            
            <version>3.5.3.1</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.4.2版本调用本代码没有问题，3.5.3.1版本有错误提示。

### 重现步骤(如果有就写完整)
mapper
public interface AreaSpaceMapper extends BaseMapper<AreaSpace> {

}
service
public interface IAreaSpaceService extends IService<AreaSpace> {

}
serviceImpl
@Service
@Primary
public class AreaSpaceServiceImpl extends IBaseServiceImpl<AreaSpaceMapper, AreaSpace> implements IAreaSpaceService {
}
serviceImpl的基类

@Slf4j
@SuppressWarnings("unchecked")
public class IBaseServiceImpl<M extends BaseMapper<T>, T> extends ServiceImpl<BaseMapper<T>, T> {
}

### 报错信息
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.baomidou.mybatisplus.core.mapper.BaseMapper.insert] with root cause

java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.baomidou.mybatisplus.core.mapper.BaseMapper.insert
	at com.baomidou.mybatisplus.core.MybatisConfiguration$StrictMap.get(MybatisConfiguration.java:454) ~[mybatis-plus-core-3.5.3.1.jar:3.5.3.1]
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMappedStatement(MybatisConfiguration.java:353) ~[mybatis-plus-core-3.5.3.1.jar:3.5.3.1]
	at com.baomidou.mybatisplus.core.MybatisConfiguration.getMappedStatement(MybatisConfiguration.java:345) ~[mybatis-plus-core-3.5.3.1.jar:3.5.3.1]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:193) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181) ~[mybatis-3.5.10.jar:3.5.10]

**Comment by miemieYaho** [comment]
`public class IBaseServiceImpl<M, T> extends ServiceImpl<M extends BaseMapper, T>`试试

**Comment by Zhanrunfeng** [comment]
public class IBaseServiceImpl<M extends BaseMapper, T> extends ServiceImpl<M，T> {
}
我改为这样可以，我先确认有没有影响其他功能
