### ISSUE TITLE
官网文档打开报错，看不到页面内容

### ISSUE THREAD

**Issue by CoderViking** [baomidou/mybatis-plus#5389]
### 当前使用版本(必填,否则不予处理)

最新版

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

正常访问官网，发现文档页面打不开

### 重现步骤(如果有就写完整)

访问mybatis.plus然后点击->快速开始->打开条件构造器页面，前端提示报错，页面白屏

### 报错信息

wrapper.html:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
app.a3d46bc0.js:8 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:40618)
    at d (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:53352)
    at https://mybatis.plus/assets/js/app.a3d46bc0.js:8:52615
    at f (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:52847)
    at h (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:53438)
    at P (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:56776)
    at a.__patch__ (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:57176)
    at t._update (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:34410)
    at a.r (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:64492)
    at hn.get (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:26686)
googleads.g.doubleclick.net/pagead/ads?client=ca-pub-4147143076931995&output=html&adk=1812271804&adf=3025194257&lmt=1604086149&plat=3%3A65536%2C4%3A65536%2C9%3A32776%2C16%3A8388608%2C17%3A32%2C24%3A32%2C25%3A32%2C30%3A1048576%2C32%3A32%2C41%3A32%2C42%3A32&format=0x0&url=https%3A%2F%2Fmybatis.plus%2Fguide%2Fwrapper.html&ea=0&pra=5&wgl=1&uach=WyJXaW5kb3dzIiwiMTAuMC4wIiwieDg2IiwiIiwiMTEzLjAuNTY3Mi4xMjciLFtdLDAsbnVsbCwiNjQiLFtbIkdvb2dsZSBDaHJvbWUiLCIxMTMuMC41NjcyLjEyNyJdLFsiQ2hyb21pdW0iLCIxMTMuMC41NjcyLjEyNyJdLFsiTm90LUEuQnJhbmQiLCIyNC4wLjAuMCJdXSwwXQ..&dt=1686110037978&bpp=3&bdt=546&idt=42&shv=r20230601&mjsv=m202306050101&ptt=9&saldr=aa&abxe=1&cookie=ID%3D300eea9a6c33be99-22a9b656b3df00f6%3AT%3D1686109762%3ART%3D1686109762%3AS%3DALNI_MYGi2YplBOT1ZiZw6fpcpTOsRWzjA&gpic=UID%3D00000c44ec9c20b8%3AT%3D1686109762%3ART%3D1686109762%3AS%3DALNI_Mbh3QHpy2KpoJNNX9GOSA1x0oyf3Q&nras=1&correlator=5868733621486&frm=20&pv=2&ga_vid=41257078.1686110038&ga_sid=1686110038&ga_hid=1197342525&ga_fc=0&u_tz=480&u_his=4&u_h=1080&u_w=1920&u_ah=1050&u_aw=1920&u_cd=24&u_sd=1&dmc=8&adx=-12245933&ady=-12245933&biw=1091&bih=947&scr_x=0&scr_y=0&eid=44759875%2C44759926%2C44759837%2C31075085%2C44772268%2C44788442%2C44793500&oid=2&pvsid=2938702240952664&tmod=1281816913&uas=0&nvt=1&fsapi=1&ref=https%3A%2F%2Fmybatis.plus%2Fguide%2F&fc=1920&brdim=-1920%2C-65%2C-1920%2C-65%2C1920%2C-65%2C1920%2C1050%2C1091%2C947&vis=1&rsz=%7C%7Cs%7C&abl=NS&fu=32768&bc=31&ifi=1&uci=a!1&fsb=1&dtd=86:1     Failed to load resource: the server responded with a status of 403 ()

**Comment by miemieYaho** [comment]
https://baomidou.com/pages/10c804/#abstractwrapper

**Comment by Marhoosh** [comment]
现在又打不开了 https://mybatis.plus/guide/generator.html 访问白屏
控制台报错如下：
`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:40618)
    at d (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:53352)
    at https://mybatis.plus/assets/js/app.a3d46bc0.js:8:52615
    at f (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:52847)
    at h (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:53438)
    at P (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:56776)
    at a.__patch__ (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:57176)
    at t._update (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:34410)
    at a.r (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:64492)
    at hn.get (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:26686)`

**Comment by VampireAchao** [comment]
https://www.baomidou.com/guides/code-generator/

Marhoosh ***@***.***> 于2024年6月20日周四 16:13写道：
