### ISSUE TITLE
V2.3.3 ActiveRecord模式 Not Found TableInfoCache 异常

### ISSUE THREAD

**Issue by gucg0307** [baomidou/mybatis-plus#547]
### 当前使用版本(必须填写清楚，否则不予处理)
V2.3.3

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
pojo继承Model<>，未定义该pojo相应的Mapper。

### 重现步骤
不定义相应Mapper接口，直接在service内部通过pojo的insert方法执行时抛异常。增加了相应Mapper后，不抛异常。

### 报错信息

Caused by: com.baomidou.mybatisplus.exceptions.MybatisPlusException: com.pojo.ApplyAsset Not Found TableInfoCache.
	at com.baomidou.mybatisplus.toolkit.GlobalConfigUtils.currentSessionFactory(GlobalConfigUtils.java:66) ~[mybatis-plus-support-2.3.3.jar:?]
	at com.baomidou.mybatisplus.mapper.SqlHelper.getSqlSession(SqlHelper.java:68) ~[mybatis-plus-support-2.3.3.jar:?]
	at com.baomidou.mybatisplus.mapper.SqlHelper.sqlSession(SqlHelper.java:81) ~[mybatis-plus-support-2.3.3.jar:?]
	at com.baomidou.mybatisplus.activerecord.Model.sqlSession(Model.java:436) ~[mybatis-plus-support-2.3.3.jar:?]
	at com.baomidou.mybatisplus.activerecord.Model.insert(Model.java:58) ~[mybatis-plus-support-2.3.3.jar:?]

**Comment by miemieYaho** [comment]
设计就是这样的

**Comment by yuxiaobin** [comment]
AR模式本来就是需要定义mapper的

**Comment by gucg0307** [comment]
是否有必要写一个空的mapper，mapper功能可否由框架代生成。另外，对复合主键是如何支持的。
