### ISSUE TITLE
[BUG]Mybatis-Plus使用XML编写SQL时，解析SQL出错：Encountered unexpected token: "," ","

### ISSUE THREAD

**Issue by t375152973** [baomidou/mybatis-plus#5484]
### 当前使用版本
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
</dependency>

### 该问题是如何引起的？
复杂SQL解析失败，会出现错误。将jsqlparser升级到4.6版本仍然无法解决。
后与jsqlparser贡献者进行交流，知晓jsqlparser-4.7-SNAPSHOT版本能解决此问题，但更新后发现，分页拦截器内使用的SelectExpressionItem在4.7版本中已去除，因此，与mybatis-plus版本不兼容。故提出此问题，看是否有解决方案。
复杂SQL如下：
SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
FROM `table1` b
         LEFT JOIN `table2` m ON m.`contactId`=b.`id`
         LEFT JOIN `table3` g ON g.`id` = m.`groupId`
WHERE b.`isDelete` != '1'
GROUP BY b.`id`
ORDER BY LENGTH(b.`name`) ASC,
     CONVERT(b.`name`, SIGNED) ASC,
     CONVERT(b.`name` USING GBK),
     b.`crewType` DESC

### 重现步骤(如果有就写完整)
1、mybatis-plus配置多租户拦截器实现多租户模式
2、xml编写上述SQL
3、使用租户拦截器、分页拦截器和乐观锁拦截器进行SQL拦截，拼写租户ID和分页信息
4、springboot容器启动调用报错

### 报错信息
[ERROR][2023-07-19 14:15:58:928] [szwa-business,10931121eb3d4cfd,10931121eb3d4cfd,] [http-nio-9192-exec-1-com.hrx.szwa.common.aspect.RestControllerAspect--124 line]  - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:97)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	at com.sun.proxy.$Proxy180.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:121)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:85)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy184.queryAddressBookRsp(Unknown Source)
	at com.hrx.szwa.business.service.impl.AddressBookServiceImpl.queryAddressBookByPage(AddressBookServiceImpl.java:93)
	at com.hrx.szwa.business.service.impl.AddressBookServiceImpl$$FastClassBySpringCGLIB$$a1f0f6f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.hrx.szwa.business.service.impl.AddressBookServiceImpl$$EnhancerBySpringCGLIB$$13ecb663.queryAddressBookByPage(<generated>)
	at com.hrx.szwa.business.controller.AddressBookController.queryAddressBookByPage(AddressBookController.java:68)
	at com.hrx.szwa.business.controller.AddressBookController$$FastClassBySpringCGLIB$$53831885.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:100)
	at com.hrx.szwa.common.aspect.RestControllerAspect.around(RestControllerAspect.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.hrx.szwa.business.controller.AddressBookController$$EnhancerBySpringCGLIB$$e6dc261c.queryAddressBookByPage(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:84)
	at org.springframework.cloud.sleuth.instrument.web.LazyTracingFilter.doFilter(TraceWebServletAutoConfiguration.java:138)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hrx.szwa.common.filter.TenantContextHolderFilter.doFilter(TenantContextHolderFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:153)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	... 113 common frames omitted
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames
        FROM `table1` b
                 LEFT JOIN `table1_map` m ON m.`contactId`=b.`id`
                 LEFT JOIN `table1_group` g ON g.`id` = m.`groupId`
        WHERE b.`isDelete` != '1'
         
         
         
         
        GROUP BY b.`id`
        ORDER BY LENGTH(b.`name`) ASC,
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:68)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy380.query(Unknown Source)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:151)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy380.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
	... 120 common frames omitted
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 11, column 38.

Was expecting one of:

    "EMIT"
    "NULLS"
    <EOF>
    <ST_SEMICOLON>

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:49)
	... 128 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 11, column 38.

Was expecting one of:

    "EMIT"
    "NULLS"
    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:38866)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:38696)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:306)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 common frames omitted

**Comment by baklpc** [comment]
我基本遇到的动态sql，生成的sql有大量\n\n的时候，JSqlParser就解析失败了，不知道mp如何解决，能压缩一下sql最好了

**Comment by baklpc** [comment]
<img width="881" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/26053677/997e2530-f1b8-42b7-9247-55aa0c99c78d">
这样解决了

**Comment by t375152973** [comment]
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/26053677/254567939-997e2530-f1b8-42b7-9247-55aa0c99c78d.png"> 这样解决了


已经尝试过了，已经将SQL转换成如下样式还是无法正常执行。
SELECT b.*,GROUP_CONCAT(g.`groupName`) AS groupNames FROM `table1` b LEFT JOIN `table2` m ON m.`contactId`=b.`id` LEFT JOIN `table3` g ON g.`id` = m.`groupId` and g.center_id = ? WHERE b.`isDelete` != '1' and b.center_id = ? GROUP BY b.`id` ORDER BY LENGTH(b.`name`) ASC, CONVERT(b.`name`, SIGNED) ASC, CONVERT(b.`name` USING GBK), b.`crewType` DESC

**Comment by baklpc** [comment]
你看你报什么错，我那样是解决JSqlParser多个换行符解析报错问题，用正则删除多个换行保留一个换行，还有就是JSqlParser提供了一个在线解析sql的工具，你可以把原始sql贴进去，可以校验是否通过

**Comment by baklpc** [comment]
你别压缩sql，就删除多个换行，保留一个

**Comment by nieqiurong** [comment]
> 我基本遇到的动态sql，生成的sql有大量\n\n的时候，JSqlParser就解析失败了，不知道mp如何解决，能压缩一下sql最好了

#5345

**Comment by kim709394** [comment]
goup by语句加条件的话应该用having而不能先where再group by

**Comment by nieqiurong** [comment]
#5872

**Comment by pansong291** [comment]
> <img alt="image" width="881" src="https://private-user-images.githubusercontent.com/26053677/254567939-997e2530-f1b8-42b7-9247-55aa0c99c78d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDAzMTcsIm5iZiI6MTcxMjc0MDAxNywicGF0aCI6Ii8yNjA1MzY3Ny8yNTQ1Njc5MzktOTk3ZTI1MzAtZjFiOC00MmI3LTkyNDctNTVhYTBjOTljNzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NDhmMTI1MjQ0NzE1Y2JjY2JiMWNjNzk0M2YzZWU5NWQ3ZDkxZGNjYjgzNGNjOGZmMjRkMzkzZjAxZGNjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xSAjM5gES4h_okDwoSOl45mS6GCyzaarveE3QXoGhZI"> 这样解决了

@baklpc 请教一下这个会不会把数据里的空行给替换了？比如：
```sql
update shop_info set title=?,



content='abc



def'
where id=?
```
