### ISSUE TITLE
mp简单SQL执行异常，按照修复方案修复不成功

### ISSUE THREAD

**Issue by shane-zfx** [baomidou/mybatis-plus#5494]
### 当前使用版本(必填,否则不予处理)
mybatis-plus-boot-starter    ---    3.5.3.1
jsqlparser    ---   4.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

项目普通的 insert 操作
 insert into table_name (field_name) values (field_value)

### 重现步骤(如果有就写完整)

不用重现，没插入成功过

### Cause: java.lang.ClassCastException: net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to net.sf.jsqlparser.statement.select.PlainSelect
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy144.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:59)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy215.insert(Unknown Source)

**Comment by miemieYaho** [comment]
你都用了mp的哪些插件? jsqlparser版本号mp有指定不要擅自提高

**Comment by shane-zfx** [comment]
目前已使用如下下插件
1.分页
2.拦截器
3.lock4j
4.动态数据源
5.mybatis-plus-generator

**Comment by miemieYaho** [comment]
jsqlparser版本号使用mp带的就行了
