### ISSUE TITLE
使用mockito如何对mybatisplus的链式调用进行mock测试？

### ISSUE THREAD

**Issue by CodingGyd** [baomidou/mybatis-plus#5535]
### 当前使用版本(必填,否则不予处理)
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
**问题描述：**
使用mybatis-plus实现一个查询功能，针对链式查询方式，mockito单元测试该怎么写？  (查了很多资料都没有找到正确的办法，官网也没有提过)

**业务mapper是这么写的：**
public interface IdRuleMapper extends ExBaseMapper<IdRuleEntity> {

}

**单元测试用的mockito框架，是这样写的：**

@RunWith(MockitoJUnitRunner.class)
@SpringBootTest(classes = MainApplication.class)
public class IdRuleServiceTest  {

    @Mock
    IdRuleMapper mapper;

    @Before
    public void setUp(){
     }

    @Test
    public void testQuery() {
        IdRuleEntity idRule = new IdRuleEntity();
        idRule.setCurrentId(1L);
        Mockito.when(mapper.lambdaQuery().eq(IdRuleEntity::getIdType,"1").one()).thenReturn(idRule);
        IdRuleEntity idRule2 = mapper.lambdaQuery().eq(IdRuleEntity::getIdType,"1").one();
        Assert.assertEquals(idRule, idRule2);
    }

}

但是执行报错。

### 报错信息

java.lang.NullPointerException
	at com.gyd.service.IdRuleServiceTest.testQuery(IdRuleServiceTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:44)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:74)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:80)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

**Comment by CodingGyd** [comment]
mockito框架的版本是3.1.0

**Comment by nieqiurong** [comment]
![image](https://github.com/baomidou/mybatis-plus/assets/15142701/bac134ee-7295-42ab-8fe8-d22853626148)

**Comment by azernia** [comment]
<img width="632" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/50955702/d16cf8d7-bda3-4664-a33d-8d6026e9e549">
调用 lambdaQuery() 方法时会返回 LambdaQueryChainWrapper 对象，每一次链式调用的时候都会返回该对象，使 用 mockito 的时候需要mock LambdaQueryChainWrapper 对象。
如：
`LambdaQueryChainWrapper<UserProfile> queryChainWrapper = mock(LambdaQueryChainWrapper.class);
        when(service.lambdaQuery()).thenReturn(queryChainWrapper);
        when(queryChainWrapper.eq(anyBoolean(), any(), any())).thenReturn(queryChainWrapper);
        when(queryChainWrapper.one()).thenReturn(new UserProfile());`

**Comment by azernia** [comment]
<img width="632" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/50955702/d16cf8d7-bda3-4664-a33d-8d6026e9e549">

调用 lambdaQuery() 方法时会返回 LambdaQueryChainWrapper 对象，每一次链式调用的时候都会返回该对象，使 用 mockito 的时候需要mock LambdaQueryChainWrapper 对象。
如：
```
LambdaQueryChainWrapper<UserProfile> queryChainWrapper = mock(LambdaQueryChainWrapper.class);
when(service.lambdaQuery()).thenReturn(queryChainWrapper);
when(queryChainWrapper.eq(anyBoolean(), any(), any())).thenReturn(queryChainWrapper);
when(queryChainWrapper.one()).thenReturn(new UserProfile());
```

**Comment by CodingGyd** [comment]
感谢各位，可以了

**Comment by changyoutianxia** [comment]
@azernia  如何根据不同的参数返回不同的数据呢？上面的都是any，如果不同参数 ，写两套，mock 能否感知调用链不一样？
