### ISSUE TITLE
关于type-enums-package失效

### ISSUE THREAD

**Issue by zx472010602** [baomidou/mybatis-plus#556]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.2

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
突然type-enums-package不生效，无法被发现

### 重现步骤
再新建一个小demo后发现该属性没问题，可以生效，但是在本项目无效
经过反复断点调试发现直接原因为
DefaultResultSetHandler类内部的createAutomaticMappings方法中的
TypeHandlerRegistry对象内部的TYPE_HANDLER_MAP（ConcurrentHashMap），同一个枚举，存在两个对象，如图
![image](https://user-images.githubusercontent.com/31379313/46879090-9faac880-ce77-11e8-98ef-c39d12657648.png)
然后每次获取到的都是Mybatis原生的E那个Handler，导致报错（数据库数据为0字符串）
以上问题应该是和某具体maven依赖冲突或其他隐藏问题，希望能给一点解决建议？在哪些情况下回出现此类问题

### 报错信息
Caused by: java.lang.IllegalArgumentException: 
       No enum constant com.*******.enums.AppTypeEnum.0
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_181]
	at org.apache.ibatis.type.EnumTypeHandler.getNullableResult(EnumTypeHandler.java:49) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.type.EnumTypeHandler.getNullableResult(EnumTypeHandler.java:26) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:66) ~[mybatis-3.4.6.jar:3.4.6]
	... 101 common frames omitted

**Comment by miemieYaho** [comment]
使用最新版
