### ISSUE TITLE
mybatis-plus-generator 3.5.3 版本配置 superClass 生成代码出错

### ISSUE THREAD

**Issue by Fate02010** [baomidou/mybatis-plus#5603]
### 当前使用版本(必填,否则不予处理)
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>3.5.3</version>
        </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 .strategyConfig(builder -> {
                    builder.likeTable(new LikeTable("ab_")).addTablePrefix(ab_")
                            .build()
                            // 设置实体
                            .entityBuilder()
                            // 设置基类
                            .superClass(BaseDataSourceEntity.class)
配置了superClass 生成代码就会出现报错

### 报错信息
 无法创建文件，请检查配置信息！
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:264)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:179)
	at com.baomidou.mybatisplus.generator.FastAutoGenerator.execute(FastAutoGenerator.java:213)
	at com.alibaba.csp.sentinel.mahasdashboard.build.MybatisCodeBuild.main(MybatisCodeBuild.java:93)
Caused by: java.lang.NullPointerException: Cannot invoke "com.baomidou.mybatisplus.core.metadata.TableInfo.getConfiguration()" because "tableInfo" is null
	at com.baomidou.mybatisplus.core.metadata.TableInfoHelper.getAllFields(TableInfoHelper.java:594)
	at com.baomidou.mybatisplus.generator.config.builder.Entity.convertSuperEntityColumns(Entity.java:190)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.baomidou.mybatisplus.generator.config.builder.Entity$Builder.get(Entity.java:639)
	at com.baomidou.mybatisplus.generator.config.StrategyConfig.entity(StrategyConfig.java:152)
	at com.baomidou.mybatisplus.generator.config.po.TableInfo.<init>(TableInfo.java:136)
	at com.baomidou.mybatisplus.generator.query.DefaultQuery.lambda$queryTables$0(DefaultQuery.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.baomidou.mybatisplus.generator.query.DefaultQuery.queryTables(DefaultQuery.java:68)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTableInfoList(ConfigBuilder.java:152)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:245)

**Comment by nieqiurong** [comment]
#5467
