### ISSUE TITLE
使用LambdaUpdateWrapper 动态set 列 报错

### ISSUE THREAD

**Issue by liuzhe101** [baomidou/mybatis-plus#5656]
### 当前使用版本(必填,否则不予处理)
3.4.2

### 重现步骤(如果有就写完整)
  LambdaUpdateWrapper<PartCategory> updateWrapper = Wrappers.lambdaUpdate(PartCategory.class);
        for (RuleRelationVO ruleRelationVO : deletedRelationVoList) {
            updateWrapper.set(judgeNotNullOrTrue(ruleRelationVO.getBackflushChance()), PartCategory::getBackflushChance, null);
}

### 报错信息

com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not find lambda cache for this entity [com.admin.entity.PartCategory]
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:49)
	at com.baomidou.mybatisplus.core.toolkit.Assert.isTrue(Assert.java:38)
	at com.baomidou.mybatisplus.core.toolkit.Assert.notNull(Assert.java:72)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.tryInitCache(AbstractLambdaWrapper.java:94)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.getColumn(AbstractLambdaWrapper.java:79)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:62)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:58)
	at com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper.set(LambdaUpdateWrapper.java:92)
	at com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper.set(LambdaUpdateWrapper.java:37)
	at com.baomidou.mybatisplus.core.conditions.update.Update.set(Update.java:30)
	at

**Comment by miemieYaho** [comment]
mapper注入到spring了吗?

**Comment by liuzhe101** [comment]
> mapper注入到spring了吗?

![image](https://github.com/baomidou/mybatis-plus/assets/61652514/8d63e27e-804b-4ddf-89d0-2d7c8d370eab)
在的，请问大佬怎么解决，这个实体bean在另一个模块，通过jar 引入
, 实体的mapper不在 本模块，
![image](https://github.com/baomidou/mybatis-plus/assets/61652514/1c01bafb-88ed-43cf-a8ae-6e6b3361ad78)

**Comment by miemieYaho** [comment]
debug看`LambdaUtils#getColumnMap`

**Comment by liuzhe101** [comment]
> debug看`LambdaUtils#getColumnMap`
我直接把deletedRelationVoList 传到PartCategory 的module 去LambdaUpdateWrapper updateWrapper = Wrappers.lambdaUpdate(PartCategory.class);就没问题了；

我大概猜测原因，就是plus框架只支持自己运行module 的Entity，要是引入本地打包其他模块的jar是不支持的，但是还是希望我们框架，在后续使用的时候就能抛出明确的异常信息，比如必须是本容器内的Entity，.class的Entity不支持

**Comment by miemieYaho** [comment]
你为什么要靠猜?debug不会吗?
