### ISSUE TITLE
从3.5.3.1版本升级到3.5.3.2遇到的问题 

### ISSUE THREAD

**Issue by maxtwistdd** [baomidou/mybatis-plus#5740]
### 当前使用版本(必填,否则不予处理)
3.5.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
3.5.3.2依赖jsqlParser版本为4.6，3.5.3.1依赖版本为4.4，该组件的parseStatement函数相较之前的版本做了很大修改，改成了异步线程来处理任务，但是加了默认的最大超时时间为6s（这个参数实际是开放可配置的）。我们在性能测试中发现，有些sql在解析中会超时，导致执行失败，希望mybaits-plus可以增加这个组件参数的配置方法。

### 报错信息

Caused by: java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
        at com.baomidou.mybatisplus.extension.parser.JsqlParserGlobal.parse(JsqlParserGlobal.java:39)
        at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:48)
        ... 60 common frames omitted

**Comment by miemieYaho** [comment]
JsqlParserGlobal.setParserSingleFunc和setParserMultiFunc
