### ISSUE TITLE
无法抽离公用属性作为父类

### ISSUE THREAD

**Issue by xzc1-23** [baomidou/mybatis-plus#5751]
### 当前使用版本(必填,否则不予处理)
     <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3.1</version>
        </dependency>
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
早期版本试过是可以的，但是忘记用的是哪个版本了。

### 重现步骤(如果有就写完整)
抽离id、createTime、updateTime作为父类属性，实体类去继承父类就会触发异常。
不继承属性写在实体类中，不存在异常。

**Comment by xzc1-23** [comment]
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '_handledType'. It was either not specified and/or could not be found for the javaType (java.lang.Class) : jdbcType (null) combination.
### The error may exist in com/qzkj/full/house/dal/dao/UserMapper.java (best guess)
### The error may involve com.qzkj.full.house.dal.dao.UserMapper.insert
### The error occurred while executing an update
### Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '_handledType'. It was either not specified and/or could not be found for the javaType (java.lang.Class) : jdbcType (null) combination.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 81 more
Caused by: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '_handledType'. It was either not specified and/or could not be found for the javaType (java.lang.Class) : jdbcType (null) combination.
	at org.apache.ibatis.mapping.ParameterMapping$Builder.validate(ParameterMapping.java:119)
	at org.apache.ibatis.mapping.ParameterMapping$Builder.build(ParameterMapping.java:104)
	at org.apache.ibatis.builder.SqlSourceBuilder$ParameterMappingTokenHandler.buildParameterMapping(SqlSourceBuilder.java:143)
	at org.apache.ibatis.builder.SqlSourceBuilder$ParameterMappingTokenHandler.handleToken(SqlSourceBuilder.java:87)
	at org.apache.ibatis.parsing.GenericTokenParser.parse(GenericTokenParser.java:77)
	at org.apache.ibatis.builder.SqlSourceBuilder.parse(SqlSourceBuilder.java:50)
	at org.apache.ibatis.scripting.xmltags.DynamicSqlSource.getBoundSql(DynamicSqlSource.java:42)
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:305)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:41)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46)
	at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:690)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at jdk.proxy2/jdk.proxy2.$Proxy144.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	... 85 more

**Comment by nieqiurong** [comment]
提供一下复现工程.

**Comment by xiaoizichao** [comment]
要不你远程我电脑看看 ？项目没上git

**Comment by xzc1-23** [comment]
[full_house.zip](https://github.com/baomidou/mybatis-plus/files/13211883/full_house.zip)

**Comment by xzc1-23** [comment]
User类只要继承EntryPo就会报错 。现在测试用例里头是正常可以插入的，你试试

**Comment by nieqiurong** [comment]
> User类只要继承EntryPo就会报错 。现在测试用例里头是正常可以插入的，你试试

我下载排查看看

**Comment by nieqiurong** [comment]
看着_handledType是你继承SerializableSerializer过来的属性字段.

**Comment by houkunlin** [comment]
我的父类是完全没问题的
![image](https://github.com/baomidou/mybatis-plus/assets/12333292/0ba63efb-3106-4bc9-8f8a-9e4aff04e1d7)

估计是 com.fasterxml.jackson.databind.ser.std.SerializableSerializer 引起的问题
![image](https://github.com/baomidou/mybatis-plus/assets/12333292/04443885-2573-4ee2-a84e-d00bdb2b6196)

**Comment by xzc1-23** [comment]
嗯嗯 ，我看错了 不好意思 。
