### ISSUE TITLE
DbType.LEALONE 该枚举值不存在

### ISSUE THREAD

**Issue by imhager** [baomidou/mybatis-plus#5781]
### 当前使用版本(必填,否则不予处理)

mybatis-plus-generator-3.5.3.2.jar

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

db_query_enum_map.put(DbType.LEALONE, new H2Query())，DbType.LEALONE 不存在

mybatis-plus-generator-3.5.3.1.jar中不存在该枚举类型。但是在mybatis-plus-generator-3.5.3.2.jar中增加了该类型，并且报错了。

### 报错信息
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchFieldError: LEALONE
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096) [spring-webmvc-6.0.12.jar:6.0.12]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) [spring-webmvc-6.0.12.jar:6.0.12]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) [spring-webmvc-6.0.12.jar:6.0.12]
Caused by: java.lang.NoSuchFieldError: LEALONE
	at com.baomidou.mybatisplus.generator.config.querys.DbQueryRegistry.<init>(DbQueryRegistry.java:40) ~[mybatis-plus-generator-3.5.4.1.jar:3.5.4.1]
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbQuery(DataSourceConfig.java:136) ~[mybatis-plus-generator-3.5.4.1.jar:3.5.4.1]
	at com.github.davidfantasy.mybatisplus.generatorui.dbquery.DbQueryHolder.getDbQuery(DbQueryHolder.java:32) ~[mybatis-plus-generator-ui-2.0.5.jar:?]

**Comment by nieqiurong** [comment]
看mybatis-plus-generator-ui 带的是3.5.3.1. 应该是你自行升级导致依赖冲突的问题,检查 mybatis-plus-annotation 的版本.

**Comment by imhager** [comment]
> 看mybatis-plus-generator-ui 带的是3.5.3.1. 应该是你自行升级导致依赖冲突的问题,检查 mybatis-plus-annotation 的版本.

ok ,thx
