### ISSUE TITLE
jdk17 savebatch问题

### ISSUE THREAD

**Issue by itapechang** [baomidou/mybatis-plus#5804]
### 当前使用版本(必填,否则不予处理)
 3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在savebatch时候出现空指针异常

### 重现步骤(如果有就写完整)
 异常信息太少，很难定位

### 报错信息
com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: java.lang.NullPointerException
    at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:59)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:197)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:217)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.saveOrUpdateBatch(SqlHelper.java:247)
    at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveOrUpdateBatch(ServiceImpl.java:177)
    at com.baomidou.mybatispl

**Comment by huayanYu** [comment]
是必现?

**Comment by itapechang** [comment]
> 是必现?

是必现的，看着像是反射引起的，classloader加载出现空指针

**Comment by nieqiurong** [comment]
适配高版本在3.5.3.2后面的版本才解决,如果无法确定异常堆栈,升级版本或者使用1.8看是否还出现此问题.

**Comment by itapechang** [comment]
> 适配高版本在3.5.3.2后面的版本才解决,如果无法确定异常堆栈,升级版本或者使用1.8看是否还出现此问题.

升级 3.5.3.2还是有相同的问题：

com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
    at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:59)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:205)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:231)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:226)
    at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.saveOrUpdateBatch(SqlHelper.java:261)

**Comment by nieqiurong** [comment]
> > 适配高版本在3.5.3.2后面的版本才解决,如果无法确定异常堆栈,升级版本或者使用1.8看是否还出现此问题.
> 
> 升级 3.5.3.2还是有相同的问题：
> 
> com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:59) at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:205) at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:231) at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.executeBatch(SqlHelper.java:226) at com.baomidou.mybatisplus.extension.toolkit.SqlHelper.saveOrUpdateBatch(SqlHelper.java:261)

提供复现工程上来看看.
