### ISSUE TITLE
Bean named 'ddlApplicationRunner' is expected to be of type 'org.springframework.boot.Runner' but was actually of type 'org.springframework.beans.factory.support.NullBean'

### ISSUE THREAD

**Issue by thousmile** [baomidou/mybatis-plus#5874]
### 当前使用版本(必填,否则不予处理)
mybatis-plus version 3.5.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
yes

### 重现步骤(如果有就写完整)

update to spring boot 3.1.7 version resulted in

### 报错信息

2023-12-23T17:52:13.354+08:00 ERROR 3984 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'ddlApplicationRunner' is expected to be of type 'org.springframework.boot.Runner' but was actually of type 'org.springframework.beans.factory.support.NullBean'
	at org.springframework.beans.factory.support.AbstractBeanFactory.adaptBeanInstance(AbstractBeanFactory.java:407) ~[spring-beans-6.0.15.jar:6.0.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:388) ~[spring-beans-6.0.15.jar:6.0.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-6.0.15.jar:6.0.15]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:762) ~[spring-boot-3.1.7.jar:3.1.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) ~[spring-boot-3.1.7.jar:3.1.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1321) ~[spring-boot-3.1.7.jar:3.1.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1310) ~[spring-boot-3.1.7.jar:3.1.7]
	at com.xaaef.molly.MollyApplication.main(MollyApplication.java:32) ~[classes/:na]

**Comment by LJiangTao** [comment]
upgrade to latest 3.5.5 or later version.
link to issus: #5867

**Comment by LJiangTao** [comment]
upgrade to the latest 3.5.5 or latest version.
link issue: #5867

**Comment by hcxin** [comment]
Please try this dependency:
```
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>3.5.5</version>
            </dependency>
```

**Comment by arnolddeng2020** [comment]
> Please try this dependency:
> 
> ```
>             <dependency>
>                 <groupId>com.baomidou</groupId>
>                 <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
>                 <version>3.5.5</version>
>             </dependency>
> ```
这个版本跟 sping boot starter 3.2.1可以正常运行
