### ISSUE TITLE
mybatis-plus-generator能否支持opengauss数据库驱动

### ISSUE THREAD

**Issue by qq947075078** [baomidou/mybatis-plus#5901]
### 当前使用版本(必填,否则不予处理)

3.5.4

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:opengauss://xxxx/xxx?currentSchema=xxx
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getConn(DataSourceConfig.java:238)
	... 9 more

**Comment by huayanYu** [comment]
提交PR

**Comment by nieqiurong** [comment]
No suitable driver found for jdbc:opengauss:    要么驱动没引入要么jdbc的url地址写的有问题
