### ISSUE TITLE
在使用graalvm的native构建本地镜像启动报错

### ISSUE THREAD

**Issue by zcdcx** [baomidou/mybatis-plus#5912]
### 当前使用版本(必填,否则不予处理)
3.5.5

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在使用graalvm的native构建本地镜像启动报错

### 重现步骤(如果有就写完整)

打包命令: mvn clean package -Pnative -DskipTests & mvn native:compile-no-fork

### 报错信息
2024-01-06 09:55:23.265  [main] [] [org.springframework.boot.SpringApplication] 
ERROR: Application run failed
java.lang.ExceptionInInitializerError: null
	at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:363)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:148)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:789)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:464)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
	at org.zcdcx.template.Spring3TemplateMavenApplication.main(Spring3TemplateMavenApplication.java:11)
	at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: org.apache.ibatis.logging.LogException: Error creating logger for logger org.mybatis.spring.mapper.ClassPathMapperScanner.  Cause: java.lang.NullPointerException
	at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:54)
	at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:47)
	at org.mybatis.logging.LoggerFactory.getLogger(LoggerFactory.java:32)
	at org.mybatis.spring.mapper.ClassPathMapperScanner.<clinit>(ClassPathMapperScanner.java:60)
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:52)
	... 16 common frames omitted

**Comment by nieqiurong** [comment]
先去按这个例子跑起来  https://github.com/nieqiurong/mybatis-native-demo

**Comment by zcdcx** [comment]
> 先去按这个例子跑起来 https://github.com/nieqiurong/mybatis-native-demo

已经按照这个例子配置了那个config跑起来了
