### ISSUE TITLE
sqlserver批量插入list报错

### ISSUE THREAD

**Issue by guiqulaici** [baomidou/mybatis-plus#595]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
单元测试sqlserver批量插入list报错，entity字段id为IdType.AUTO，经过跟踪代码，发现调用时用了自增的Jdbc3KeyGenerator，将Generator改为NoKeyGenerator，跳过回写id，但是数据还是未commit到数据库。不清楚是什么原因？
![image](https://user-images.githubusercontent.com/11836445/47773112-f9d6d500-dd23-11e8-905c-0207453c9a9b.png)

### 重现步骤
调用service类的saveBatch方法

### 报错信息
Caused by: org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:83)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:128)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.CachingExecutor.flushStatements(CachingExecutor.java:114)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:253)
	... 38 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 必须执行该语句才能获得结果。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getGeneratedKeys(SQLServerStatement.java:2040)
	at com.alibaba.druid.pool.DruidPooledStatement.getGeneratedKeys(DruidPooledStatement.java:821)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:63)
	... 43 more

**Comment by guiqulaici** [comment]
已处理，需要手动commit
![image](https://user-images.githubusercontent.com/11836445/47777624-18db6400-dd30-11e8-8f84-16036bf0f7eb.png)

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`

**Comment by miemieYaho** [comment]
你数据库连接信息没设置自动 commit 把

**Comment by xie-summer** [comment]
没有，感谢，我再试试

**Comment by xie-summer** [comment]
![image](https://user-images.githubusercontent.com/27772586/50816877-eae05480-135c-11e9-8dee-76e29ff90472.png)
@miemieYaho  设置了自动commit ,但是还是失败了，我用的动态数据源

**Comment by miemieYaho** [comment]
动态的就自己排查
