### ISSUE TITLE
mysql，service执行批量插入报错

### ISSUE THREAD

**Issue by cc-cfg** [baomidou/mybatis-plus#597]
### 当前使用版本(必须填写清楚，否则不予处理)
当前版本 3.0.5

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
    storeService.insertBatch(storeList);    执行批量插入异常  ，insert执行正常

### 重现步骤
部分代码如下：

    @Autowired
    StoreService storeService ;

                    List<Store> storeList = new ArrayList<>();
                    Store store = new Store();
                    store.setStoreCount(111);

                    Store store2 = new Store();
                    store2.setStoreCount(22);
                    storeList.add(store);
                    storeList.add(store2);
                    storeService.insertBatch(storeList);

接口：
public interface StoreService extends IService<Store> {}

实体：
@TableName("dc_store")
public class Store implements Serializable {

plus配置  有两个数据源 一个日志数据库 ，一个业务数据库  

### 报错信息

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.gw.dc.persist.dao.businessdatasource.StoreMapper.insert
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:130)
	... 106 more
Caused by: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.gw.dc.persist.dao.businessdatasource.StoreMapper.insert
	at org.apache.ibatis.session.Configuration$StrictMap.get(Configuration.java:888)
	at org.apache.ibatis.session.Configuration.getMappedStatement(Configuration.java:721)
	at org.apache.ibatis.session.Configuration.getMappedStatement(Configuration.java:714)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 108 more

**Comment by cc-cfg** [comment]
去除日志数据源，批量插入正常，   那问题来了，  如何在使用两个数据源的情况下，执行service的批量插入

**Comment by huayanYu** [comment]
试试官方的https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter

**Comment by cc-cfg** [comment]
还是不行  ，难过

**Comment by huayanYu** [comment]
没遇到过，建议给出能复现的代码。

**Comment by dchack** [comment]
这问题怎么没个定论就关了？

**Comment by huayanYu** [comment]
@dchack  你能复现了这个问题？可以快速基于 https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter/tree/master/samples 的示例代码，快速构建一个环境。给一份能复现的代码。

**Comment by Burt-L** [comment]
遇到同样问题，当前是手写batch操作。。。
