### ISSUE TITLE
quarkus使用mybatis-plus简单查询（通过id查询表数据）报错找不到类：org/springframework/core/convert/support/DefaultConversionService

### ISSUE THREAD

**Issue by chenfromsz** [baomidou/mybatis-plus#6001]
### 当前使用版本(必填,否则不予处理)
quarkus version：3.8.1
mybatis-plus version：2.2.2
<dependency>
            <groupId>io.quarkiverse.mybatis</groupId>
            <artifactId>quarkus-mybatis-plus</artifactId>
            <version>2.2.2</version>
      </dependency>

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
<dependency>
            <groupId>io.quarkiverse.mybatis</groupId>
            <artifactId>quarkus-mybatis-plus</artifactId>
            <version>2.2.2</version>
        </dependency>

### 重现步骤(如果有就写完整)
源代码ServiceImpl
（package com.baomidou.mybatisplus.extension.service.impl.ServiceImpl）
有相关springframework的引用，于是找不到相关引用而报错：
......
import org.springframework.aop.framework.AopProxyUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.ConversionService;
import org.springframework.core.convert.support.DefaultConversionService;
import org.springframework.transaction.annotation.Transactional;

### 报错信息
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] :
java.lang.NoClassDefFoundError: org/springframework/core/convert/support/DefaultConversionService
        at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.<init>(ServiceImpl.java:62)
        at com.datas.service.impl.PermissionServiceImpl.<init>(PermissionServiceImpl.java:22)
        at com.datas.service.impl.PermissionServiceImpl_Bean.doCreate(Unknown Source)
        at com.datas.service.impl.PermissionServiceImpl_Bean.create(Unknown Source)
        at com.datas.service.impl.PermissionServiceImpl_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
        at com.datas.service.impl.PermissionServiceImpl_Bean.get(Unknown Source)
        at com.datas.service.impl.PermissionServiceImpl_Bean.get(Unknown Source)
        at com.datas.resource.PermissionResource_Bean.doCreate(Unknown Source)
        at com.datas.resource.PermissionResource_Bean.create(Unknown Source)
        at com.datas.resource.PermissionResource_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
        at com.datas.resource.PermissionResource_Bean.get(Unknown Source)
        at com.datas.resource.PermissionResource_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:554)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:534)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:567)
        at io.quarkus.arc.impl.ArcContainerImpl$3.get(ArcContainerImpl.java:331)
        at io.quarkus.arc.impl.ArcContainerImpl$3.get(ArcContainerImpl.java:328)
        at io.quarkus.arc.runtime.BeanContainerImpl$1.create(BeanContainerImpl.java:58)
        at io.quarkus.resteasy.reactive.common.runtime.ArcBeanFactory.createInstance(ArcBeanFactory.java:27)
        at org.jboss.resteasy.reactive.server.handlers.InstanceHandler.handle(InstanceHandler.java:26)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:139)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.convert.support.DefaultConversionService
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        ... 43 more

**Comment by miemieYaho** [comment]
2.x的mp不再维护了

**Comment by nieqiurong** [comment]
ServiceImpl不是给quarkus用的
