### ISSUE TITLE
文档打不开，浏览器调试窗口console报错

### ISSUE THREAD

**Issue by a1369213361** [baomidou/mybatis-plus#6088]
### 当前使用版本(必填,否则不予处理)

https://mybatis.plus/guide/generator.html

### 报错信息
打开：https://mybatis.plus/guide/generator.html

OMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:40618)
    at d (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:53352)
    at https://mybatis.plus/assets/js/app.a3d46bc0.js:8:52615
    at f (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:52847)
    at h (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:53438)
    at P (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:56776)
    at a.__patch__ (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:57176)
    at t._update (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:34410)
    at a.r (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:64492)
    at hn.get (https://mybatis.plus/assets/js/app.a3d46bc0.js:8:26686)
Wt @ app.a3d46bc0.js:8
12Third-party cookie will be blocked. Learn more in the Issues tab.
ads:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()

**Comment by miemieYaho** [comment]
https://baomidou.com/
