### ISSUE TITLE
达梦数据库无法匹配到owner=‘%s’ 问题

### ISSUE THREAD

**Issue by matry521** [baomidou/mybatis-plus#6109]
### 当前使用版本(必填,否则不予处理)
3.5.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
达梦数据库链接，走DMQuery后，无法进行替换掉owner='%s'内容
![1714299191849](https://github.com/baomidou/mybatis-plus/assets/19566560/3915ad5f-61b9-4cbf-a0c5-f5c1fc658707)
此处不支持

### 重现步骤(如果有就写完整)
DataSourceConfig.Builder builder1 = new DataSourceConfig.Builder(xxx,xxx,xx)
builder1.schema("xxxx");
  builder1.dbQuery(new DMQuery());
  builder1.typeConvert(new DmTypeConvert());
  builder1.databaseQueryClass(SQLQuery.class);
 FastAutoGenerator
                .create(builder1)

### 报错信息
Exception in thread "main" java.lang.RuntimeException: 无法创建文件，请检查配置信息！
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:259)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:185)
	at com.baomidou.mybatisplus.generator.FastAutoGenerator.execute(FastAutoGenerator.java:239)
	at com.xinj.oil.config.CodeGenerator.main(CodeGenerator.java:99)
Caused by: java.lang.RuntimeException: dm.jdbc.driver.DMException: 第1 行附近出现错误:
无效的列名[owner]
	at com.baomidou.mybatisplus.generator.query.SQLQuery.queryTables(SQLQuery.java:88)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTableInfoList(ConfigBuilder.java:162)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:240)
	... 3 more
Caused by: dm.jdbc.driver.DMException: 第1 行附近出现错误:
无效的列名[owner]
	at dm.jdbc.driver.DBError.throwException(DBError.java:635)
	at dm.jdbc.c.a.n.J(MSG.java:221)
	at dm.jdbc.c.a.n.G(MSG.java:181)
	at dm.jdbc.c.a.n.F(MSG.java:162)
	at dm.jdbc.c.a.a(DBAccess.java:759)
	at dm.jdbc.c.a.a(DBAccess.java:186)
	at dm.jdbc.driver.DmdbPreparedStatement.prepareSql(DmdbPreparedStatement.java:150)
	at dm.jdbc.driver.DmdbPreparedStatement.<init>(DmdbPreparedStatement.java:120)
	at dm.jdbc.driver.DmdbConnection.do_prepareStatement(DmdbConnection.java:721)
	at dm.jdbc.driver.DmdbConnection.do_prepareStatement(DmdbConnection.java:707)
	at dm.jdbc.driver.DmdbConnection.prepareStatement(DmdbConnection.java:1312)
	at com.baomidou.mybatisplus.generator.config.querys.DbQueryDecorator.execute(DbQueryDecorator.java:193)
	at com.baomidou.mybatisplus.generator.query.SQLQuery.queryTables(SQLQuery.java:66)
	... 5 more
Disconnected from the target VM, address: '127.0.0.1:53193', transport: 'socket'

**Comment by matry521** [comment]
不应该出现这个owner field才对吧？

**Comment by nieqiurong** [comment]
用 3.5.7-SNAPSHOT 试试

**Comment by matry521** [comment]
@nieqiurong  麻烦发布一下3.5.7-SNAPSHOT 呢，仓库找不到该版本

**Comment by nieqiurong** [comment]
https://baomidou.com/pages/bab2db/#snapshot
