### ISSUE TITLE
使用 UUID 和  BINARY 关联映射 QueryWrapper queryTotal execution error

### ISSUE THREAD

**Issue by craone** [baomidou/mybatis-plus#625]
### 当前使用版本(必须填写清楚，否则不予处理)
```groovy
implementation("com.baomidou:mybatis-plus-boot-starter:3.0.5")
```

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**

`UUIDTypeHandler` 也写好了，查找所有，保存都正常，但通过条件查找时就 `QueryWrapper` 生成的条件查找时就报 插入参数错误

### 重现步骤
domain 字段映射
```kotlin
@TableField(value = "anonymous_user",el = "anonymousUser ,jdbcType=BINARY ,javaType=java.util.UUID")
//  bug 通过 annotation 注册handler 查找映射成功 保存 接口不走 映射失败
//  @TableField(value = "anonymous_user",el = "anonymousUser ,jdbcType=BINARY ,javaType=java.util.UUID  ,typeHandler=type.handlers.UUIDTypeHandler") 
var anonymousUser: UUID? = null,
```
service 方法内组装条件查找
```kotlin
val queryWrapper = QueryWrapper<QueueNumber>()
               .eq("anonymous_user", queueNumber.anonymousUser)
               .eq("department_id", department.id)
               .orderByDesc("create_time")
val queueNumberPage = queueNumberMapper.selectPage(page, queryWrapper)
```
application.yml
```yml
#  bug 只能 yml 注册handler 查找保存 映射成功 
type-handlers-package: type.handlers
```
UUIDTypeHandler
```kotlin
class UUIDTypeHandler : BaseTypeHandler<UUID>() {

    @Throws(SQLException::class)
    override fun setNonNullParameter(ps: PreparedStatement, i: Int, parameter: UUID, jdbcType: JdbcType) {
        ps.setBytes(i, parameter.asBytes())
    }

    @Throws(SQLException::class)
    override fun getNullableResult(rs: ResultSet, columnName: String): UUID? {
        return rs.getBytes(columnName)?.asUUID()
    }

    @Throws(SQLException::class)
    override fun getNullableResult(rs: ResultSet, columnIndex: Int): UUID? {
        return rs.getBytes(columnIndex)?.asUUID()
    }

    @Throws(SQLException::class)
    override fun getNullableResult(cs: CallableStatement, columnIndex: Int): UUID? {
        return cs.getBytes(columnIndex)?.asUUID()
    }
}
```
### 报错信息
``` error
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error.
### The error may exist in scheduling/system/mapper/QueueNumberMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error.",
    "trace": "org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
	### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error.
	### The error may exist in scheduling/system/mapper/QueueNumberMapper.java (best guess)
	### The error may involve defaultParameterMap
	### The error occurred while setting parameters
	### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy72.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany2(PageMapperMethod.java:128)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:98)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy78.selectPage(Unknown Source)
```

**Comment by miemieYaho** [comment]
使用 QueryWrapper  构建查询条件,和你在model里注解的任何东西都无关

**Comment by craone** [comment]
谢谢提醒
```kotlin
.eq("anonymous_user", queueNumber.anonymousUser?.asBytes())
```
这样子就可以了

**Comment by coder8421** [comment]
我也遇到 同样的报错  目前没有解决
