### ISSUE TITLE
springboot3+jdk17 未适配完成

### ISSUE THREAD

**Issue by lzzkey** [baomidou/mybatis-plus#6287]
**当前使用版本**
springboot  3.0.4
mybatis-plus 3.5.7
**当前环境信息**
例如: Java17 + Mysql5.7

**描述bug现象**
springboot3 + mybatis-plus 3.5.7   ,启动报错

jvm 启动加入  --add-opens java.base/java.lang.reflect=ALL-UNNAMED 才能正常启动
**提供问题复现步骤**

**提供完整堆栈日志(可选)**

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.reflect.InvocationHandler java.lang.reflect.Proxy.h accessible: module java.base does not "opens java.lang.reflect" to unnamed module @7bb58ca3
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:212)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	... 162 more

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by twocold0451** [comment]
最后怎么解决的呢
