### ISSUE TITLE
逻辑删除插件导致Jsql解析错误

### ISSUE THREAD

**Issue by chasonHgg** [baomidou/mybatis-plus#6328]
**当前使用版本**
3.5.5
**当前环境信息**
例如: Java8 + Mysql5.7

**描述bug现象**
通过源码查询到，逻辑删除插件,会在sql后面多加了很多\n导致，JsqlParserGlobal.parse异常

**提供问题复现步骤**
<img width="965" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/168900242/748607e2-9e5f-445d-a27d-808d8bb5a9b8">

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.
升级jsqlparser为5.0可以解决问题

**Comment by chasonHgg** [comment]
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT  
cc_project.name,cc_project.team_id,cc_project.tenant_id,cc_project.is_del,cc_project.gmt_update,cc_project.gmt_create,cc_project.id, cc_team.name  cc_team_name , cc_team.tenant_id  cc_team_tenantId , cc_team.is_del  cc_team_isDel , cc_team.gmt_update  cc_team_gmtUpdate , cc_team.gmt_create  cc_team_gmtCreate , cc_team.id  cc_team_id 
  FROM  cc_project  cc_project   LEFT JOIN cc_team  cc_team ON cc_team.id = cc_project.team_id 
 AND cc_team.is_del=0
 
 WHERE  cc_project.is_del=0



 
 ORDER BY cc_project.id DESC
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:51)
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:72)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy183.query(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at icu.mhb.mybatisplus.plugln.interceptor.JoinInterceptor.intercept(JoinInterceptor.java:85)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy183.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	... 114 common frames omitted
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ORDER" "ORDER"
    at line 11, column 2.

Was expecting:

    <EOF>

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserGlobal.parse(JsqlParserGlobal.java:43)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:48)
	... 127 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "ORDER" "ORDER"
    at line 11, column 2.

Was expecting:

    <EOF>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:38866)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:38696)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:306)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 common frames omitted

**Comment by chasonHgg** [comment]
升级jsqlparser为5.0
