### ISSUE TITLE
[错误报告]: 描述 net.sf.jsqlparser.parser.CCJSqlParserUtil#parseStatement 解析sql 超时，默认时间是 6秒

### ISSUE THREAD

**Issue by elcnu986** [baomidou/mybatis-plus#6392]
### 确认

- [ ] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [x] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [x] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.3.2

### 问题描述

net.sf.jsqlparser.parser.CCJSqlParserUtil#parseStatement
这个方法是通过 线程异步解析sql 的，但是 超时时间 6000 ms 是写死的，无法修改，应该如何解析

### 详细堆栈日志

```bash
at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39) ~[mybatis-plus-core-3.5.3.2.jar:3.5.3.2]
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:51) ~[mybatis-plus-extension-3.5.3.2.jar:3.5.3.2]
	at com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor.beforeQuery(TenantLineInnerInterceptor.java:72) ~[mybatis-plus-extension-3.5.3.2.jar:3.5.3.2]
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:78) ~[mybatis-plus-extension-3.5.3.2.jar:3.5.3.2]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59) ~[mybatis-3.5.13.jar:3.5.13]
	at com.sun.proxy.$Proxy491.query(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154) ~[mybatis-3.5.13.jar:3.5.13]
	... 125 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:203) ~[na:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:258) ~[jsqlparser-4.6.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:81) ~[jsqlparser-4.6.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:47) ~[jsqlparser-4.6.jar:na]
	at com.baomidou.mybatisplus.extension.parser.JsqlParserGlobal.parse(JsqlParserGlobal.java:39) ~[mybatis-plus-extension-3.5.3.2.jar:3.5.3.2]
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:48) ~[mybatis-plus-extension-3.5.3.2.jar:3.5.3.2]
	... 130 common frames omitted
```

**Comment by miemieYaho** [comment]
JsqlParserGlobal设置

**Comment by elcnu986** [comment]
> JsqlParserGlobal设置

这个咋改啊？没找到地方啊？
