### ISSUE TITLE
[错误报告]: 使用LambdaQueryWrapper中出现can not find lambda cache for this property

### ISSUE THREAD

**Issue by redcarp666** [baomidou/mybatis-plus#6400]
### 确认

- [ ] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.1

### 问题描述

代码如下, Entity是有effectiveStartTime的
```
public class EmConversionCoefficient extends BaseEntity {
	@ApiModelProperty(value = "名称")
	private String name;
	@ApiModelProperty(value = "生效开始月份")
	@JsonFormat(pattern = "yyyy-MM")
	private String effectiveStartTime;
	@ApiModelProperty(value = "生效结束月份")
	@JsonFormat(pattern = "yyyy-MM")
	private String effectiveEndTime;
	@ApiModelProperty(value = "组织ids（以英文逗号间隔）")
	private String refOrgIds;
	@ApiModelProperty(value = "备注")
	private String remark;
	@ApiModelProperty(value = "是否删除")
	@TableLogic
	@TableField(fill = FieldFill.INSERT)
	private Integer deleted = 0;
}
```
```
private LambdaQueryWrapper<EmConversionCoefficient> getQueryWrapper(EmConversionCoefficientVo.EmConversionCoefficientPageListInput input) {
		LambdaQueryWrapper<EmConversionCoefficient> wrapper = getBaseWrapper(input);
		wrapper.like(StringUtils.isNotEmpty(input.getName()),
		             EmConversionCoefficient::getName,
		             IbfStringUtil.replaceSpecialCharOfLike(input.getName()));
		wrapper.le(null != input.getEffectiveEndTime(),
		           EmConversionCoefficient::getEffectiveStartTime,
		           input.getEffectiveEndTime());
		wrapper.ge(null != input.getEffectiveStartTime(),
		           EmConversionCoefficient::getEffectiveEndTime,
		           input.getEffectiveStartTime());
		return wrapper;
	}
```
```
default <Input extends BaseQueryInput> LambdaQueryWrapper<T> getBaseWrapper(Input input) {
        LambdaQueryWrapper<T> wrapper = Wrappers.lambdaQuery();
	    wrapper.like(ObjectUtil.isNotEmpty(input.getCreator()), BaseEntity::getCreator, input.getCreator()).like(
			    ObjectUtil.isNotEmpty(input.getModifier()),
			    BaseEntity::getModifier,
			    input.getModifier());
	    wrapper.between(ObjectUtil.isNotEmpty(input.getCreateStartTime()) && ObjectUtil.isNotEmpty(input.getCreateEndTime()),
	                    BaseEntity::getCreateTime,
	                    input.getCreateStartTime(),
	                    EmDateUtil.endOfDay(input.getCreateEndTime()));
	    wrapper.between(ObjectUtil.isNotEmpty(input.getModifyStartTime()) && ObjectUtil.isNotEmpty(input.getModifyEndTime()),
	                    BaseEntity::getModifyTime,
	                    input.getModifyStartTime(),
	                    EmDateUtil.endOfDay(input.getModifyEndTime()));
        return wrapper;
    }
```

### 详细堆栈日志

```bash
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression 'ew.sqlSegment != null and ew.sqlSegment != '' and ew.nonEmptyOfNormal'. Cause: org.apache.ibatis.ognl.OgnlException: sqlSegment [com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: can not find lambda cache for this property [effectiveStartTime] of entity [cn.zjky.ibf.em.bim.entity.EmConversionCoefficient]]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy144.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:121)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:85)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy172.selectPage(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.page(IService.java:389)
```

**Comment by miemieYaho** [comment]
你有basemapper< EmConversionCoefficient >并且被正确加载了吗?

**Comment by redcarp666** [comment]
> 你有basemapper< EmConversionCoefficient >并且被正确加载了吗?

```
@Mapper
public interface EmConversionCoefficientMapper extends BaseMapper<EmConversionCoefficient> {

}
```
@miemieYaho 有的

**Comment by miemieYaho** [comment]
那你`Wrappers.lambdaQuery(EmConversionCoefficient.class)`

**Comment by redcarp666** [comment]
> 那你`Wrappers.lambdaQuery(EmConversionCoefficient.class)`

- 这样是可以，那就是得传LambdaQueryWrapper参数进去了。
- <img width="1060" alt="image" src="https://github.com/user-attachments/assets/a98ded41-3a72-4128-9eac-385aeb89e703">


- 使用时，必须在后面拼接上公共条件的字段才不会报错。
- <img width="1154" alt="image" src="https://github.com/user-attachments/assets/3bcd123f-4e6f-4b17-8530-b184856a1f83">

**Comment by nieqiurong** [comment]
也可以改成一下传入子类类型创建或者通过父类初始化的QueryWrapper后回来在setEntityClass一下

**Comment by mniwjb** [comment]
升级到3.5.4就好了
