### ISSUE TITLE
[错误报告]: 描述3.5.7版本的generator报找不到驱动

### ISSUE THREAD

**Issue by f1024557668** [baomidou/mybatis-plus#6414]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

通过FastAutoGenerator.create方法进行创建，但是builder中根本没有driverName方法，看过官网文档，是现在必须要手动自己根据连接类型判断使用MysqlQuery还是其它数据库Query吗？我看那些Query类里也没有driverName。很困惑，网上搜到的，好像以前版本是可以手动设置driverName的。

### 详细堆栈日志

```bash
Caused by: java.lang.RuntimeException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getConn(DataSourceConfig.java:253)
	at com.baomidou.mybatisplus.generator.query.DefaultQuery.<init>(DefaultQuery.java:57)
	... 119 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getConn(DataSourceConfig.java:241)
	... 120 more
```

**Comment by nieqiurong** [comment]
自行引入mysql驱动包.

**Comment by f1024557668** [comment]
> 自行引入mysql驱动包.

驱动包是引入的，目前解决方法就是自己在调用生成代码前手动把驱动加载进去。觉得有点无奈。没有发现接口文档里有处理类似的情况的方法。反正自己算解决吧。只是没想通为啥要把驱动注册的过程交给调用方来手动处理。

**Comment by nieqiurong** [comment]
符合jdbc4.0的驱动是不再需要显示加载驱动的.
