### ISSUE TITLE
[错误报告]: 描述DataChangeRecorderInnerInterceptor解析Instant类型数据时报错

### ISSUE THREAD

**Issue by DavidFengZiYang** [baomidou/mybatis-plus#6420]
### 确认

- [X] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

实体参数类型是Instant时候，PgResultSet的getObject(int columnIndex, Class<T> type)方法里没有针对Instant类型的处理

### 详细堆栈日志

```bash
c.b.m.e.p.i.DataChangeRecorderInnerInterceptor[buildOriginalObjectData,577] - try to get record tobe updated for selectStmt= *** org.postgresql.util.PSQLException: conversion to class java.time.Instant from timestamptz not supported
at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3874)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getObject(HikariProxyResultSet.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.ibatis.logging.jdbc.ResultSetLogger.invoke(ResultSetLogger.java:68)
	at jdk.proxy3/jdk.proxy3.$Proxy220.getObject(Unknown Source)
	at com.baomidou.mybatisplus.extension.plugins.inner.DataChangeRecorderInnerInterceptor.prepareOriginalDataObj(DataChangeRecorderInnerInterceptor.java:637)
	at com.baomidou.mybatisplus.extension.plugins.inner.DataChangeRecorderInnerInterceptor.buildOriginalObjectData(DataChangeRecorderInnerInterceptor.java:567)
	at com.baomidou.mybatisplus.extension.plugins.inner.DataChangeRecorderInnerInterceptor.processUpdate(DataChangeRecorderInnerInterceptor.java:244)
	at com.baomidou.mybatisplus.extension.plugins.inner.DataChangeRecorderInnerInterceptor.beforePrepare(DataChangeRecorderInnerInterceptor.java:153)
	at io.haina.core.database.interceptor.HaInaMybatisPlusInterceptor.intercept(HaInaMybatisPlusInterceptor.java:142)
```

**Comment by nieqiurong** [comment]
#6430
