### ISSUE TITLE
[错误报告]: 描述 代码生成器，设置.entityBuilder().superClass() 后，启动报错

### ISSUE THREAD

**Issue by TryCatchCat** [baomidou/mybatis-plus#6451]
### 确认

- [x] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [ ] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [ ] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

V3.5.7

### 问题描述

代码生成器，设置.entityBuilder().superClass() 后，启动报错
        FastAutoGenerator.create(url, name, password)
                        .strategyConfig(builder -> {
                            builder.entityBuilder()
                                    .superClass(xxx.class);
                        });

### 详细堆栈日志

```bash
Exception in thread "main" java.lang.RuntimeException: 无法创建文件，请检查配置信息！
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:258)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:179)
	at com.baomidou.mybatisplus.generator.FastAutoGenerator.execute(FastAutoGenerator.java:213)
	at com.izkml.mlyun.office.equip.mybatisplus.MyGeneratorTest.main(MyGeneratorTest.java:149)
Caused by: java.lang.NullPointerException
	at com.baomidou.mybatisplus.core.metadata.TableInfoHelper.getAllFields(TableInfoHelper.java:594)
	at com.baomidou.mybatisplus.generator.config.builder.Entity.convertSuperEntityColumns(Entity.java:192)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.baomidou.mybatisplus.generator.config.builder.Entity$Builder.get(Entity.java:627)
	at com.baomidou.mybatisplus.generator.config.StrategyConfig.entity(StrategyConfig.java:152)
	at com.baomidou.mybatisplus.generator.config.po.TableInfo.<init>(TableInfo.java:136)
	at com.baomidou.mybatisplus.generator.IDatabaseQuery$DefaultDatabaseQuery.lambda$queryTables$0(IDatabaseQuery.java:116)
	at com.baomidou.mybatisplus.generator.config.querys.DbQueryDecorator.execute(DbQueryDecorator.java:196)
	at com.baomidou.mybatisplus.generator.IDatabaseQuery$DefaultDatabaseQuery.queryTables(IDatabaseQuery.java:113)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTableInfoList(ConfigBuilder.java:139)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:240)
	... 3 more
```

**Comment by TryCatchCat** [comment]
#6216
