### ISSUE TITLE
[错误报告]: 描述解析SQL报错

### ISSUE THREAD

**Issue by newbirdking** [baomidou/mybatis-plus#6535]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.2

### 问题描述

查询语句
![image](https://github.com/user-attachments/assets/c11b64bd-9639-4b9d-99bf-bb0f7cf0e95e)
会报错;
![image](https://github.com/user-attachments/assets/4b739715-bf88-44aa-9633-500d737bd846)
但是如果改成sys_user_role sr 
就OK

### 详细堆栈日志

```bash
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: select distinct u.user_id
             , u.dept_code
             , d.dept_name
             , u.user_name
             , u.nick_name
        from sys_user u
                 left join sys_dept d on u.dept_code = d.dept_code and d.del_flag = '0'
                 left join sys_user_role as ur on u.user_id = ur.user_id
                 left join sys_role r on r.role_id = ur.role_id and r.del_flag = '0'
                 left join sys_user_hospital b on u.user_name=b.user_name and b.del_flag ='0'
         WHERE  r.role_key in
                (
                    ?
                )
            
        and u.del_flag = '0'
        and u.status = '0'
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:52)
CCJSqlParser 4.4
```

**Comment by miemieYaho** [comment]
CCJSqlParser
