### ISSUE TITLE
[错误报告]: 描述

### ISSUE THREAD

**Issue by 00booker** [baomidou/mybatis-plus#6618]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.9

### 问题描述

![image](https://github.com/user-attachments/assets/be5b8aa7-f216-4f85-8d61-6d7bcf36a1d8)
这一点getOne()方法我在使用中发现，如果数据库中返回多条数据的话并不会在SQL中自动添加LIMIT 1，需要我们自己在wrapper里手动添加.last("LIMIT 1");

### 详细堆栈日志

```bash
2024-11-30 11:29:08.472 ERROR [nio-8003-exec-1] c.s.b.f.e.GlobalExceptionHandler         [72] 1862700360200634370 : exception:

org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 13
	at com.baomidou.mybatisplus.core.mapper.BaseMapper.selectOne(BaseMapper.java:177)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:162)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy128.selectOne(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.getOne(ServiceImpl.java:202)
	at com.baomidou.mybatisplus.extension.service.IService.getOne(IService.java:320)
	at com.baomidou.mybatisplus.extension.service.IService$$FastClassBySpringCGLIB$$f8525d18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
```

**Comment by miemieYaho** [comment]
不会自动加limit,文档有误

**Comment by yangyang0507** [comment]
文档问题，已经处理
