### ISSUE TITLE
[错误报告]: mybatis plus 连接达梦数据库，分页查询报错

### ISSUE THREAD

**Issue by yasuo-deng** [baomidou/mybatis-plus#6622]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.3.2

### 问题描述

![image](https://github.com/user-attachments/assets/091e1134-6395-4a77-b04a-f9e2f0604921)
分页查询的时候，查询count报错 ,mp 版本号3.3.2   达梦驱动版本号8.1.1.193

### 详细堆栈日志

```bash
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM t_question_answer tqa INNER JOIN t_document td ON tqa.document_id = td.id AND td.deleted = 0 WHERE tqa.deleted = 0 AND ((td.standard_id IS NOT NULL AND td.standard_id != '' AND td.security_level <= ? + 3) OR ((td.standard_id IS NULL OR td.standard_id = '') AND td.security_level <= ? + 3)) AND td.name = ? 

### The error may exist in file [D:\code\gitlab\huazhi-ai-api\target\classes\mapper\QuestionAnswerMapper.xml]
### The error may involve net.trueland.huazhi.ai.api.mapper.QuestionAnswerMapper.selectQaList
### The error occurred while executing a query
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM t_question_answer tqa INNER JOIN t_document td ON tqa.document_id = td.id AND td.deleted = 0 WHERE tqa.deleted = 0 AND ((td.standard_id IS NOT NULL AND td.standard_id != '' AND td.security_level <= ? + 3) OR ((td.standard_id IS NULL OR td.standard_id = '') AND td.security_level <= ? + 3)) AND td.name = ? 

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.4.jar:3.5.4]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149) ~[mybatis-3.5.4.jar:3.5.4]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.4.jar:3.5.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_351]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_351]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.4.jar:2.0.4]
	... 82 common frames omitted
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM t_question_answer tqa INNER JOIN t_document td ON tqa.document_id = td.id AND td.deleted = 0 WHERE tqa.deleted = 0 AND ((td.standard_id IS NOT NULL AND td.standard_id != '' AND td.security_level <= ? + 3) OR ((td.standard_id IS NULL OR td.standard_id = '') AND td.security_level <= ? + 3)) AND td.name = ? 

	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:39) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:253) ~[mybatis-plus-extension-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:201) ~[mybatis-plus-extension-3.3.2.jar:3.3.2]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.4.jar:3.5.4]
	at com.sun.proxy.$Proxy217.prepare(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:92) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.5.4.jar:3.5.4]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.4.jar:3.5.4]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:163) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.query(MybatisCachingExecutor.java:90) ~[mybatis-plus-core-3.3.2.jar:3.3.2]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.4.jar:3.5.4]
	... 88 common frames omitted
Caused by: dm.jdbc.driver.DMException: 第1 行附近出现错误:
数据类型不匹配
	at dm.jdbc.driver.DBError.throwException(DBError.java:667) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.a.b.p.F(MSG.java:536) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.a.b.p.C(MSG.java:496) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.a.b.p.B(MSG.java:477) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.a.a.a(DBAccess.java:837) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.a.a.a(DBAccess.java:216) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbPreparedStatement.prepareSql(DmdbPreparedStatement.java:205) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbPreparedStatement.allocateHandle(DmdbPreparedStatement.java:173) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbPreparedStatement.<init>(DmdbPreparedStatement.java:125) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbPreparedStatement.<init>(DmdbPreparedStatement.java:140) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbConnection.do_prepareStatement(DmdbConnection.java:713) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbConnection.do_prepareStatement(DmdbConnection.java:699) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at dm.jdbc.driver.DmdbConnection.prepareStatement(DmdbConnection.java:1316) ~[DmJdbcDriver18-8.1.1.193.jar:- 8.1.1.193 - Production]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:377) ~[druid-1.2.8.jar:1.2.8]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_351]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_351]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.5.4.jar:3.5.4]
	at com.sun.proxy.$Proxy218.prepareStatement(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:238) ~[mybatis-plus-extension-3.3.2.jar:3.3.2]
	... 98 common frames omitted
```

**Comment by miemieYaho** [comment]
Caused by: dm.jdbc.driver.DMException: 第1 行附近出现错误:
数据类型不匹配

**Comment by yasuo-deng** [comment]
![image](https://github.com/user-attachments/assets/648d05f4-ff7e-41a3-9bed-8fb8109df16f)
看报错就这一行不匹配，跟我的分页插件配置或者mp的版本有关系吗

**Comment by miemieYaho** [comment]
你用xml方式跑一遍目标SQL不就知道了，把问号变成#{值}形式

**Comment by yasuo-deng** [comment]
找到问题了，达梦text字段类型不能用等号判断，需要改成这种。and TEXT_EQUAL(td.name , #{quesAnswer.sourceDocumentName})
