### ISSUE TITLE
[错误报告]: YML 配置加密配合@PostConstruct时提示Access denied for user 'mpw:*********' (using password: YES)

### ISSUE THREAD

**Issue by libin-tech** [baomidou/mybatis-plus#6630]
### 确认

- [X] 我使用的版本是[最新版](https://central.sonatype.com/search?q=g:com.baomidou%20%20a:mybatis-plus&smo=true), 并且使用插件确认过项目里无依赖版本冲突
- [X] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [X] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 当前程序版本

3.5.7

### 问题描述

application.yml:

spring:
  datasource:
    url: jdbc:mysql://xxxxxxxxx
    username: mpw:**********
    password: mpw:**********

-- i need this query database
@PostConstruct
  public void init() {
     long count = demoDAO.count();
      
  }

-- 此时启动后会报错

### 详细堆栈日志

```bash
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'mpw:******************'@'pub.zb-tech.com' (using password: YES)
### The error may exist in com/xxxx/xxxx/dal/mapper/ApplicationInfoMapper.java (best guess)
### The error may involve com.xxxx.xxxx.dal.mapper.ApplicationInfoMapper.selectCount
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'mpw:******************'@'pub.zb-tech.com' (using password: YES)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332) ~[spring-context-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.39.jar:5.3.39]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932) ~[spring-context-5.3.39.jar:5.3.39]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) ~[spring-context-5.3.39.jar:5.3.39]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) [spring-boot-2.7.18.jar:2.7.18]
	at com.xxxxx.xxxxx.bootstarp.BootstrapApplication.main(BootstrapApplication.java:42) [classes/:na]
```

**Comment by melonhzp** [comment]
你在启动时，有通过命令行参数或环境变量传递密钥吗？详细说明见[如何使用](https://baomidou.com/guides/security/#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)

**Comment by libin-tech** [comment]
> 你在启动时，有通过命令行参数或环境变量传递密钥吗？详细说明见[如何使用](https://baomidou.com/guides/security/#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)

-Dmpw.key=xxxxx 已配置。

**Comment by nieqiurong** [comment]
![image](https://github.com/user-attachments/assets/269f262d-ddd3-49b7-ab44-92e1c3b17b97)

**Comment by nieqiurong** [comment]
#6625
