### ISSUE TITLE
分页查询报错

### ISSUE THREAD

**Issue by loulley** [baomidou/mybatis-plus#699]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
查询分页，放在一起查询，报错，如下：
    IPage<BankInfo> bankPage = bankInfoDao.selectPage(page,qw);
   IPage<Map<String, Object>> bankMapsPage = bankInfoDao.selectMapsPage(page,qw);
![image](https://user-images.githubusercontent.com/19515237/49919509-cb7f1480-fee1-11e8-986b-95d1b3b30021.png)

但不放在一起，又好了
![image](https://user-images.githubusercontent.com/19515237/49919572-fff2d080-fee1-11e8-970d-da2fad5d2db9.png)

### 重现步骤
junit执行即可

### 报错信息

java.lang.ClassCastException: java.util.HashMap cannot be cast to com.x.spring.entity.master.BankInfo

	at com.x.spring.junit.UserInfoDaoTest$$Lambda$67/991363637.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.x.spring.junit.UserInfoDaoTest.testPage(UserInfoDaoTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by miemieYaho** [comment]
什么叫放在一起?

**Comment by loulley** [comment]
请看截图，两个分页方法上下两行写在一起

**Comment by miemieYaho** [comment]
page 不要复用
