### ISSUE TITLE
kotlin 使用 QueryWrapper 报错，版本：3.0.6

### ISSUE THREAD

**Issue by legendsf** [baomidou/mybatis-plus#716]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

kotlin 简单使用 queryWrapper 查询报错。
使用 selectByMap 使用正常。

### 重现步骤

    @Test
    fun test_query() {

        var lq = QueryWrapper<LubanUser>().lambda().eq(LubanUser::userName, "songfei")
        var list1 = lubanUserMapper?.selectList(lq)
        println(list1)
    }

### 报错信息
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: 该方法仅能传入 lambda 表达式产生的合成类
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:51)
	at com.baomidou.mybatisplus.core.toolkit.support.SerializedLambda.resolve(SerializedLambda.java:58)
	at com.baomidou.mybatisplus.core.toolkit.LambdaUtils.lambda$resolve$24(LambdaUtils.java:61)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.baomidou.mybatisplus.core.toolkit.LambdaUtils.resolve(LambdaUtils.java:60)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:55)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:37)
	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.lambda$addCondition$7fff9b71$1(AbstractWrapper.java:358)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.baomidou.mybatisplus.core.conditions.segments.NormalSegmentList.getSqlSegment(NormalSegmentList.java:92)
	at com.baomidou.mybatisplus.core.conditions.segments.MergeSegments.getSqlSegment(MergeSegments.java:66)
	at com.baomidou.mybatisplus.core.conditions.AbstractWrapper.getSqlSegment(AbstractWrapper.java:465)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:899)
	at org.apache.ibatis.ognl.OgnlRuntime.getMethodValue(OgnlRuntime.java:1709)
	... 72 more

**Comment by miemieYaho** [comment]
lambdaQueryWrapper 不支持 kotlin, 非要使用 kotlin 用最新快照里面的 KtQueryWrapper 和 KtUpdateWrapper

**Comment by legendsf** [comment]
多谢大神

**Comment by qmdx** [comment]
> 建议KtQueryWrapper提供一个只需要bean class的构造函数

来 PR
