### ISSUE TITLE
版本3.0.6，使用h2数据库进行代码生成失败，原因h2不支持show table status

### ISSUE THREAD

**Issue by lizhonghua983094718** [baomidou/mybatis-plus#737]
### 当前使用版本(必须填写清楚，否则不予处理)
版本3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
使用h2数据库进行代码生成

### 重现步骤
直接代码生成

### 报错信息

org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
show table status [42001-197]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
at org.h2.message.DbException.getSyntaxError(DbException.java:217)
at org.h2.command.Parser.getSyntaxError(Parser.java:555)
at org.h2.command.Parser.readTerm(Parser.java:3298)
at org.h2.command.Parser.readFactor(Parser.java:2587)
at org.h2.command.Parser.readSum(Parser.java:2574)
at org.h2.command.Parser.readConcat(Parser.java:2544)
at org.h2.command.Parser.readCondition(Parser.java:2370)
at org.h2.command.Parser.readAnd(Parser.java:2342)
at org.h2.command.Parser.readExpression(Parser.java:2334)
at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:2245)
at org.h2.command.Parser.parseSelectSimple(Parser.java:2277)
at org.h2.command.Parser.parseSelectSub(Parser.java:2133)
at org.h2.command.Parser.parseSelectUnion(Parser.java:1946)
at org.h2.command.Parser.parseSelect(Parser.java:1919)
at org.h2.command.Parser.parsePrepared(Parser.java:463)
at org.h2.command.Parser.parse(Parser.java:335)
at org.h2.command.Parser.parse(Parser.java:311)
at org.h2.command.Parser.prepare(Parser.java:262)
at org.h2.engine.Session.prepare(Session.java:576)
at org.h2.engine.Session.prepare(Session.java:560)
at org.h2.command.Parser.prepare(Parser.java:1050)
at org.h2.command.Parser.parseShow(Parser.java:1042)
at org.h2.command.Parser.parsePrepared(Parser.java:473)
at org.h2.command.Parser.parse(Parser.java:335)
at org.h2.command.Parser.parse(Parser.java:307)
at org.h2.command.Parser.prepareCommand(Parser.java:278)
at org.h2.engine.Session.prepareLocal(Session.java:611)
at org.h2.engine.Session.prepareCommand(Session.java:549)
at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
at org.h2.jdbc.JdbcPreparedStatement.(JdbcPreparedStatement.java:76)
at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:469)
at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:301)
at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.(ConfigBuilder.java:146)
at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:88)
at com.lzh.test.generator.CodeGenerator.main(CodeGenerator.java:61)

**Comment by yuxiaobin** [comment]
H2数据库代码生成已提交到3.0分支

https://gitee.com/baomidou/mybatis-plus/commit/511d7b32b42b408b9f73b4f5a411487590cb9bdb

测试用例

https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus/src/test/java/com/baomidou/mybatisplus/test/h2/GenerateCode4H2Database.java
