### ISSUE TITLE
3.06中 代码生成器 判断sqlserver driver 直接报错 

### ISSUE THREAD

**Issue by fireicewater** [baomidou/mybatis-plus#746]
### 当前使用版本(必须填写清楚，否则不予处理)
3.06

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

在 DataSourceConfig 这个方法中 没有判断sqlserver的情况
  public DbType getDbType() {
        if (null == this.dbType) {
            if (this.driverName.contains("mysql")) {
                this.dbType = DbType.MYSQL;
            } else if (this.driverName.contains("oracle")) {
                this.dbType = DbType.ORACLE;
            } else if (this.driverName.contains("postgresql")) {
                this.dbType = DbType.POSTGRE_SQL;
            } else if (this.driverName.contains("db2")) {
                this.dbType = DbType.DB2;
            } else {
                if (!this.driverName.contains("mariadb")) {
                    throw ExceptionUtils.mpe("Unknown type of database!", new Object[0]);
                }

                this.dbType = DbType.MARIADB;
            }
        }

        return this.dbType;
    }

### 报错信息

Exception in thread "main" com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Unknown type of database!
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:51)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbType(DataSourceConfig.java:129)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbQuery(DataSourceConfig.java:86)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerDataSource(ConfigBuilder.java:288)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:139)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:88)
	at com.CodeGenerator.main(CodeGenerator.java:136)

**Comment by miemieYaho** [comment]
尝试使用 `3.0.7`
