### ISSUE TITLE
能提供sqlite 的支持吗

### ISSUE THREAD

**Issue by owendawn** [baomidou/mybatis-plus#748]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.6

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

无法识别数据库

### 重现步骤

代码生成器阶段

### 报错信息

Exception in thread "main" com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Unknown type of database!

**Comment by miemieYaho** [comment]
欢迎 pr

**Comment by miemieYaho** [comment]
本身支持

**Comment by owendawn** [comment]
Exception in thread "main" com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Unknown type of database!
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:51)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbType(DataSourceConfig.java:129)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getDbQuery(DataSourceConfig.java:86)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerDataSource(ConfigBuilder.java:288)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:139)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:88)
	at CodeGenerator.main(CodeGenerator.java:122)

**Comment by owendawn** [comment]
public DbType getDbType() {
        if (null == this.dbType) {
            if (this.driverName.contains("mysql")) {
                this.dbType = DbType.MYSQL;
            } else if (this.driverName.contains("oracle")) {
                this.dbType = DbType.ORACLE;
            } else if (this.driverName.contains("postgresql")) {
                this.dbType = DbType.POSTGRE_SQL;
            } else if (this.driverName.contains("db2")) {
                this.dbType = DbType.DB2;
            } else {
                if (!this.driverName.contains("mariadb")) {
                    throw ExceptionUtils.mpe("Unknown type of database!", new Object[0]);
                }

                this.dbType = DbType.MARIADB;
            }
        }

**Comment by owendawn** [comment]
代码生成器报错

**Comment by miemieYaho** [comment]
这得有人 pr了
