### ISSUE TITLE
使用 QueryWrapper 查询 时 ，如果选择查询的列带有id,报异常

### ISSUE THREAD

**Issue by niuguangyue** [baomidou/mybatis-plus#776]
### 当前使用版本(必须填写清楚，否则不予处理)

当前使用版本 3.0.7

问题：
使用 QueryWrapper 查询 时 ，如果选择查询的列带有id,报异常， 如果选择查询的列没有id, 不报异常

查询代码：

LambdaQueryWrapper<OrderHeader> queryWrapper = new QueryWrapper<OrderHeader>().lambda();        queryWrapper.eq(OrderHeader::getThirdPartyNo,"6b982cc").select(OrderHeader::getId,OrderHeader::getThirdPartyNo,OrderHeader::getAmount,OrderHeader::getBatchNo);
	        System.out.println(queryWrapper.getSqlSegment()+"  "+queryWrapper.getSqlSelect());
	        List<OrderHeader> list = iOrderHeaderService.list(queryWrapper);

实体类信息：

@Data
@Accessors(chain = true)
public class OrderHeader implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 主键
     */
    @TableId("id")
    private Long id;

    /**
     * 订单号
     */
    @TableField("trans_no")
    private String transNo;

    /**
     * 业务批次编号
     */
    @TableField("batch_no")
    private String batchNo;

报错信息：

com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: your property named id cannot find the corresponding database column name!
	at com.baomidou.mybatisplus.core.toolkit.ExceptionUtils.mpe(ExceptionUtils.java:51)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.lambda$getColumn$1(AbstractLambdaWrapper.java:84)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.getColumn(AbstractLambdaWrapper.java:84)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:70)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.lambda$columnsToString$0(AbstractLambdaWrapper.java:61)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnsToString(AbstractLambdaWrapper.java:61)
	at com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper.select(LambdaQueryWrapper.java:77)
	at

**Comment by miemieYaho** [comment]
用最新版
