### ISSUE TITLE
SqlFormatter的format方法存在bug

### ISSUE THREAD

**Issue by cjiewong** [baomidou/mybatis-plus#783]
### 当前使用版本(必须填写清楚，否则不予处理)
com.baomidou:mybatis-plus-boot-starter:2.2.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
开启了PerformanceInterceptor就可能会出现此bug
定位到bug点在com.baomidou.mybatisplus.toolkit.SqlFormatter类的format方法。
当特殊情况下实体类的某一个字段set的值包含单引号就会触发此bug
具体是什么特殊情况查起来很累  没深入排查  重现步骤中的传入的source参数是debug时候拷贝出来的

### 重现步骤
    public static void main(String[] args) {
        new SqlFormatter().format(" INSERT INTO bianla_easemob_chat_record \n" +
                " ( msg_id,\n" +
                "\tmsg_send_time,\n" +
                "\tdirection,\n" +
                "\tsend_from,\n" +
                "\tsend_to,\n" +
                "\tchat_type,\n" +
                "\tbodies,\n" +
                "\tmsg,\n" +
                "\text,\n" +
                "\t`type`,\n" +
                "\tcreated )  VALUES \n" +
                " ( '555794876462008332',\n" +
                "\t'2019-01-09 02:07:58.848',\n" +
                "\t'outgoing',\n" +
                "\t'bianla_67248',\n" +
                "\t'bianla_5197773',\n" +
                "\t'chat',\n" +
                "\t'\\'dfsfsfsdf',\n" +
                "\t'[):][):]',\n" +
                "\t'{}',\n" +
                "\t'txt',\n" +
                "\t'2019-01-09 17:45:33.992' )");
    }

### 报错信息

Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.util.NoSuchElementException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at com.sun.proxy.$Proxy70.insert(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.6.jar:3.4.6]
	at com.sun.proxy.$Proxy75.insert(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insert(ServiceImpl.java:98) ~[mybatis-plus-support-2.2.0.jar:na]
	at com.baomidou.mybatisplus.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$3e2398a4.invoke(<generated>) ~[mybatis-plus-support-2.2.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.bianla.service.impl.EasemobChatRecordServiceImpl$$EnhancerBySpringCGLIB$$5e33f48d.insert(<generated>) ~[classes/:na]
	at com.bianla.runner.ApplicationRunnerServiceImpl.lambda$downloadAndDeal$1(ApplicationRunnerServiceImpl.java:93) ~[classes/:na]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_151]
	at com.bianla.runner.ApplicationRunnerServiceImpl.downloadAndDeal(ApplicationRunnerServiceImpl.java:60) ~[classes/:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:897) ~[na:1.8.0_151]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:1.8.0_151]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[na:1.8.0_151]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[na:1.8.0_151]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[na:1.8.0_151]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_151]
	at com.bianla.runner.ApplicationRunnerServiceImpl.pullChatRecordByRecordTime(ApplicationRunnerServiceImpl.java:116) ~[classes/:na]
	at com.bianla.runner.EasemobChatRecordPullApplicationRunner.lambda$run$2(EasemobChatRecordPullApplicationRunner.java:38) ~[classes/:na]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_151]
	at com.bianla.runner.EasemobChatRecordPullApplicationRunner.run(EasemobChatRecordPullApplicationRunner.java:38) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:788) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 10 common frames omitted
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.util.NoSuchElementException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) ~[mybatis-3.4.6.jar:3.4.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.2.jar:1.3.2]
	... 48 common frames omitted
Caused by: java.util.NoSuchElementException: null
	at java.util.LinkedList.removeLast(LinkedList.java:283) ~[na:1.8.0_151]
	at com.baomidou.mybatisplus.toolkit.SqlFormatter$FormatProcess.closeParen(SqlFormatter.java:300) ~[mybatis-plus-support-2.2.0.jar:na]
	at com.baomidou.mybatisplus.toolkit.SqlFormatter$FormatProcess.perform(SqlFormatter.java:143) ~[mybatis-plus-support-2.2.0.jar:na]
	at com.baomidou.mybatisplus.toolkit.SqlFormatter.format(SqlFormatter.java:75) ~[mybatis-plus-support-2.2.0.jar:na]
	at com.baomidou.mybatisplus.toolkit.SqlUtils.sqlFormat(SqlUtils.java:148) ~[mybatis-plus-support-2.2.0.jar:na]
	at com.baomidou.mybatisplus.plugins.PerformanceInterceptor.intercept(PerformanceInterceptor.java:161) ~[mybatis-plus-core-2.2.0.jar:na]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.6.jar:3.4.6]
	at com.sun.proxy.$Proxy86.update(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[mybatis-3.4.6.jar:3.4.6]
	... 54 common frames omitted

**Comment by miemieYaho** [comment]
已确认,修复中

**Comment by qmdx** [comment]
https://mp.baomidou.com/guide/p6spy.html
