### ISSUE TITLE
分页导致传入参数绑定不到

### ISSUE THREAD

**Issue by yuhou615** [baomidou/mybatis-plus#813]
### 当前使用版本(必须填写清楚，否则不予处理)
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.6</version>
 </dependency>

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

** 分页得对象，和参数的集合对象同时传入不行吗？

### 重现步骤
 1，public class PageBase<T> extends Page<T>

2， List<TkUser> getPageData(PageBase page,UserQuery query);

3， <select id="getPageData"  resultType="com.ttzs.serving.app.model.to.TkUser">

        select * from tk_user where state = 0

        <if test="name !=null ">
            and  name = #{name}
        </if>

    </select>

### 报错信息
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'name' not found. Available parameters are [arg1, arg0, param1, param2]
at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy98.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany(PageMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy102.getPageData(Unknown Source)

**Comment by miemieYaho** [comment]
https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-pagination/src/main/java/com/baomidou/mybatisplus/samples/pagination/mapper/UserMapper.java
