### ISSUE TITLE
通过注解的方式无法使用分页查询插件

### ISSUE THREAD

**Issue by littleSkylark** [baomidou/mybatis-plus#844]
### 该问题是怎么引起的？
自己的mapper中通过ibatis注解(@Select)只能返回List<T>，不能返回IPage<T>

### 重现步骤
```
package lark.demo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import lark.demo.model.po.NotifyTask;
public interface NotifyTaskMapper extends BaseMapper<NotifyTask> {

	@Select("select * from cms_notify_task")
	IPage<NotifyTask> selectPages(Page<NotifyTask> page);
}
```
### 报错信息
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: Error instantiating interface 
com.baomidou.mybatisplus.core.metadata.IPage with invalid types () or values (). Cause: 		 
java.lang.NoSuchMethodException: com.baomidou.mybatisplus.core.metadata.IPage.<init>()

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy92.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany2(PageMapperMethod.java:128)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:98)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy93.selectPages(Unknown Source)
	at lark.demo.service.impl.NotifyTaskServiceImpl.selectPage(NotifyTaskServiceImpl.java:36)
	at lark.demo.service.impl.NotifyTaskServiceImpl$$FastClassBySpringCGLIB$$ec013afd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at lark.demo.service.impl.NotifyTaskServiceImpl$$EnhancerBySpringCGLIB$$65209536.selectPage(<generated>)
```

**Comment by miemieYaho** [comment]
下个版本支持
