### ISSUE TITLE
3.0.7.1 版本找不到 H2Query 代码生成错误

### ISSUE THREAD

**Issue by gclm** [baomidou/mybatis-plus#849]
### 当前使用版本(必须填写清楚，否则不予处理)
3.0.7.1

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

使用h2数据库进行代码生成，官方生成demo中  .setDbQuery(new H2Query())，在3.0.7.1 已找不到该类，不使用该类生成代码报以下错误，并生成空文件夹
 
### 重现步骤

直接代码生成

### 报错信息

org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
show table status [42001-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.getSyntaxError(DbException.java:217)
	at org.h2.command.Parser.getSyntaxError(Parser.java:555)
	at org.h2.command.Parser.readTerm(Parser.java:3298)
	at org.h2.command.Parser.readFactor(Parser.java:2587)
	at org.h2.command.Parser.readSum(Parser.java:2574)
	at org.h2.command.Parser.readConcat(Parser.java:2544)
	at org.h2.command.Parser.readCondition(Parser.java:2370)
	at org.h2.command.Parser.readAnd(Parser.java:2342)
	at org.h2.command.Parser.readExpression(Parser.java:2334)
	at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:2245)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2277)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2133)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1946)
	at org.h2.command.Parser.parseSelect(Parser.java:1919)
	at org.h2.command.Parser.parsePrepared(Parser.java:463)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:311)
	at org.h2.command.Parser.prepare(Parser.java:262)
	at org.h2.engine.Session.prepare(Session.java:576)
	at org.h2.engine.Session.prepare(Session.java:560)
	at org.h2.command.Parser.prepare(Parser.java:1050)
	at org.h2.command.Parser.parseShow(Parser.java:1042)
	at org.h2.command.Parser.parsePrepared(Parser.java:473)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:469)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:301)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:146)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:88)
	at club.gclmit.paymentcode.CodeGenerator.main(CodeGenerator.java:84)
22:09:20.757 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/pojo]
22:09:20.757 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/controller]
22:09:20.758 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/mapper/xml]
22:09:20.758 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/service]
22:09:20.758 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/service/impl]
22:09:20.758 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================

**Comment by gclm** [comment]
手动创建 H2Query，代码为示例 demo 中的代码。出现找不到数据库错误。

# 控制台信息
08:19:27.654 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
表 [PAY_USER, PAY_QR] 在数据库中不存在！！！
08:19:28.374 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/pojo]
08:19:28.375 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/controller]
08:19:28.375 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/mapper/xml]
08:19:28.375 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/service]
08:19:28.375 [main] DEBUG com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine - 创建目录： [/Volumes/Workspace/codes/back-end/java/me/payment-code/src/main/java/club/gclmit/qr/service/impl]
08:19:28.375 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================文件生成完成！！！==========================

**Comment by yuxiaobin** [comment]
H2生成代码是1月8号才提交，3.0.7.1是1月2号发的版本，还没包括这部分的代码。

需要使用，可以自己到https://gitee.com/baomidou/mybatis-plus 下源码 自己install到本地仓库使用
