### ISSUE TITLE
3.0.7.1版本和spring boot 2.1.3.RELEASE版本一起使用，启动报错

### ISSUE THREAD

**Issue by zjl-bright** [baomidou/mybatis-plus#858]
插件的3.0.7.1版本和spring boot 2.1.3.RELEASE版本一起使用，启动报错

### 报错信息
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.baomidou.mybatisplus.extension.service.impl.ServiceImpl] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:686) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:583) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:596) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:568) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:248) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 29 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/baomidou/mybatisplus/core/conditions/update/Update
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_151]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_151]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[na:1.8.0_151]
	at java.lang.Class.getMethods(Class.java:1615) ~[na:1.8.0_151]
	at org.springframework.util.ReflectionUtils.findConcreteMethodsOnInterfaces(ReflectionUtils.java:696) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:669) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 33 common frames omitted

**Comment by miemieYaho** [comment]
自行处理

**Comment by zjl-bright** [comment]
我这里临时的解决方案是用了3.0.6版本

**Comment by yuxiaobin** [comment]
sample项目升级: BOOT-STARTER 2.1.3.RELEASE + MP 3.0.7.1
没有发现问题

https://gitee.com/baomidou/mybatis-plus-samples

**Comment by Cat7373** [comment]
我也混用了这俩版本，老项目单元测试 100% 通过😂
