### ISSUE TITLE
IService中的IPage<T> page(IPage<T> var1, Wrapper<T> var2)不传var1报错，能默认查全部不

### ISSUE THREAD

**Issue by 255793613** [baomidou/mybatis-plus#866]
### 当前使用版本(必须填写清楚，否则不予处理)
v3.0.7

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

IService中的IPage<T> page(IPage<T> var1, Wrapper<T> var2)不传var1报错，能默认查全部不,
不然报错。。。

java.lang.NullPointerException
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:97)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy93.selectPage(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.page(ServiceImpl.java:279)
	at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl$$FastClassBySpringCGLIB$$76535273.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.xfhl.meeting.service.impl.AppServiceImpl$$EnhancerBySpringCGLIB$$61e11a99.page(<generated>)

**Comment by qmdx** [comment]
请使用 selectList
