### ISSUE TITLE
代码生成问题

### ISSUE THREAD

**Issue by zhengxiaoya2017** [baomidou/mybatis-plus#919]
### 当前使用版本(必须填写清楚，否则不予处理)

3.0.8.4-SNAPSHOT

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**
直接下载的代码，运行MysqlGenerator

### 重现步骤

运行代码生成main方法

### 报错信息
Exception in thread "main" java.lang.NoClassDefFoundError: freemarker/template/Configuration
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.init(FreemarkerTemplateEngine.java:41)
	at com.baomidou.mybatisplus.generator.engine.FreemarkerTemplateEngine.init(FreemarkerTemplateEngine.java:34)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:98)
	at com.baomidou.mybatisplus.samples.generator.MysqlGenerator.main(MysqlGenerator.java:115)
Caused by: java.lang.ClassNotFoundException: freemarker.template.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

**Comment by miemieYaho** [comment]
自己引入 freemarker
