### ISSUE TITLE
3.1.0的缺少依赖jar

### ISSUE THREAD

**Issue by sdisk** [baomidou/mybatis-plus#947]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=mybatis-plus)上已修复的会直接**close**掉)**

pom.xml文件引用了
```
<dependency>
	<groupId>com.baomidou</groupId>
	<artifactId>mybatis-plus-boot-starter</artifactId>
	<version>3.1.0</version>
</dependency>
```
换成低版本 3.0.6后，启动正常

### 重现步骤

引入jar出现问题，发现问题

### 报错信息
Caused by: java.lang.ClassNotFoundException: org.mybatis.logging.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
	... 73 common frames omitted

**Comment by lzp3021** [comment]
去掉mybatis-boot-starter

**Comment by xiaolshi** [comment]
> mybatis-boot-starter

没有用
