### ISSUE TITLE
自定义批量逻辑删除方法

### ISSUE THREAD

**Issue by shmily2038** [baomidou/mybatis-plus#963]
### 当前使用版本(必须填写清楚，否则不予处理)
3.1.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
<script>
UPDATE user <set> rec_status=1,modify_time=now(),rec_ver=rec_ver+1  </set> WHERE  rec_status=0 and <choose> <when test="list!=null and list.size()>0">(id,tenant_id,rec_ver) in <foreach collection="list" item="item" index="index" open="(" separator="," close=")">(#{item.id},#{item.tenantId},#{item.recVer})</foreach></when><otherwise>1!=1</otherwise></choose>
</script>
生成脚本的sql如上

### 重现步骤
先执行查询SQL，获取到数据列表，然后传入batchDelete方法，就报错

### Error updating database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: UPDATE user  SET rec_status=1,modify_time=now(),rec_ver=rec_ver+1  WHERE  rec_status=0 and ( (id,tenant_id,rec_ver) in  (  (?,?,?) , (?,?,?) , (?,?,?) ) )
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, please exclude the tableName or statementId.
 Error SQL: UPDATE user  SET rec_status=1,modify_time=now(),rec_ver=rec_ver+1  WHERE  rec_status=0 and ( (id,tenant_id,rec_ver) in  (  (?,?,?) , (?,?,?) , (?,?,?) ) )] with root cause

net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 97.

Was expecting one of:

    "&&"
    ")"
    "AND"

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:19398) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:19248) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:6088) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:6051) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.AndExpression(CCJSqlParser.java:6142) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.OrExpression(CCJSqlParser.java:6051) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Expression(CCJSqlParser.java:6022) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.WhereClause(CCJSqlParser.java:5379) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Update(CCJSqlParser.java:822) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:140) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParser.Statements(CCJSqlParser.java:455) ~[jsqlparser-1.4.jar:na]
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatements(CCJSqlParserUtil.java:152) ~[jsqlparser-1.4.jar:na]
	at com.baomidou.mybatisplus.core.parser.AbstractJsqlParser.parser(AbstractJsqlParser.java:60) ~[mybatis-plus-core-3.1.0.jar:3.1.0]
	at com.baomidou.mybatisplus.extension.handlers.AbstractSqlParserHandler.sqlParser(AbstractSqlParserHandler.java:66) ~[mybatis-plus-extension-3.1.0.jar:3.1.0]
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.intercept(PaginationInterceptor.java:127) ~[mybatis-plus-extension-3.1.0.jar:3.1.0]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.0.jar:3.5.0]
	at com.sun.proxy.$Proxy82.prepare(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86) ~[mybatis-3.5.0.jar:3.5.0]

**Comment by miemieYaho** [comment]
自己写的自己排查

**Comment by shmily2038** [comment]
> 
> 
> 自己写的自己排查

主要是框架底层报错，我的SQL在mysql上执行是正常的

**Comment by miemieYaho** [comment]
jsqlparser 报错,无法解析你的 sql,检查去除不必要的里面有使用 jsqlparser  的插件

**Comment by shmily2038** [comment]
> 
> 
> jsqlparser 报错,无法解析你的 sql,检查去除不必要的里面有使用 jsqlparser 的插件

知道有使用jsqlparser，但是SQL是正常的，估计这个插件无法解析此SQL语法，导致无法处理，只能换种姿势来，是吗？
